function m(b,a,c,d){b.j.qb(b.ub,a,c,d)}function n(b,a,c,d){b.j.ba?m(b,a,c,d):b.j.Ve()._OnMessageFromDOM({type:"event",component:b.ub,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function p(b,a,c){b.j.B(b.ub,a,c)}function v(b,a){for(const [c,d]of a)p(b,c,d)}function w(b){b.$b||(b.j.Gc(b.le),b.$b=!0)}window.Ea=class{constructor(b,a){this.j=b;this.ub=a;this.$b=!1;this.le=()=>this.Sa()}tc(){}Sa(){}};
window.Gf=class{constructor(){this.qd=-1}l(){-1!==this.qd&&(self.clearTimeout(this.qd),this.qd=-1)}};"use strict";class aa{constructor(b){this.xb=b;this.Xc=!1;this.dd=!0;this.zb=this.ra=this.rd=-1}}
function ba(b,a){const c=a.elementId,d=b.vc(c,a),e=new aa(d);b.Ma.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.dd=!!a.isVisible;d.addEventListener("focus",()=>{x(b,"elem-focused",c)});d.addEventListener("blur",()=>{x(b,"elem-blurred",c)});const f=a.htmlIndex;e.rd=f;e.zb=a.htmlZIndex;b.Va&&(a=b.j.xc(f),e.ra=a,b.j.kb(a).appendChild(d))}function da(b,a){p(b,"get-element",c=>{const d=y(b,c.elementId);return a(d,c)})}
function y(b,a){b=b.Ma.get(a);if(!b)throw Error(`no element with id ${a}`);return b.xb}function x(b,a,c,d){d||(d={});d.elementId=c;m(b,a,d)}function fa(b,a){var c;c||(c={});c.elementId=a;n(b,"click",c)}
window.Ob=class extends self.Ea{constructor(b,a){super(b,a);this.Ma=new Map;this.Va=!0;v(this,[["create",c=>ba(this,c)],["destroy",c=>{c=c.elementId;const d=y(this,c);this.Va&&d.parentElement.removeChild(d);this.Ma.delete(c)}],["set-visible",c=>{if(this.Va){var d=this.Ma.get(c.elementId),e=d.xb;d.Xc?e.style.display=c.isVisible?"":"none":d.dd=!!c.isVisible}}],["update-position",c=>{if(this.Va){var d=this.Ma.get(c.elementId),e=d.xb,f=this.j;e.style.left=c.left+"px";e.style.top=c.top+"px";e.style.width=
c.width+"px";e.style.height=c.height+"px";var g=c.fontSize;null!==g&&(e.style.fontSize=g+"em");g=c.htmlIndex;d.rd=g;g=f.xc(g);g!==d.ra&&(e.remove(),f.kb(g).appendChild(e),d.ra=g,f.Rc());c=c.htmlZIndex;c!==d.zb&&(d.zb=c,f.Rc());d.Xc||(d.Xc=!0,d.dd&&(e.style.display=""))}}],["update-state",c=>{const d=y(this,c.elementId);this.rb(d,c)}],["focus",c=>this.Oc(c)],["set-css-style",c=>{const d=y(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",
c=>{y(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{y(this,c.elementId).removeAttribute(c.name)}]]);da(this,c=>c)}vc(){throw Error("required override");}rb(){throw Error("required override");}Oc(b){var a=y(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const ha=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),z=/android/i.test(navigator.userAgent),ia=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);
let ja=0;function A(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.wf?new Promise(c=>{const d="c3_resolve_"+ja;++ja;self[d]=c;a.textContent=b.Af+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function ka(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let B=new Audio;
const la={"audio/webm; codecs=opus":!!B.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!B.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!B.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!B.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!B.canPlayType("audio/mp4"),"audio/mpeg":!!B.canPlayType("audio/mpeg")};B=null;async function ma(b){b=await na(b);return(new TextDecoder("utf-8")).decode(b)}
function na(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const oa=[];let D=0;window.RealFile=window.File;const E=[],pa=new Map,ta=new Map;let ua=0;const va=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");va.push(b)};const wa=new Set(["cordova","playable-ad","instant-games"]);let xa=!1;
window.ca=class b{constructor(a){this.ba=a.Cf;this.Aa=null;this.aa="";this.fb=a.zf;this.Mb={};this.Za=this.wa=null;this.Xa=[];this.na=null;this.Zd=!0;this.M=[];this.kd=[];this.ld=!1;this.me=()=>this.Te();this.ad=!1;this.Td=0;this.Bb=null;this.eb=-1;this.sf=()=>this.df();this.Jb=new Set;this.sd=null;this.ne=[];this.u=a.oe;this.ac="file"===location.protocol.substr(0,4);if("playable-ad"===this.u||"instant-games"===this.u)this.ba=!1;ia&&(this.ba=!1);if("cordova"===this.u&&this.ba&&z){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.ba=!1)}this.pa()?self.chrome.webview.addEventListener("message",c=>this.Id(c.data)):"macos-wkwebview"===this.u&&(self.C3WrapperOnMessage=c=>this.Id(c));this.dc=this.ta=null;"html5"!==this.u||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.hf(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.Ze());this.B("runtime","cordova-fetch-local-file",c=>this.$e(c));this.B("runtime","create-job-worker",()=>this.af());this.B("runtime","send-wrapper-extension-message",c=>this.gf(c));"cordova"===this.u?document.addEventListener("deviceready",()=>this.Sb(a)):this.Sb(a)}l(){this.Hc();this.Aa&&(this.Aa=this.Aa.onmessage=null);this.wa&&(this.wa.terminate(),this.wa=null);this.Za&&(this.Za.l(),this.Za=null);for(const {canvas:a,
ib:c}of this.M)a.remove(),c.remove();this.M.length=0}zd(){return this.M[0].canvas}xc(a){return Math.min(a,this.M.length-1)}kb(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].ib}_GetHTMLWrapElement(a){return this.kb(a)}Je(){return ha&&"cordova"===this.u}ob(){const a=navigator.userAgent;return ha&&wa.has(this.u)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}He(){return z}Ad(){return z&&wa.has(this.u)}Cd(){return"windows-webview2"===this.u||!!("preview"===
this.u&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}pa(){return this.Cd()||"xbox-uwp-webview2"===this.u}async Sb(a){this.ba&&!await ka()&&(this.ba=!1);"macos-wkwebview"===this.u?this.Ia({type:"ready"}):this.pa()&&(this.kf(),this.ne=(await this.Ye()).registeredComponentIds);if("playable-ad"===this.u){this.ta=self.c3_base64files;this.dc={};await this.Qe();for(let d=0,e=a.hb.length;d<e;++d){var c=a.hb[d];this.dc.hasOwnProperty(c)?a.hb[d]={wf:!0,Af:this.dc[c]}:this.ta.hasOwnProperty(c)&&
(a.hb[d]=URL.createObjectURL(this.ta[c]))}a.sc=[]}if("nwjs"===this.u&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Gc(()=>{d++;document.documentElement.style.opacity=0===d%2?"1":"0.999"})}a.yf?this.aa=a.yf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Ef&&(this.Mb=a.Ef);c=new MessageChannel;this.Aa=c.port1;this.Aa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&
window.c3_addPortMessageHandler(d=>this.cf(d));this.Bb=new self.Ke(this);await ya(this.Bb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ba?await this.Xe(a,c.port2):await this.We(a,c.port2)}Jc(a){a=this.Mb.hasOwnProperty(a)?this.Mb[a]:a.endsWith("/workermain.js")&&this.Mb.hasOwnProperty("workermain.js")?
this.Mb["workermain.js"]:"playable-ad"===this.u&&this.ta.hasOwnProperty(a)?this.ta[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async wc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.u&&this.ac)return a=await this.Nb(d.vf?a:this.fb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),
d)}return new Worker(a,d)}qa(){return Math.max(window.innerWidth,1)}ha(){return Math.max(window.innerHeight,1)}zc(){return this.pa()||(new Set(["cordova","nwjs","macos-wkwebview"])).has(this.u)?"standalone":window.matchMedia("(display-mode: fullscreen)").matches?"fullscreen":window.matchMedia("(display-mode: standalone)").matches?"standalone":window.matchMedia("(display-mode: minimal-ui)").matches?"minimal-ui":navigator.standalone?"standalone":"browser"}Gd(a){var c=this.aa,d=location.href,e=this.qa(),
f=this.ha(),g=this.zc(),h=window.devicePixelRatio,k=b.nb(),l=a.Kf,q=window.cr_previewImageBlobs||this.ta,r=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,u=window.cr_swClientId||"";a=a.oe;var ea=(new URLSearchParams(self.location.search)).has("debug"),H=this.Bb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,cssDisplayMode:g,devicePixelRatio:h,isFullscreen:k,projectData:l,previewImageBlobs:q,previewProjectFileBlobs:r,previewProjectFileSWUrls:t,swClientId:u,
exportType:a,isDebug:ea,ife:!!self.Jf,jobScheduler:{inputPort:H.$c,outputPort:H.jd,maxNumWorkers:H.pf},supportedAudioFormats:la,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.fb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.fb+"opus.wasm.wasm",isFileProtocol:this.ac,isiOSCordova:this.Je(),isiOSWebView:this.ob(),isWindowsWebView2:this.Cd(),isAnyWebView2Wrapper:this.pa(),wrapperComponentIds:this.ne,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Xe(a,c){const d=
this.Jc(a.Df);"preview"===this.u?(this.wa=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,q)=>{const r=t=>{this.wa.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():q()};this.wa.addEventListener("message",r);this.wa.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.wa=await this.wc(d,this.aa,{type:"module",name:"Runtime",vf:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();
document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,ib:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.sc||[],k=a.hb;h=await Promise.all(h.map(l=>this.Ta(l)));k=await Promise.all(k.map(l=>this.Ta(l)));if("cordova"===this.u)for(let l=0,q=a.rc.length;l<q;++l){const r=a.rc[l],t=r[0];if(t===a.td||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Ta(t)}this.wa.postMessage(Object.assign(this.Gd(a),
{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.rc,mainProjectScript:a.td,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...za(this.Bb)]);this.Xa=E.map(l=>new l(this));this.Fd();Aa(e);Ba(g);Ca(this.na);self.c3_callFunction=(l,q)=>{var r=this.na;return r.j.Dd(r.ub,"js-invoke-function",{name:l,params:q})};"preview"===this.u&&(self.goToLastErrorScript=()=>this.qb("runtime","go-to-last-error-script"))}async We(a,c){const d=
document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,ib:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Xa=E.map(h=>new h(this));this.Fd();Aa(d);Ba(e);e=a.hb.map(h=>"string"===typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.sc)){var f=[...a.sc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=
await Promise.all(e.map(h=>this.Ta(h)));await Promise.all(e.map(h=>A(h)));e=self.C3_ProjectScriptsStatus;f=a.td;const g=a.rc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Ta(k),await A(k),"preview"!==this.u||e[h]||this.Kd(h,"main script did not run to completion")}catch(l){this.Kd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=await this.Ta(k),await A(k);"preview"===this.u&&"object"!==typeof self.Ff.Hf?(this.Ub(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Gd(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:va}),Ca(this.na),this.Hd(),this.Za=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Za,a))}Kd(a,c){this.Ub();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Hd(){this.Ub()}Ub(){const a=
window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async af(){const a=await Da(this.Bb);return{outputPort:a,transferables:[a]}}hf(a){if(!this.ad){var c=a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,ib:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Zd&&(g.style.display="",h.style.display=
"");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Zd=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,ib:q}=this.M.pop();q.remove();this.ba&&!d?this.kd.push(l):l.remove()}else if(c>this.M.length)for(let l=0,q=c-this.M.length;l<q;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),
this.ba?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,Aa(c),Ba(d),this.M.push({canvas:c,ib:d});for(const l of this.Xa)if(l instanceof window.Ob&&l.Va)for(const q of l.Ma.values())e=l.j.xc(q.rd),f=q.ra,-1!==
e&&-1!==f&&e!==f&&(f=q.xb,f.remove(),l.j.kb(e).appendChild(f),q.ra=e);this.Rc();return{addedCanvases:a,transferables:k}}Ze(){for(const a of this.kd)a.remove();this.kd.length=0}Rc(){this.ld||(this.ld=!0,this.Gc(this.me))}Te(){this.Jd(this.me);this.ld=!1;let a=[];for(var c of this.Xa)if(c instanceof window.Ob){var d=c.Va?[...c.Ma.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.ra,l=h.ra;return k!==l?k-l:g.zb-h.zb});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.ra!==c&&(this.Ed(c,a.slice(d,
e)),c=g.ra,d=e)}d<e&&this.Ed(c,a.slice(d,e))}Ed(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.xb);var d=new Set(c);a=this.kb(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Ve(){if(this.ba)throw Error("not available in worker mode");return this.Za}qb(a,c,d,e,f){this.Aa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},
f)}Dd(a,c,d,e,f){const g=ua++,h=new Promise((k,l)=>{ta.set(g,{resolve:k,reject:l})});this.Aa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.bf(a);if("result"===c)this.ef(a);else if("runtime-ready"===c)this.ff();else if("alert-error"===c)this.Ub(),alert(a.message);else if("creating-runtime"===c)this.Hd();else throw Error(`unknown message '${c}'`);}bf(a){const c=a.component,d=a.handler,
e=a.data,f=a.responseId;if(a=pa.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Tb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Tb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Tb(f,!1,""+h)}):this.Tb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Tb(a,c,d){let e;d&&d.transferables&&
(e=d.transferables);this.Aa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}ef(a){const c=a.responseId,d=a.isOk;a=a.result;const e=ta.get(c);d?e.resolve(a):e.reject(a);ta.delete(c)}B(a,c,d){let e=pa.get(a);e||(e=new Map,pa.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static xa(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}Fd(){for(const a of this.Xa)if("runtime"===a.ub){this.na=a;return}throw Error("cannot find runtime DOM handler");
}cf(a){this.qb("debugger","message",a)}ff(){for(const a of this.Xa)a.tc()}static nb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||xa)}static Vb(a){xa=!!a}Gc(a){this.Jb.add(a);this.Qc()}Jd(a){this.Jb.delete(a);0===this.Jb.size&&this.Hc()}Qc(){-1===this.eb&&0<this.Jb.size&&(this.eb=requestAnimationFrame(this.sf))}Hc(){-1!==this.eb&&(cancelAnimationFrame(this.eb),this.eb=-1)}df(){this.eb=-1;for(const a of this.Jb)a();this.Qc()}Ha(a){this.na.Ha(a)}Ra(a){this.na.Ra(a)}Pc(){this.na.Pc()}Rb(a){this.na.Rb(a)}Ie(){return!!la["audio/webm; codecs=opus"]}async lf(a){a=
await this.Dd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Me(a){this.ad=!0;this.Td=a}Ge(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}Bd(a){return!this.Ge(a)}async Ta(a){return"cordova"===this.u&&(a.startsWith("file:")||this.ac&&this.Bd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Nb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async $e(a){const c=a.filename;switch(a.as){case "text":return await this.Fe(c);
case "buffer":return await this.Nb(c);default:throw Error("unsupported type");}}xd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async Fe(a){a=await this.xd(a);return await ma(a)}Ic(){if(oa.length&&!(8<=D)){D++;var a=oa.shift();this.Re(a.filename,a.Bf,a.uf)}}Nb(a){return new Promise((c,d)=>{oa.push({filename:a,Bf:e=>{D--;this.Ic();c(e)},uf:e=>{D--;this.Ic();d(e)}});this.Ic()})}async Re(a,c,d){try{const e=
await this.xd(a),f=await na(e);c(f)}catch(e){d(e)}}Id(a){if("entered-fullscreen"===a)b.Vb(!0),F(this.na);else if("exited-fullscreen"===a)b.Vb(!1),F(this.na);else if("object"===typeof a){const c=a.type;"directory-handles"!==c&&("wrapper-init-response"===c?(this.sd(a),this.sd=null):"extension-message"===c?this.qb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a))}else console.warn("Unknown wrapper message: ",a)}gf(a){this.Ia({type:"extension-message",componentId:a.componentId,
messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}Ia(a){this.pa()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.u&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}kf(){window.moveTo=(a,c)=>{this.Ia({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.Ia({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Ye(){return this.pa()?new Promise(a=>{this.sd=a;this.Ia({type:"wrapper-init"})}):
Promise.resolve()}async Qe(){const a=[];for(const [c,d]of Object.entries(this.ta))a.push(this.Pe(c,d));await Promise.all(a)}async Pe(a,c){if("object"===typeof c)this.ta[a]=new Blob([c.str],{type:c.type}),this.dc[a]=c.str;else{let d=await this.Ue(c);d||(d=this.Se(c));this.ta[a]=d}}async Ue(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}Se(a){a=this.jf(a);return this.Oe(a.data,a.xf)}jf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{xf:a,data:d}}Oe(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const G=self.ca,Fa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),I={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ga={dispatchUserScriptEvent:!0},Ha={dispatchRuntimeEvent:!0};function Ia(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}
function Ja(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function Ka(b){b=URL.createObjectURL(b);try{return await Ja(b)}finally{URL.revokeObjectURL(b)}}function La(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ma=new Set(["input","textarea","datalist","select"]),Na=new Set(["canvas","body","html"]);
function J(b){b.target.tagName&&Na.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Oa(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Pa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await Ka(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ka(b);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Qa=!1;document.addEventListener("pause",()=>Qa=!0);document.addEventListener("resume",()=>Qa=!1);function Aa(b){b.addEventListener("selectstart",J);b.addEventListener("gesturehold",J);b.addEventListener("pointerdown",J)}function Ba(b){b.addEventListener("selectstart",Oa);b.addEventListener("gesturehold",Oa);b.addEventListener("touchstart",Oa)}function Ca(b){b.Sd=!0;b.ed=b.j.qa();b.Cb=b.j.ha()}
function F(b){if(!b.la){var a=G.nb();a&&"any"!==b.od&&Ra(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.qa(),innerHeight:b.ha()})}}async function Sa(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ta(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ua(b){return await self.C3_GetSvgImageSize(b.blob)}function Va(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Wa(b){self.setTimeout(()=>{b.Rd=!0},1E3);"cordova"===b.j.u?(document.addEventListener("pause",()=>Xa(b,!0)),document.addEventListener("resume",()=>Xa(b,!1))):document.addEventListener("visibilitychange",()=>Xa(b,"hidden"===document.visibilityState));b.ic=!("hidden"!==document.visibilityState&&!Qa);return{isSuspended:b.ic}}
function Ya(b){b.Md||(b.Md=!0,window.addEventListener("deviceorientation",a=>{b.la||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},I)}),window.addEventListener("deviceorientationabsolute",a=>{b.la||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},I)}))}
function Za(b){b.Ld||(b.Ld=!0,window.addEventListener("devicemotion",a=>{if(!b.la){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},I)}}))}async function $a(b){await Ia(b.url)}
function ab(b,a){b.Ud=a.message;-1===b.Vc&&(b.Vc=setTimeout(()=>{b.Vc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Ud)},250))}function bb(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:G.nb(),innerWidth:b.qa(),innerHeight:b.ha()})}
function Xa(b,a){b.ic!==a&&((b.ic=a)?b.j.Hc():b.j.Qc(),m(b,"visibilitychange",{hidden:a}),!a&&b.j.ob()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function cb(b,a,c){"Backspace"===c.key&&J(c);"nwjs"===b.j.u&&"u"===c.key&&(c.ctrlKey||c.metaKey)&&c.preventDefault();if(!b.la){var d=Fa.get(c.code)||c.code;n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},I)}}
function K(b,a,c,d){b.la||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Da,pageX:c.pageX,pageY:c.pageY+b.Da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function L(b,a,c){if(!b.la){var d=0;"mouse"===c.pointerType&&(d=b.gd);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Da,pageX:c.pageX,pageY:c.pageY+b.Da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},I);"mouse"===c.pointerType&&
(b.gd=c.buttons)}}function db(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Da=a))}}
function eb(b,a,c,d){const e=b.qa(),f=b.ha();b.gb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:G.nb(),cssDisplayMode:b.j.zc()}):10>d&&fb(b,e,f,d+1)}function fb(b,a,c,d){-1!==b.gb&&clearTimeout(b.gb);b.gb=setTimeout(()=>eb(b,a,c,d),48)}
function Ra(b){b=b.od;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function gb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
G.xa(class extends self.Ea{constructor(b){super(b,"runtime");this.Sd=!1;this.gb=-1;this.od="any";this.ic=this.Ld=this.Md=!1;this.oc=document.createElement("div");this.oc.className="c3-screen-reader-text";this.oc.setAttribute("aria-live","polite");document.body.appendChild(this.oc);this.La=null;this.la=!1;this.Ud="";this.Vc=-1;this.Rd=!1;this.ed=b.qa();this.Cb=b.ha();this.Da=this.Lb=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Sa(c));b.B("runtime","raster-svg-image",c=>Ta(c));b.B("runtime","get-svg-image-size",c=>Ua(c));b.B("runtime","set-target-orientation",c=>{this.od=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Va(c));b.B("runtime","go-to-script",c=>Va(c));b.B("runtime","before-start-ticking",()=>Wa(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.La||(this.La=document.createElement("div"),this.La.id="inspectOutline",document.body.appendChild(this.La));var d=this.La;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.La&&(this.La.style.display="none")});b.B("runtime","enable-device-orientation",()=>Ya(this));b.B("runtime","enable-device-motion",()=>Za(this));b.B("runtime","add-stylesheet",c=>$a(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>this.Mc(c));b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.oc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===d?
(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.la=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.j.zd().style.display="";this.j.Me(c.duration)});b.B("runtime","export-to-video-progress",c=>ab(this,c));b.B("runtime","exported-to-video",c=>{window.tf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.tf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
La(d)||c.preventDefault()});window.addEventListener("selectstart",J);window.addEventListener("gesturehold",J);window.addEventListener("touchstart",J,{passive:!1});window.addEventListener("pointerdown",J,{passive:!1});this.gd=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Pa,{passive:!1});window.addEventListener("wheel",Pa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.la&&this.Sd){var c=this.qa();var d=this.ha();if(this.j.Ad()){if(this.Rd){if(this.ed===
c&&d<this.Cb){this.Lb=this.Cb-d;db(this,this.Cb,this.Lb);c=void 0;break a}0<this.Lb&&(this.Lb=0,db(this,d,this.Lb))}this.ed=c;this.Cb=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:G.nb(),cssDisplayMode:this.j.zc()});this.j.ob()&&(-1!==this.gb&&clearTimeout(this.gb),eb(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>F(this));window.addEventListener("webkitfullscreenchange",()=>F(this));window.addEventListener("mozfullscreenchange",
()=>F(this));window.addEventListener("fullscreenerror",c=>bb(this,c));window.addEventListener("webkitfullscreenerror",c=>bb(this,c));window.addEventListener("mozfullscreenerror",c=>bb(this,c));if(b.ob()){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d});document.documentElement.setAttribute("ioswebview","")}this.$a=new Set;this.fc=new WeakSet;this.za=!1}tc(){window.addEventListener("focus",
()=>{m(this,"window-focus",null,Ha)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}m(this,"window-blur",{parentHasFocus:a},Ha);this.gd=0});window.addEventListener("focusin",a=>{a=a.target;(Ma.has(a.tagName.toLowerCase())||La(a))&&m(this,"keyboard-blur",null,Ha)});window.addEventListener("keydown",a=>cb(this,"keydown",a));window.addEventListener("keyup",a=>cb(this,"keyup",a));window.addEventListener("mousedown",a=>K(this,"mousedown",a,
Ga));window.addEventListener("mousemove",a=>K(this,"mousemove",a,Ga));window.addEventListener("mouseup",a=>K(this,"mouseup",a,Ga));window.addEventListener("dblclick",a=>K(this,"dblclick",a,I));window.addEventListener("wheel",a=>{this.la||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Da,pageX:a.pageX,pageY:a.pageY+this.Da,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},I)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();
gb(a.target)&&document.activeElement&&!gb(document.activeElement)&&document.activeElement.blur();L(this,"pointerdown",a)});this.j.ba&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{L(this,"pointermove",a)}):window.addEventListener("pointermove",a=>L(this,"pointermove",a));window.addEventListener("pointerup",a=>L(this,"pointerup",a));window.addEventListener("pointercancel",a=>L(this,"pointercancel",a));const b=()=>this.Pc();window.addEventListener("pointerup",
b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.j.He()&&!this.j.Ad()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{db(this,this.ha(),navigator.virtualKeyboard.boundingRect.height)}));this.j.ob()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}qa(){return this.j.qa()}ha(){return this.j.ha()}Pc(){var b=
[...this.$a];this.$a.clear();if(!this.za)for(const a of b)(b=a.play())&&b.catch(()=>{this.fc.has(a)||this.$a.add(a)})}Ha(b){if("function"!==typeof b.play)throw Error("missing play function");this.fc.delete(b);let a;try{a=b.play()}catch(c){this.$a.add(b);return}a&&a.catch(()=>{this.fc.has(b)||this.$a.add(b)})}Ra(b){this.$a.delete(b);this.fc.add(b)}Rb(b){this.za=!!b}Mc(b){alert(b.message)}});"use strict";
async function ya(b){if(b.mf)throw Error("already initialised");b.mf=!0;var a=b.Ba.Jc(("playable-ad"===b.Ba.u?b.Ba.fb:"")+"dispatchworker.js");b.Uc=await b.Ba.wc(a,b.tb,{name:"DispatchWorker"});a=new MessageChannel;b.$c=a.port1;b.Uc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.jd=await Da(b)}function za(b){return[b.$c,b.jd]}
async function Da(b){const a=b.$d.length;var c=b.Ba.Jc(("playable-ad"===b.Ba.u?b.Ba.fb:"")+"jobworker.js");c=await b.Ba.wc(c,b.tb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Uc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.$d.push(c);return e.port1}
self.Ke=class{constructor(b){this.Ba=b;this.tb=b.aa;this.tb="preview"===b.u?this.tb+"workers/":this.tb+b.fb;this.pf=Math.min(navigator.hardwareConcurrency||2,16);this.Uc=null;this.$d=[];this.jd=this.$c=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.ca({Cf:!1,Df:"workermain.js",hb:["scripts/c3runtime.js"],rc:[],td:"",zf:"scripts/",sc:[],oe:"html5"}));"use strict";
self.ca.xa(class extends self.Ea{constructor(b){super(b,"mouse");v(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.j.zd().requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{m(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{m(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";const hb=180/Math.PI;
async function ib(b,a){a.usePlayMusicAsSoundWorkaround&&(b.kc=!0);b.pd=a.timeScaleMode;b.ee=["equalpower","HRTF","soundfield"][a.panningModel];b.Qd=["linear","inverse","exponential"][a.distanceModel];b.fe=a.refDistance;b.de=a.maxDistance;b.he=a.rolloffFactor;if(b.j.ad)b.kc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.j.Td)});else{var c={latencyHint:a.latencyHint};b.ke||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");kb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&kb(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Wa=b.g.createGain();b.Wa.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.da);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>M(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function lb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,q=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.ae=g.slice(0);mb(b,g);try{b.R=await nb(b,c,d,e,g,f);if(q){N(b.R,!0);var u=b.R,ea=q.x,H=q.y,Db=q.z,Eb=q.angle,qa=q.innerAngle,ra=q.outerAngle,sa=q.outerGain;if(u.Ab){ob(u,ea,H,Db,Eb);var C=self.jb.Ne;
u.ua[0]!==C(qa)&&(u.ua[0]=C(qa),u.F.coneInnerAngle=C(qa));u.ua[1]!==C(ra)&&(u.ua[1]=C(ra),u.F.coneOuterAngle=C(ra));u.ua[2]!==sa&&(u.ua[2]=sa,u.F.coneOuterGain=sa)}q.hasOwnProperty("uid")&&(b.R.sa=q.uid)}else"number"===typeof r&&0!==r?(O(b.R,!0),pb(b.R,r)):(N(b.R,!1),O(b.R,!1));b.R.Play(h,k,l,t)}catch(Fb){console.error("[Construct] Audio: error starting playback: ",Fb);return}finally{c=g.join(" ");d=b.Ib.get(c);if(!d)throw Error("expected pending tag");d.ud--;0===d.ud&&(d.resolve(),b.Ib.delete(c))}w(b)}
async function qb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await rb(b,c);for(const h of P(b,c))if(!h.ya){c=h.G.gain;c.cancelScheduledValues(0);var f=h.v.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Pa=d;h.Ya=g;h.je=a}Q(b)}async function sb(b,a){const c=a.tags;a=a.rate;await rb(b,c);for(const d of P(b,c))d.ma!==a&&(d.ma=a,d.Ja())}async function tb(b,a){const c=a.tags;a=a.pos;await rb(b,c);for(const d of P(b,c))d.Dc(a)}
async function ub(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await nb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function vb(b,a){if(a=await M(b,"",a.url,a.type,a.isMusic,!0))a.l(),a=b.ja.indexOf(a),-1!==a&&b.ja.splice(a,1)}
async function wb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await M(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.ue(b,...e);else if("delay"===c)d=new self.se(b,...e);else if("convolution"===c){var g=d=new self.re(b,f.ia,...e),h=a.bufferType;g.Od=a.bufferOriginalUrl;g.Pd=h}else if("flanger"===c)d=
new self.ve(b,...e);else if("phaser"===c)d=new self.xe(b,...e);else if("gain"===c)d=new self.we(b,...e);else if("stereopan"===c)d=new self.ze(b,...e);else if("tremolo"===c)d=new self.Ae(b,...e);else if("ringmod"===c)d=new self.ye(b,...e);else if("distortion"===c)d=new self.te(b,...e);else if("compressor"===c)d=new self.qe(b,...e);else if("analyser"===c)d=new self.pe(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ka.get(h);l||(l=[],g.ka.set(h,l));d.Yd=l.length;d.nd=
h;l.push(d);xb(g,h)}yb(b)}
async function zb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Fa()&&1===c||!e.Fa()&&2===c?d.push(e):e.l();b.H=d}for(const f of b.ka.values())for(const g of f)g.l();b.ka.clear();b.pc=a.timeScale;b.Wc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.da[e]=d[e];b.g.listener.setOrientation(...b.da)}b.za=a.isSilent;b.j.Rb(b.za);b.ec=a.masterVolume;b.Wa.gain.value=
b.ec;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>wb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Ab(b,f,c)));Q(b)}
async function Bb(b,a){try{const c=b.g.suspend(a.time);b.Xd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.j.qb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Cb(d)),b.Xd=!0);await c}catch(c){Cb(c)}}
function kb(b){b.Zb||(b.Zc=!1,window.addEventListener("pointerup",b.Ca,!0),window.addEventListener("touchend",b.Ca,!0),window.addEventListener("click",b.Ca,!0),window.addEventListener("keydown",b.Ca,!0),b.Zb=!0)}
async function M(b,a,c,d,e,f){for(var g of b.ja)if(g.mb()===c)return await Gb(g),g;if(f)return null;if(e&&(b.kc||b.Wd)){f=0;for(let h=0,k=b.ja.length;h<k;++h)g=b.ja[h],b.ja[f]=g,g.Fa()?g.l():++f;b.ja.length=f}f="audio/webm; codecs=opus"===d&&!b.ke;e&&f&&(b.Wd=!0);c=!e||b.kc||f?new self.De(b,a,c,d,e,f):new self.Be(b,a,c,d,e);b.ja.push(c);await Gb(c);b.ce.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.ga()}),b.ce.add(a));return c}
function Hb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Ib(b,a){return(a=b.ka.get(a.toLowerCase()))?a[0].N():b.fa()}function xb(b,a){a=a.toLowerCase();let c=b.fa();var d=b.ka.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.fa()):e.U(d[f+1].N())}}for(const f of Jb(b,a))e=f,d=c,e=e.ea||e.F||e.G,e.disconnect(),e.connect(d);b.Na&&b.fd===a&&(b.Na.disconnect(),b.Na.connect(c))}
function*Jb(b,a){if(a)for(const c of b.H)Hb(0<c.oa.length?c.oa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Kb(b,a,c){return c?b.j.lf(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Lb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.l():++c}b.H.length=c}
function*P(b,a){if(0<a.length)for(const d of b.H){a:{b=d.oa;var c=a;for(const e of c){c=!1;for(const f of b)if(Hb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function nb(b,a,c,d,e,f){for(const g of b.H)if(g.mb()===c&&(g.uc()||f))return g.oa=e,g;a=await M(b,a,c,d,f);e="html5"===a.Sc?new self.Ce(a.v,a,e):new self.Ee(a.v,a,e);b.H.push(e);return e}
function mb(b,a){a=a.join(" ");let c=b.Ib.get(a);if(!c){let d=null;c={ud:0,promise:new Promise(e=>d=e),resolve:d};b.Ib.set(a,c)}c.ud++}function rb(b,a){return(b=b.Ib.get((0===a.length?b.ae:a).join(" ")))?b.promise:Promise.resolve()}function Q(b){if(0<b.Ua.size)w(b);else for(const a of b.H)if(!a.I&&!a.O()){w(b);break}}function Mb(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function yb(b){b.bd||(b.bd=!0,Promise.resolve().then(()=>Nb(b)))}
function Nb(b){const a={};for(const [c,d]of b.ka)a[c]=d.map(e=>e.lb());m(b,"fxstate",{fxstate:a});b.bd=!1}
async function Ab(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await nb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(N(b,!0),e=b.F,f=d.pos,b.bb[0]=f[0],b.bb[1]=f[1],b.bb[2]=f[2],f=d.orient,b.ab[0]=f[0],b.ab[1]=f[1],b.ab[2]=f[2],e.setPosition(...b.bb),e.setOrientation(...b.ab),b.ua[0]=d.cia,b.ua[1]=d.coa,b.ua[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.sa=d.uid):N(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?O(b,!1):(O(b,!0),pb(b,d));c.Play(k,l,q,0);a.isPlaying||c.pb();c.Lc(a)}}}function Cb(b){console.error("[Audio] Offline rendering error: ",b)}
self.jb=class extends self.Ea{constructor(b){super(b,"audio");this.Wa=this.g=null;this.Zb=this.Zc=!1;this.Ca=()=>{if(!this.Zc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Zb&&(this.Zc=!0,window.removeEventListener("pointerup",this.Ca,!0),window.removeEventListener("touchend",this.Ca,!0),window.removeEventListener("click",this.Ca,!0),window.removeEventListener("keydown",
this.Ca,!0),this.Zb=!1)}};this.ja=[];this.H=[];this.R=null;this.ae=[];this.ce=new Set;this.be=-1;this.Ib=new Map;this.ec=1;this.za=!1;this.pd=0;this.pc=1;this.Wc=0;this.ee="HRTF";this.Qd="inverse";this.fe=600;this.de=1E4;this.he=1;this.$=[0,0,0];this.da=[0,0,-1,0,1,0];this.Wd=this.kc=!1;this.ke=this.j.Ie();this.ka=new Map;this.Ua=new Set;this.Xd=this.bd=!1;this.fd="";this.Na=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Na&&this.Na.disconnect();this.fd=c.toLowerCase();this.Na=this.g.createMediaStreamSource(a);
this.Na.connect(Ib(this,this.fd))};this.Yb=null;self.C3Audio_GetOutputStream=()=>{this.Yb||(this.Yb=this.g.createMediaStreamDestination(),this.Wa.connect(this.Yb));return this.Yb.stream};self.C3Audio_DOMInterface=this;v(this,[["create-audio-context",a=>ib(this,a)],["play",a=>lb(this,a)],["stop",a=>{a=a.tags;for(const c of P(this,a))c.Ga()}],["stop-all",()=>{for(const a of this.H)a.Ga()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of P(this,c))a?d.pb():d.Qb();Q(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of P(this,c))R(d,a)}],["fade-volume",a=>qb(this,a)],["set-master-volume",a=>{this.ec=a.vol;this.Wa.gain.value=this.ec}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of P(this,c))Pb(d,a)}],["set-silent",a=>{this.za=a.isSilent;this.j.Rb(this.za);for(const c of this.H)c.Wb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of P(this,c))d.Ec(a)}],["set-playback-rate",a=>sb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of P(this,
c))O(d,!0),pb(d,a)}],["seek",a=>tb(this,a)],["preload",a=>ub(this,a)],["unload",a=>vb(this,a)],["unload-all",()=>{for(const a of this.ja)a.l();this.ja.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.Fc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>wb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ka.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);yb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ka.get(a);if(!d||!d.length)break;for(const e of d)e.l();this.ka.delete(a);xb(this,a)}}],["tick",a=>{this.pc=a.timeScale;this.Wc=a.gameTime;this.be=a.tickCount;if(0!==this.pd)for(var c of this.H)c.Ja();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.da[0]!==
c[0]||this.da[1]!==c[1]||this.da[2]!==c[2]||this.da[3]!==c[3]||this.da[4]!==c[4]||this.da[5]!==c[5])){for(let d=0;6>d;++d)this.da[d]=c[d];this.g.listener.setOrientation(...this.da)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.sa===a&&ob(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>zb(this,a)],["offline-render-audio",a=>Bb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}fa(){return this.Wa}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.fa()}Pb(){return this.za}Ha(b){this.j.Ha(b)}Ra(b){this.j.Ra(b)}Sa(){for(var b of this.Ua)b.Sa();
b=this.g.currentTime;for(var a of this.H)a.Sa(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.lb());m(this,"state",{tickCount:this.be,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ua].map(c=>({tag:c.nd,index:c.Yd,peak:c.cb,rms:c.ge,binCount:c.m.frequencyBinCount,freqBins:c.Vd}))});0===a.length&&0===this.Ua.size&&this.$b&&(this.j.Jd(this.le),this.$b=!1)}static Ne(b){return b*hb}static yd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Le(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.ca.xa(self.jb);"use strict";function Gb(b){b.cc||(b.cc=b.Kc());return b.cc}self.vd=class{constructor(b,a,c,d,e){this.v=b;this.rf=a;this.Oa=c;this.T=d;this.nf=e;this.Sc="";this.cc=null}l(){this.cc=this.v=null}Kc(){}V(){return this.v.V()}Ac(){return this.rf}mb(){return this.Oa}yc(){return this.T}Fa(){return this.nf}ga(){}};"use strict";
self.Be=class extends self.vd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Sc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.Db=this.Eb=null;this.L.addEventListener("canplaythrough",()=>!0);this.Hb=this.V().createGain();this.Gb=null;this.L.addEventListener("canplay",()=>{this.Eb&&(this.Eb(),this.Db=this.Eb=null);!this.Gb&&this.L&&(this.Gb=this.V().createMediaElementSource(this.L),this.Gb.connect(this.Hb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Oa}' error: `,f);this.Db&&(this.Db(f),this.Db=this.Eb=null)})}l(){Lb(this.v,this);this.Hb.disconnect();this.Hb=null;this.Gb.disconnect();this.Gb=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.l()}Kc(){return new Promise((b,a)=>{this.Eb=b;this.Db=a;this.L.src=this.Oa})}W(){return this.L}ga(){return this.L.duration}};"use strict";
async function Qb(b){if(b.Ka)return b.Ka;var a=b.v.j;if("cordova"===a.u&&a.Bd(b.Oa)&&a.ac)b.Ka=await a.Nb(b.Oa);else{a=await fetch(b.Oa);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ka=await a.arrayBuffer()}}async function Rb(b){if(b.ia)return b.ia;b.ia=await Kb(b.v,b.Ka,b.qf);b.Ka=null}
self.De=class extends self.vd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Sc="webaudio";this.ia=this.Ka=null;this.qf=!!f}l(){Lb(this.v,this);this.ia=this.Ka=null;super.l()}async Kc(){try{await Qb(this),await Rb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Oa}': `,b)}}ga(){return this.ia?this.ia.duration:0}};"use strict";let Sb=0;
function N(b,a){a=!!a;b.Ab!==a&&(b.Ab=a,b.Ab?(O(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.v.ee,b.F.distanceModel=b.v.Qd,b.F.refDistance=b.v.fe,b.F.maxDistance=b.v.de,b.F.rolloffFactor=b.v.he),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.fa())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.fa())))}
function O(b,a){a=!!a;b.bc!==a&&(b.bc=a,b.bc?(N(b,!1),b.ea=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ea),b.ea.connect(b.fa())):(b.ea.disconnect(),b.ea=null,b.G.disconnect(),b.G.connect(b.fa())))}function pb(b,a){b.bc&&b.md!==a&&(b.ea.pan.value=a,b.md=a)}function R(b,a){b.Pa=a;b.G.gain.cancelScheduledValues(0);b.Ya=-1;b.G.gain.value=b.Bc()}function Pb(b,a){a=!!a;b.ya!==a&&(b.ya=a,b.Wb())}
function ob(b,a,c,d,e){if(b.Ab){var f=b.bb,g=b.ab,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function S(b){return b.cd?b.v.Wc:performance.now()/1E3}
self.wd=class{constructor(b,a,c){this.v=b;this.P=a;this.oa=c;this.Xb=Sb++;this.G=this.V().createGain();this.G.connect(this.fa());this.F=null;this.Ab=!1;this.bb=[0,0,0];this.ab=[0,0,0];this.ua=[0,0,0];this.ea=null;this.bc=!1;this.md=0;this.I=!0;this.Y=this.va=this.J=!1;this.Pa=1;this.ya=!1;this.ma=1;b=this.v.pd;this.cd=1===b&&!this.Fa()||2===b;this.Ya=this.sa=-1;this.je=!1}l(){this.P=this.v=null;this.F&&(this.F.disconnect(),this.F=null);this.ea&&(this.ea.disconnect(),this.ea=null);this.G.disconnect();
this.G=null}V(){return this.v.V()}fa(){return Ib(this.v,0<this.oa.length?this.oa[0]:"")}Ac(){return this.P.Ac()}mb(){return this.P.mb()}yc(){return this.P.yc()}Fa(){return this.P.Fa()}O(){}uc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}Qa(){}ga(){return this.P.ga()}Play(){}Ga(){}pb(){}Qb(){}Sa(b){-1!==this.Ya&&b>=this.Ya&&(this.Ya=-1,this.je&&this.Ga(),Mb(this.v,"fade-ended",this.oa,this.Xb))}Bc(){const b=this.Pa;return isFinite(b)?b:0}Pb(){return this.v.Pb()}Wb(){}Ec(){}Ja(){}Dc(){}Fc(){}Cc(){}lb(){var b=
this.Xb,a=this.oa,c=this.ga(),d=-1===this.Ya?this.Pa:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.bb,orient:this.ab,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.sa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Qa(),playbackRate:this.ma,uid:this.sa,bufferOriginalUrl:this.Ac(),bufferUrl:"",bufferType:this.yc(),isMusic:this.Fa(),isLooping:this.Y,isMuted:this.ya,resumePosition:this.Cc(),pan:f,stereoPan:this.ea?
this.md:null}}Lc(b){var a=b.playbackRate;this.ma!==a&&(this.ma=a,this.Ja());Pb(this,b.isMuted)}};"use strict";
self.Ce=class extends self.wd{constructor(b,a,c){super(b,a,c);this.P.Hb.connect(this.G);this.P.onended=()=>this.Nc()}l(){this.Ga();this.P.Hb.disconnect();super.l()}W(){return this.P.W()}Nc(){this.I=!0;this.sa=-1;Mb(this.v,"ended",this.oa,this.Xb)}O(){return this.W().ended}uc(){return this.I?!0:this.O()}Qa(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.ga()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);R(this,a);this.ya=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.mb()}' to position '${c}': `,e)}this.v.Ha(d);this.J=this.I=!1;this.Y=b;this.ma=1}Ga(){const b=this.W();b.paused||b.pause();this.v.Ra(b);this.I=!0;this.J=!1;this.sa=-1}pb(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.v.Ra(b);this.J=!0}}Qb(){!this.J||this.I||this.O()||(this.v.Ha(this.W()),this.J=!1)}Wb(){this.W().muted=this.ya||this.Pb()}Ec(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Ja(){let b=this.ma;this.cd&&(b*=this.v.pc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}Dc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}Cc(){return this.Qa()}Fc(b){b?this.IsPlaying()?(this.W().pause(),this.va=!0):this.va=!1:this.va&&(this.v.Ha(this.W()),this.va=!1)}};"use strict";
function T(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.sb=null}
self.Ee=class extends self.wd{constructor(b,a,c){super(b,a,c);this.s=null;this.hc=d=>this.Nc(d);this.Yc=!0;this.sb=null;this.S=this.jc=this.lc=0;this.hd=1}l(){this.Ga();T(this);this.hc=null;super.l()}Nc(b){this.J||this.va||b.target!==this.sb||(this.I=this.Yc=!0,this.sa=-1,T(this),Mb(this.v,"ended",this.oa,this.Xb))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Yc}uc(){return!this.s||this.I?!0:this.O()}Qa(){let b;b=this.J?this.S:this.jc+(S(this)-this.lc)*this.ma;this.Y||(b=Math.min(b,this.ga()));
return b}Play(b,a,c,d){this.ya=!1;this.hd=1;R(this,a);T(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ia;this.s.connect(this.G);this.sb=this.s;this.s.onended=this.hc;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Yc=!1;this.Y=b;this.ma=1;this.lc=S(this);this.jc=c}Ga(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.sa=-1}pb(){this.J||this.I||this.O()||(this.S=this.Qa(),this.Y&&(this.S%=this.ga()),this.J=!0,this.s.stop(0))}Qb(){!this.J||this.I||this.O()||(T(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ia,this.s.connect(this.G),this.sb=this.s,this.s.onended=this.hc,this.s.loop=this.Y,R(this,this.Pa),this.Ja(),this.s.start(0,this.S),this.lc=S(this),this.jc=this.S,this.J=!1)}Bc(){return super.Bc()*this.hd}Wb(){this.hd=this.ya||this.Pb()?0:1;R(this,this.Pa)}Ec(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ja(){let b=this.ma;this.cd&&(b*=this.v.pc);this.s&&(this.s.playbackRate.value=b)}Dc(b){this.I||this.O()||(this.J?this.S=b:(this.pb(),
this.S=b,this.Qb()))}Cc(){return this.S}Fc(b){b?this.IsPlaying()?(this.va=!0,this.S=this.Qa(),this.Y&&(this.S%=this.ga()),this.s.stop(0)):this.va=!1:this.va&&(T(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ia,this.s.connect(this.G),this.sb=this.s,this.s.onended=this.hc,this.s.loop=this.Y,R(this,this.Pa),this.Ja(),this.s.start(0,this.S),this.lc=S(this),this.jc=this.S,this.va=!1)}Lc(b){super.Lc(b);this.S=b.resumePosition}};"use strict";function U(b){return b.g.createGain()}
function V(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class W{constructor(b){this.v=b;this.g=b.V();this.Yd=-1;this.T=this.nd="";this.o=null}l(){this.g=null}N(){}U(){}lb(){return{type:this.T,tag:this.nd,params:this.o}}}
self.ue=class extends W{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.A=U(this);this.i=U(this);this.i.gain.value=g;this.h=U(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}l(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;V(this,this.i.gain,a,c,d);V(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;V(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;V(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;V(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,V(this,this.D.gain,a,c,d)}}};
self.se=class extends W{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.A=U(this);this.i=U(this);this.i.gain.value=d;this.h=U(this);this.h.gain.value=1-d;this.Fb=U(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.wb=U(this);this.wb.gain.value=c;this.A.connect(this.Fb);this.A.connect(this.h);this.Fb.connect(this.i);this.Fb.connect(this.X);this.X.connect(this.wb);this.wb.connect(this.Fb)}l(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.Fb.disconnect();
this.X.disconnect();this.wb.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){const e=self.jb.yd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;V(this,this.i.gain,a,c,d);V(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);V(this,this.wb.gain,e(a),c,d);break;case 5:this.o[0]=a,V(this,this.X.delayTime,a,c,d)}}};
self.re=class extends W{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Pd=this.Od="";this.A=U(this);this.i=U(this);this.i.gain.value=d;this.h=U(this);this.h.gain.value=1-d;this.vb=this.g.createConvolver();this.vb.normalize=c;this.vb.buffer=a;this.A.connect(this.vb);this.A.connect(this.h);this.vb.connect(this.i)}l(){this.A.disconnect();this.vb.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,V(this,this.i.gain,a,c,d),V(this,this.h.gain,1-a,c,d)}}lb(){const b=super.lb();b.bufferOriginalUrl=this.Od;b.bufferUrl="";b.bufferType=this.Pd;return b}};
self.ve=class extends W{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.A=U(this);this.h=U(this);this.h.gain.value=1-f/2;this.i=U(this);this.i.gain.value=f/2;this.yb=U(this);this.yb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=U(this);this.K.gain.value=c;this.A.connect(this.X);this.A.connect(this.h);this.X.connect(this.i);this.X.connect(this.yb);this.yb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}l(){this.C.stop(0);this.A.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.yb.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;V(this,this.i.gain,a/2,c,d);V(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;V(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;V(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,V(this,this.yb.gain,a/100,c,d)}}};
self.xe=class extends W{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.A=U(this);this.h=U(this);this.h.gain.value=1-g/2;this.i=U(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=U(this);this.K.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}l(){this.C.stop(0);this.A.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;V(this,this.i.gain,a/2,c,d);V(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;V(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;V(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;V(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;V(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,V(this,this.C.frequency,a,c,d)}}};self.we=class extends W{constructor(b,a){super(b);this.T="gain";this.o=[a];this.m=U(this);this.m.gain.value=a}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){const e=self.jb.yd;switch(b){case 4:this.o[0]=e(a),V(this,this.m.gain,e(a),c,d)}}};
self.ze=class extends W{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.m=this.g.createStereoPanner();this.m.pan.value=a}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,V(this,this.m.pan,a,c,d)}}};
self.Ae=class extends W{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.m=U(this);this.m.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=U(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.m.gain);this.C.start(0)}l(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;V(this,this.m.gain,1-a/2,c,d);V(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,V(this,this.C.frequency,a,c,d)}}};
self.ye=class extends W{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.A=U(this);this.i=U(this);this.i.gain.value=c;this.h=U(this);this.h.gain.value=1-c;this.Kb=U(this);this.Kb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Kb.gain);this.C.start(0);this.A.connect(this.Kb);this.A.connect(this.h);this.Kb.connect(this.i)}l(){this.C.stop(0);this.C.disconnect();this.Kb.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;V(this,this.i.gain,a,c,d);V(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,V(this,this.C.frequency,a,c,d)}}};
self.te=class extends W{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.A=U(this);this.nc=U(this);this.mc=U(this);b=d;.01>b&&(b=.01);this.nc.gain.value=b;this.mc.gain.value=Math.pow(1/b,.6)*e;this.i=U(this);this.i.gain.value=f;this.h=U(this);this.h.gain.value=1-f;this.qc=this.g.createWaveShaper();this.Tc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Tc[32768+e]=f,this.Tc[32768-
e-1]=-f;this.qc.curve=this.Tc;this.A.connect(this.nc);this.A.connect(this.h);this.nc.connect(this.qc);this.qc.connect(this.mc);this.mc.connect(this.i)}l(){this.A.disconnect();this.nc.disconnect();this.qc.disconnect();this.mc.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,V(this,this.i.gain,a,c,d),V(this,this.h.gain,
1-a,c,d)}}};self.qe=class extends W{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.m=this.g.createDynamicsCompressor();this.m.threshold.value=a;this.m.knee.value=c;this.m.ratio.value=d;this.m.attack.value=e;this.m.release.value=f}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};
self.pe=class extends W{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.m=this.g.createAnalyser();this.m.fftSize=a;this.m.smoothingTimeConstant=c;this.Vd=new Float32Array(this.m.frequencyBinCount);this.ie=new Uint8Array(a);this.ge=this.cb=0;b=this.v;b.Ua.add(this);Q(b)}l(){this.v.Ua.delete(this);this.m.disconnect();super.l()}Sa(){this.m.getFloatFrequencyData(this.Vd);this.m.getByteTimeDomainData(this.ie);const b=this.m.fftSize;let a=this.cb=0;for(var c=0;c<b;++c){let d=(this.ie[c]-
128)/128;0>d&&(d=-d);this.cb<d&&(this.cb=d);a+=d*d}c=self.jb.Le;this.cb=c(this.cb);this.ge=c(Math.sqrt(a/b))}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};"use strict";function X(b){b.stopPropagation()}
self.ca.xa(class extends self.Ob{constructor(b){super(b,"progress-bar")}vc(b,a){const c=document.createElement("progress");c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",X);c.addEventListener("pointermove",X);c.addEventListener("pointerrawupdate",X);c.addEventListener("pointerup",X);c.addEventListener("mousedown",X);c.addEventListener("mouseup",X);c.addEventListener("click",()=>fa(this,b));a.id&&(c.id=a.id);a.className&&(c.className=
a.className);this.rb(c,a);return c}rb(b,a){b.title=a.title;const c=a.value;a=a.max;0<a&&0<=c?(b.max=a,b.value=c):(b.removeAttribute("value"),b.removeAttribute("max"))}});"use strict";async function Tb(b,a){a=a.type;let c=!0;0===a?c=await Ub():1===a&&(c=await Vb());m(b,"permission-result",{type:a,result:c})}
async function Ub(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Vb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.ca.xa(class extends self.Ea{constructor(b){super(b,"touch");p(this,"request-permission",a=>Tb(this,a))}});"use strict";
async function Wb(){try{return{isOk:!0,isPersistent:await navigator.storage.persist()}}catch(b){return console.error("[Construct] Error requesting persistent storage: ",b),{isOk:!1}}}self.ca.xa(class extends self.Ea{constructor(b){super(b,"localstorage");v(this,[["init",()=>this.Sb()],["request-persistent",()=>Wb()]])}async Sb(){let b=!1;try{b=await navigator.storage.persisted()}catch(a){b=!1,console.warn("[Construct] Error checking storage persisted state: ",a)}return{isPersistent:b}}});"use strict";
function Y(b){b.stopPropagation()}
self.ca.xa(class extends self.Ob{constructor(b){super(b,"sliderbar")}vc(b,a){const c=document.createElement("input");c.type="range";c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",Y);c.addEventListener("pointermove",Y);c.addEventListener("pointerrawupdate",Y);c.addEventListener("pointerup",Y);c.addEventListener("mousedown",Y);c.addEventListener("mouseup",Y);c.addEventListener("keydown",Y);c.addEventListener("keyup",Y);c.addEventListener("contextmenu",
d=>d.preventDefault());c.addEventListener("click",()=>fa(this,b));c.addEventListener("change",()=>x(this,"change",b,{value:parseFloat(c.value)}));c.addEventListener("input",()=>x(this,"input",b,{value:parseFloat(c.value)}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.rb(c,a);return c}rb(b,a){b.max=a.max;b.min=a.min;b.step=a.step;b.value=a.value;b.disabled=!a.isEnabled;b.title=a.title}});"use strict";let Z=null,Xb=null;
window.addEventListener("beforeinstallprompt",b=>{b.preventDefault();Z=b;Xb&&m(Xb,"install-available");return!1});function Yb(){}function Zb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>m(b,"sw-message",a.data))}
function $b(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}async function ac(){if(!Z)return{result:"unavailable"};try{return Z.prompt(),{result:(await Z.userChoice).outcome}}catch(b){return console.error("[Construct] Requesting install failed: ",b),{result:"failed"}}}
self.ca.xa(class extends self.Ea{constructor(b){super(b,"browser");this.u="";v(this,[["get-initial-state",a=>{this.u=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
Zb(this)],["alert",a=>this.Mc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Oc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>$b(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||this.j.pa()?window.open(c,"_blank"):this.If||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.j.pa()||"macos-wkwebview"===this.u)self.ca.Vb(!0),this.j.Ia({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===
a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(Yb)}}],["exit-fullscreen",()=>{if(this.j.pa()||"macos-wkwebview"===this.u)self.ca.Vb(!1),this.j.Ia({type:"set-fullscreen",
fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Yb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=
document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}],["set-window-size",a=>{window.resizeTo(a.windowWidth,
a.windowHeight)}],["set-window-position",a=>{window.moveTo(a.windowX,a.windowY)}],["request-install",()=>ac()],["set-warn-on-close",a=>{a.enabled?window.addEventListener("beforeunload",this.Nd):window.removeEventListener("beforeunload",this.Nd)}]]);window.addEventListener("online",()=>{m(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{m(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{m(this,"hashchange",{location:location.toString()})});this.Nd=
a=>a.preventDefault();document.addEventListener("backbutton",()=>{m(this,"backbutton")})}tc(){Z?m(this,"install-available"):Xb=this;window.addEventListener("appinstalled",()=>{m(this,"app-installed")})}Mc(b){alert(b.message)}Oc(b){b=b.isFocus;if("nwjs"===this.u){const a="nwjs"===this.u?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});
