function l(b,a,c,d){b.l.vb(b.zb,a,c,d)}function p(b,a,c){return b.l.Kd(b.zb,a,c)}function q(b,a,c,d){b.l.fa?l(b,a,c,d):b.l.Df()._OnMessageFromDOM({type:"event",component:b.zb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function r(b,a,c){b.l.D(b.zb,a,c)}function x(b,a){for(const [c,d]of a)r(b,c,d)}function y(b){b.ec||(b.l.Nc(b.te),b.ec=!0)}window.Ca=class{constructor(b,a){this.l=b;this.zb=a;this.ec=!1;this.te=()=>this.La()}yc(){}La(){}};
window.vg=class{constructor(){this.xd=-1}m(){-1!==this.xd&&(self.clearTimeout(this.xd),this.xd=-1)}};"use strict";class aa{constructor(b){this.Cb=b;this.dd=!1;this.ld=!0;this.Eb=this.va=this.yd=-1}}
function ca(b,a){const c=a.elementId,d=b.Ac(c,a),e=new aa(d);b.Sa.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.ld=!!a.isVisible;d.addEventListener("focus",()=>{z(b,"elem-focused",c)});d.addEventListener("blur",()=>{z(b,"elem-blurred",c)});const f=a.htmlIndex;e.yd=f;e.Eb=a.htmlZIndex;b.$a&&(a=b.l.Cc(f),e.va=a,b.l.pb(a).appendChild(d))}function da(b,a){r(b,"get-element",c=>{const d=A(b,c.elementId);return a(d,c)})}
function A(b,a){b=b.Sa.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Cb}function z(b,a,c,d){d||(d={});d.elementId=c;l(b,a,d)}function ea(b,a){var c;c||(c={});c.elementId=a;q(b,"click",c)}
window.Tb=class extends self.Ca{constructor(b,a){super(b,a);this.Sa=new Map;this.$a=!0;x(this,[["create",c=>ca(this,c)],["destroy",c=>{c=c.elementId;const d=A(this,c);this.$a&&d.parentElement.removeChild(d);this.Sa.delete(c)}],["set-visible",c=>{if(this.$a){var d=this.Sa.get(c.elementId),e=d.Cb;d.dd?e.style.display=c.isVisible?"":"none":d.ld=!!c.isVisible}}],["update-position",c=>{if(this.$a){var d=this.Sa.get(c.elementId),e=d.Cb,f=this.l;e.style.left=c.left+"px";e.style.top=c.top+"px";e.style.width=
c.width+"px";e.style.height=c.height+"px";var h=c.fontSize;null!==h&&(e.style.fontSize=h+"em");h=c.htmlIndex;d.yd=h;h=f.Cc(h);h!==d.va&&(e.remove(),f.pb(h).appendChild(e),d.va=h,f.Yc());c=c.htmlZIndex;c!==d.Eb&&(d.Eb=c,f.Yc());d.dd||(d.dd=!0,d.ld&&(e.style.display=""))}}],["update-state",c=>{const d=A(this,c.elementId);this.wb(d,c)}],["focus",c=>this.Vc(c)],["set-css-style",c=>{const d=A(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",
c=>{A(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{A(this,c.elementId).removeAttribute(c.name)}]]);da(this,c=>c)}Ac(){throw Error("required override");}wb(){throw Error("required override");}Vc(b){var a=A(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const fa=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),ia=/android/i.test(navigator.userAgent),ja=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);
let ka=0;function la(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.eg?new Promise(c=>{const d="c3_resolve_"+ka;++ka;self[d]=c;a.textContent=b.ig+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function ma(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let B=new Audio;
const na={"audio/webm; codecs=opus":!!B.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!B.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!B.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!B.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!B.canPlayType("audio/mp4"),"audio/mpeg":!!B.canPlayType("audio/mpeg")};B=null;async function oa(b){b=await pa(b);return(new TextDecoder("utf-8")).decode(b)}
function pa(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const qa=[];let C=0;window.RealFile=window.File;const D=[],ra=new Map,va=new Map;let wa=0;const xa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");xa.push(b)};const ya=new Set(["cordova","playable-ad","instant-games"]);let za=!1;
window.ba=class b{constructor(a){this.fa=a.mg;this.Fa=null;this.ea="";this.kb=a.hg;this.Rb={};this.eb=this.Aa=null;this.bb=[];this.qa=null;this.ge=!0;this.P=[];this.rd=[];this.sd=!1;this.ue=()=>this.Bf();this.hd=!1;this.ae=0;this.Gb=null;this.jb=-1;this.ag=()=>this.Mf();this.Ob=new Set;this.zd=null;this.ve=[];this.A=a.we;this.fc="file"===location.protocol.substr(0,4);if("playable-ad"===this.A||"instant-games"===this.A)this.fa=!1;ja&&(this.fa=!1);if("cordova"===this.A&&this.fa&&ia){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.fa=!1)}this.ta()?self.chrome.webview.addEventListener("message",c=>this.Qd(c.data)):"macos-wkwebview"===this.A&&(self.C3WrapperOnMessage=c=>this.Qd(c));this.jc=this.xa=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.D("canvas","update-size",c=>this.Qf(c));this.D("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.D("canvas","cleanup-html-layers",()=>this.Hf());this.D("runtime","cordova-fetch-local-file",c=>this.If(c));this.D("runtime","create-job-worker",()=>this.Jf());this.D("runtime","send-wrapper-extension-message",c=>this.Pf(c));"cordova"===this.A?document.addEventListener("deviceready",()=>this.Xb(a)):this.Xb(a)}m(){this.Oc();this.Fa&&(this.Fa=this.Fa.onmessage=null);this.Aa&&(this.Aa.terminate(),this.Aa=null);this.eb&&(this.eb.m(),this.eb=null);for(const {canvas:a,
nb:c}of this.P)a.remove(),c.remove();this.P.length=0}Gd(){return this.P[0].canvas}Cc(a){return Math.min(a,this.P.length-1)}pb(a){if(0>a||a>=this.P.length)throw new RangeError("invalid canvas layer");return this.P[a].nb}_GetHTMLWrapElement(a){return this.pb(a)}Te(){return fa&&"cordova"===this.A}tb(){const a=navigator.userAgent;return fa&&ya.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Re(){return ia}Hd(){return ia&&ya.has(this.A)}Jd(){return"windows-webview2"===this.A||!!("preview"===
this.A&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}ta(){return this.Jd()||"xbox-uwp-webview2"===this.A}async Xb(a){this.fa&&!await ma()&&(this.fa=!1);"macos-wkwebview"===this.A?this.Oa({type:"ready"}):this.ta()&&(this.Sf(),this.ve=(await this.Gf()).registeredComponentIds);if("playable-ad"===this.A){this.xa=self.c3_base64files;this.jc={};await this.yf();for(let d=0,e=a.mb.length;d<e;++d){var c=a.mb[d];this.jc.hasOwnProperty(c)?a.mb[d]={eg:!0,ig:this.jc[c]}:this.xa.hasOwnProperty(c)&&
(a.mb[d]=URL.createObjectURL(this.xa[c]))}a.xc=[]}if("nwjs"===this.A&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Nc(()=>{d++;document.documentElement.style.opacity=0===d%2?"1":"0.999"})}a.gg?this.ea=a.gg:(c=location.origin,this.ea=("null"===c?"file:///":c)+location.pathname,c=this.ea.lastIndexOf("/"),-1!==c&&(this.ea=this.ea.substr(0,c+1)));a.og&&(this.Rb=a.og);c=new MessageChannel;this.Fa=c.port1;this.Fa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&
window.c3_addPortMessageHandler(d=>this.Lf(d));this.Gb=new self.Ue(this);await Aa(this.Gb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.fa?await this.Ff(a,c.port2):await this.Ef(a,c.port2)}Qc(a){a=this.Rb.hasOwnProperty(a)?this.Rb[a]:a.endsWith("/workermain.js")&&this.Rb.hasOwnProperty("workermain.js")?
this.Rb["workermain.js"]:"playable-ad"===this.A&&this.xa.hasOwnProperty(a)?this.xa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async Bc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.fc)return a=await this.Sb(d.dg?a:this.kb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),
d)}return new Worker(a,d)}ua(){return Math.max(window.innerWidth,1)}ka(){return Math.max(window.innerHeight,1)}Ec(){return this.ta()||(new Set(["cordova","nwjs","macos-wkwebview"])).has(this.A)?"standalone":window.matchMedia("(display-mode: fullscreen)").matches?"fullscreen":window.matchMedia("(display-mode: standalone)").matches?"standalone":window.matchMedia("(display-mode: minimal-ui)").matches?"minimal-ui":navigator.standalone?"standalone":"browser"}Od(a){var c=this.ea,d=location.href,e=this.ua(),
f=this.ka(),h=this.Ec(),k=window.devicePixelRatio,m=b.sb(),n=a.Cg,t=window.cr_previewImageBlobs||this.xa,v=window.cr_previewProjectFileBlobs,u=window.cr_previewProjectFiles,w=window.cr_swClientId||"";a=a.we;var ha=(new URLSearchParams(self.location.search)).has("debug"),J=this.Gb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,cssDisplayMode:h,devicePixelRatio:k,isFullscreen:m,projectData:n,previewImageBlobs:t,previewProjectFileBlobs:v,previewProjectFileSWUrls:u,swClientId:w,
exportType:a,isDebug:ha,ife:!!self.Ag,jobScheduler:{inputPort:J.gd,outputPort:J.qd,maxNumWorkers:J.Xf},supportedAudioFormats:na,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.kb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.kb+"opus.wasm.wasm",isFileProtocol:this.fc,isiOSCordova:this.Te(),isiOSWebView:this.tb(),isWindowsWebView2:this.Jd(),isAnyWebView2Wrapper:this.ta(),wrapperComponentIds:this.ve,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ff(a,c){const d=
this.Qc(a.ng);"preview"===this.A?(this.Aa=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((n,t)=>{const v=u=>{this.Aa.removeEventListener("message",v);u.data&&"ok"===u.data.type?n():t()};this.Aa.addEventListener("message",v);this.Aa.postMessage({type:"construct-worker-init","import":(new URL(d,this.ea)).toString()})})):this.Aa=await this.Bc(d,this.ea,{type:"module",name:"Runtime",dg:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();
document.body.appendChild(e);const h=document.createElement("div");h.className="c3htmlwrap";document.body.appendChild(h);this.P.push({canvas:e,nb:h});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let k=a.xc||[],m=a.mb;k=await Promise.all(k.map(n=>this.Ya(n)));m=await Promise.all(m.map(n=>this.Ya(n)));if("cordova"===this.A)for(let n=0,t=a.wc.length;n<t;++n){const v=a.wc[n],u=v[0];if(u===a.Ad||"scriptsInEvents.js"===u||u.endsWith("/scriptsInEvents.js"))v[1]=await this.Ya(u)}this.Aa.postMessage(Object.assign(this.Od(a),
{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:k,engineScripts:m,projectScripts:a.wc,mainProjectScript:a.Ad,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...Ba(this.Gb)]);this.bb=D.map(n=>new n(this));this.Nd();Da(e);Ea(h);Fa(this.qa);self.c3_callFunction=(n,t)=>p(this.qa,"js-invoke-function",{name:n,params:t});"preview"===this.A&&(self.goToLastErrorScript=()=>this.vb("runtime","go-to-last-error-script"))}async Ef(a,c){const d=document.createElement("canvas");
d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.P.push({canvas:d,nb:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.bb=D.map(k=>new k(this));this.Nd();Da(d);Ea(e);e=a.mb.map(k=>"string"===typeof k?(new URL(k,this.ea)).toString():k);if(Array.isArray(a.xc)){var f=[...a.xc].map(k=>k instanceof Blob?URL.createObjectURL(k):k);e.unshift(...f)}e=await Promise.all(e.map(k=>
this.Ya(k)));await Promise.all(e.map(k=>la(k)));e=self.C3_ProjectScriptsStatus;f=a.Ad;const h=a.wc;for(let [k,m]of h)if(m||(m=k),k===f)try{m=await this.Ya(m),await la(m),"preview"!==this.A||e[k]||this.Sd(k,"main script did not run to completion")}catch(n){this.Sd(k,n)}else if("scriptsInEvents.js"===k||k.endsWith("/scriptsInEvents.js"))m=await this.Ya(m),await la(m);"preview"===this.A&&"object"!==typeof self.ug.wg?(this.Zb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Od(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:xa}),Fa(this.qa),this.Pd(),this.eb=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.eb,a))}Sd(a,c){this.Zb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Pd(){this.Zb()}Zb(){const a=
window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Jf(){const a=await Ga(this.Gb);return{outputPort:a,transferables:[a]}}Qf(a){if(!this.hd){var c=a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:h,nb:k}of this.P)h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,k.style.width=c,k.style.height=d,k.style.marginLeft=e,k.style.marginTop=f,this.ge&&(h.style.display="",k.style.display=
"");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.ge=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const h=a.marginLeft+"px",k=a.marginTop+"px";a=[];const m=[];if(c<this.P.length)for(;this.P.length>c;){const {canvas:n,nb:t}=this.P.pop();t.remove();this.fa&&!d?this.rd.push(n):n.remove()}else if(c>this.P.length)for(let n=0,t=c-this.P.length;n<t;++n)c=document.createElement("canvas"),c.classList.add("c3overlay"),
this.fa?(d=c.transferControlToOffscreen(),a.push(d),m.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=f,c.style.marginLeft=h,c.style.marginTop=k,d.style.width=e,d.style.height=f,d.style.marginLeft=h,d.style.marginTop=k,Da(c),Ea(d),this.P.push({canvas:c,nb:d});for(const n of this.bb)if(n instanceof window.Tb&&n.$a)for(const t of n.Sa.values())e=n.l.Cc(t.yd),f=t.va,-1!==
e&&-1!==f&&e!==f&&(f=t.Cb,f.remove(),n.l.pb(e).appendChild(f),t.va=e);this.Yc();return{addedCanvases:a,transferables:m}}Hf(){for(const a of this.rd)a.remove();this.rd.length=0}Yc(){this.sd||(this.sd=!0,this.Nc(this.ue))}Bf(){this.Rd(this.ue);this.sd=!1;let a=[];for(var c of this.bb)if(c instanceof window.Tb){var d=c.$a?[...c.Sa.values()]:null;d&&a.push(...d)}a.sort((h,k)=>{const m=h.va,n=k.va;return m!==n?m-n:h.Eb-k.Eb});let e=d=c=0,f=a.length;for(;e<f;++e){const h=a[e];h.va!==c&&(this.Md(c,a.slice(d,
e)),c=h.va,d=e)}d<e&&this.Md(c,a.slice(d,e))}Md(a,c){if(!(1>=c.length||a>=this.P.length)){c=c.map(m=>m.Cb);var d=new Set(c);a=this.pb(a);for(var e=Array.from(a.children).filter(m=>d.has(m)),f=0,h=Math.min(c.length,e.length);f<h&&c[f]===e[f];++f);for(var k=f;k<h;++k)e[k].remove();for(k=f;k<h;++k)a.appendChild(c[k])}}Df(){if(this.fa)throw Error("not available in worker mode");return this.eb}vb(a,c,d,e,f){this.Fa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},
f)}Kd(a,c,d,e,f){const h=wa++,k=new Promise((m,n)=>{va.set(h,{resolve:m,reject:n})});this.Fa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:h},f);return k}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Kf(a);if("result"===c)this.Nf(a);else if("runtime-ready"===c)this.Of();else if("alert-error"===c)this.Zb(),alert(a.message);else if("creating-runtime"===c)this.Pd();else throw Error(`unknown message '${c}'`);}Kf(a){const c=a.component,d=a.handler,
e=a.data,f=a.responseId;if(a=ra.get(c))if(a=a.get(d)){var h=null;try{h=a(e)}catch(k){console.error(`Exception in '${c}' handler '${d}':`,k);null!==f&&this.Yb(f,!1,""+k);return}if(null===f)return h;h&&h.then?h.then(k=>this.Yb(f,!0,k)).catch(k=>{console.error(`Rejection from '${c}' handler '${d}':`,k);this.Yb(f,!1,""+k)}):this.Yb(f,!0,h)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Yb(a,c,d){let e;d&&d.transferables&&
(e=d.transferables);this.Fa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Nf(a){const c=a.responseId,d=a.isOk;a=a.result;const e=va.get(c);d?e.resolve(a):e.reject(a);va.delete(c)}D(a,c,d){let e=ra.get(a);e||(e=new Map,ra.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static sa(a){if(D.includes(a))throw Error("DOM handler already added");D.push(a)}Nd(){for(const a of this.bb)if("runtime"===a.zb){this.qa=a;return}throw Error("cannot find runtime DOM handler");
}Lf(a){this.vb("debugger","message",a)}Of(){for(const a of this.bb)a.yc()}static sb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||za)}static $b(a){za=!!a}Nc(a){this.Ob.add(a);this.Xc()}Rd(a){this.Ob.delete(a);0===this.Ob.size&&this.Oc()}Xc(){-1===this.jb&&0<this.Ob.size&&(this.jb=requestAnimationFrame(this.ag))}Oc(){-1!==this.jb&&(cancelAnimationFrame(this.jb),this.jb=-1)}Mf(){this.jb=-1;for(const a of this.Ob)a();this.Xc()}Ma(a){this.qa.Ma(a)}Xa(a){this.qa.Xa(a)}Wc(){this.qa.Wc()}Wb(a){this.qa.Wb(a)}Se(){return!!na["audio/webm; codecs=opus"]}async Tf(a){a=
await this.Kd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Ye(a){this.hd=!0;this.ae=a}Qe(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}Id(a){return!this.Qe(a)}async Ya(a){return"cordova"===this.A&&(a.startsWith("file:")||this.fc&&this.Id(a))?(a.startsWith(this.ea)&&(a=a.substr(this.ea.length)),a=await this.Sb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async If(a){const c=a.filename;switch(a.as){case "text":return await this.Oe(c);
case "buffer":return await this.Sb(c);default:throw Error("unsupported type");}}Ed(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async Oe(a){a=await this.Ed(a);return await oa(a)}Pc(){if(qa.length&&!(8<=C)){C++;var a=qa.shift();this.zf(a.filename,a.jg,a.cg)}}Sb(a){return new Promise((c,d)=>{qa.push({filename:a,jg:e=>{C--;this.Pc();c(e)},cg:e=>{C--;this.Pc();d(e)}});this.Pc()})}async zf(a,c,d){try{const e=
await this.Ed(a),f=await pa(e);c(f)}catch(e){d(e)}}Qd(a){if("entered-fullscreen"===a)b.$b(!0),F(this.qa);else if("exited-fullscreen"===a)b.$b(!1),F(this.qa);else if("object"===typeof a){const c=a.type;"directory-handles"!==c&&("wrapper-init-response"===c?(this.zd(a),this.zd=null):"extension-message"===c?this.vb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a))}else console.warn("Unknown wrapper message: ",a)}Pf(a){this.Oa({type:"extension-message",componentId:a.componentId,
messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}Oa(a){this.ta()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.A&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Sf(){window.moveTo=(a,c)=>{this.Oa({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.Oa({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Gf(){return this.ta()?new Promise(a=>{this.zd=a;this.Oa({type:"wrapper-init"})}):
Promise.resolve()}async yf(){const a=[];for(const [c,d]of Object.entries(this.xa))a.push(this.xf(c,d));await Promise.all(a)}async xf(a,c){if("object"===typeof c)this.xa[a]=new Blob([c.str],{type:c.type}),this.jc[a]=c.str;else{let d=await this.Cf(c);d||(d=this.Af(c));this.xa[a]=d}}async Cf(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}Af(a){a=this.Rf(a);return this.wf(a.data,a.fg)}Rf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{fg:a,data:d}}wf(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),h=new Uint32Array(f.buffer,0,e),k,m;for(m=k=0;k<e;++k)h[k]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=
3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const G=self.ba,Ha=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),H={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ia={dispatchUserScriptEvent:!0},Ja={dispatchRuntimeEvent:!0};function Ka(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}
function La(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function Ma(b){b=URL.createObjectURL(b);try{return await La(b)}finally{URL.revokeObjectURL(b)}}function Na(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Oa=new Set(["input","textarea","datalist","select"]),Pa=new Set(["canvas","body","html"]);
function I(b){b.target.tagName&&Pa.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Qa(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Ra(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await Ma(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ma(b);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Sa=!1;document.addEventListener("pause",()=>Sa=!0);document.addEventListener("resume",()=>Sa=!1);function Da(b){b.addEventListener("selectstart",I);b.addEventListener("gesturehold",I);b.addEventListener("pointerdown",I)}function Ea(b){b.addEventListener("selectstart",Qa);b.addEventListener("gesturehold",Qa);b.addEventListener("touchstart",Qa)}function Fa(b){b.$d=!0;b.md=b.l.ua();b.Hb=b.l.ka()}
function F(b){if(!b.oa){var a=G.sb();a&&"any"!==b.vd&&Ta(b);l(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.ua(),innerHeight:b.ka()})}}async function Ua(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Va(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Wa(b){return await self.C3_GetSvgImageSize(b.blob)}function Xa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ya(b){self.setTimeout(()=>{b.Zd=!0},1E3);"cordova"===b.l.A?(document.addEventListener("pause",()=>Za(b,!0)),document.addEventListener("resume",()=>Za(b,!1))):document.addEventListener("visibilitychange",()=>Za(b,"hidden"===document.visibilityState));b.nc=!("hidden"!==document.visibilityState&&!Sa);return{isSuspended:b.nc}}
function $a(b){b.Ud||(b.Ud=!0,window.addEventListener("deviceorientation",a=>{b.oa||l(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},H)}),window.addEventListener("deviceorientationabsolute",a=>{b.oa||l(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},H)}))}
function ab(b){b.Td||(b.Td=!0,window.addEventListener("devicemotion",a=>{if(!b.oa){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});l(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},H)}}))}async function bb(b){await Ka(b.url)}
function cb(b,a){b.be=a.message;-1===b.bd&&(b.bd=setTimeout(()=>{b.bd=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.be)},250))}function db(b,a){console.warn("[Construct] Fullscreen request failed: ",a);l(b,"fullscreenerror",{isFullscreen:G.sb(),innerWidth:b.ua(),innerHeight:b.ka()})}
function Za(b,a){b.nc!==a&&((b.nc=a)?b.l.Oc():b.l.Xc(),l(b,"visibilitychange",{hidden:a}),!a&&b.l.tb()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function eb(b,a,c){"Backspace"===c.key&&I(c);"nwjs"===b.l.A&&"u"===c.key&&(c.ctrlKey||c.metaKey)&&c.preventDefault();if(!b.oa){var d=Ha.get(c.code)||c.code;q(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},H)}}
function K(b,a,c,d){b.oa||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||q(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Ia,pageX:c.pageX,pageY:c.pageY+b.Ia,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function L(b,a,c){if(!b.oa){var d=0;"mouse"===c.pointerType&&(d=b.od);q(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Ia,pageX:c.pageX,pageY:c.pageY+b.Ia,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},H);"mouse"===c.pointerType&&
(b.od=c.buttons)}}function fb(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Ia=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Ia=a))}}
function gb(b,a,c,d){const e=b.ua(),f=b.ka();b.lb=-1;e!=a||f!=c?l(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:G.sb(),cssDisplayMode:b.l.Ec()}):10>d&&hb(b,e,f,d+1)}function hb(b,a,c,d){-1!==b.lb&&clearTimeout(b.lb);b.lb=setTimeout(()=>gb(b,a,c,d),48)}
function Ta(b){b=b.vd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function ib(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
G.sa(class extends self.Ca{constructor(b){super(b,"runtime");this.$d=!1;this.lb=-1;this.vd="any";this.nc=this.Td=this.Ud=!1;this.tc=document.createElement("div");this.tc.className="c3-screen-reader-text";this.tc.setAttribute("aria-live","polite");document.body.appendChild(this.tc);this.Ra=null;this.oa=!1;this.be="";this.bd=-1;this.Zd=!1;this.md=b.ua();this.Hb=b.ka();this.Ia=this.Qb=0;b.D("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.D("runtime","load-webfonts",c=>Ua(c));b.D("runtime","raster-svg-image",c=>Va(c));b.D("runtime","get-svg-image-size",c=>Wa(c));b.D("runtime","set-target-orientation",c=>{this.vd=c.targetOrientation});b.D("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.D("runtime","post-to-debugger",c=>Xa(c));b.D("runtime","go-to-script",c=>Xa(c));b.D("runtime","before-start-ticking",()=>Ya(this));b.D("runtime",
"debug-highlight",c=>{if(c.show){this.Ra||(this.Ra=document.createElement("div"),this.Ra.id="inspectOutline",document.body.appendChild(this.Ra));var d=this.Ra;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Ra&&(this.Ra.style.display="none")});b.D("runtime","enable-device-orientation",()=>$a(this));b.D("runtime","enable-device-motion",()=>ab(this));b.D("runtime","add-stylesheet",c=>bb(c));
b.D("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.D("runtime","alert",c=>this.Tc(c));b.D("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.tc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===d?
(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.D("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.D("runtime","set-exporting-to-video",c=>{this.oa=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.l.Gd().style.display="";this.l.Ye(c.duration)});b.D("runtime","export-to-video-progress",c=>cb(this,c));b.D("runtime","exported-to-video",c=>{window.bg({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.D("runtime","exported-to-image-sequence",c=>{window.bg({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Na(d)||c.preventDefault()});window.addEventListener("selectstart",I);window.addEventListener("gesturehold",I);window.addEventListener("touchstart",I,{passive:!1});window.addEventListener("pointerdown",I,{passive:!1});this.od=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Ra,{passive:!1});window.addEventListener("wheel",Ra,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.oa&&this.$d){var c=this.ua();var d=this.ka();if(this.l.Hd()){if(this.Zd){if(this.md===
c&&d<this.Hb){this.Qb=this.Hb-d;fb(this,this.Hb,this.Qb);c=void 0;break a}0<this.Qb&&(this.Qb=0,fb(this,d,this.Qb))}this.md=c;this.Hb=d}l(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:G.sb(),cssDisplayMode:this.l.Ec()});this.l.tb()&&(-1!==this.lb&&clearTimeout(this.lb),gb(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>F(this));window.addEventListener("webkitfullscreenchange",()=>F(this));window.addEventListener("mozfullscreenchange",
()=>F(this));window.addEventListener("fullscreenerror",c=>db(this,c));window.addEventListener("webkitfullscreenerror",c=>db(this,c));window.addEventListener("mozfullscreenerror",c=>db(this,c));if(b.tb()){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d});document.documentElement.setAttribute("ioswebview","")}this.fb=new Set;this.lc=new WeakSet;this.Ea=!1}yc(){window.addEventListener("focus",
()=>{l(this,"window-focus",null,Ja)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}l(this,"window-blur",{parentHasFocus:a},Ja);this.od=0});window.addEventListener("focusin",a=>{a=a.target;(Oa.has(a.tagName.toLowerCase())||Na(a))&&l(this,"keyboard-blur",null,Ja)});window.addEventListener("keydown",a=>eb(this,"keydown",a));window.addEventListener("keyup",a=>eb(this,"keyup",a));window.addEventListener("mousedown",a=>K(this,"mousedown",a,
Ia));window.addEventListener("mousemove",a=>K(this,"mousemove",a,Ia));window.addEventListener("mouseup",a=>K(this,"mouseup",a,Ia));window.addEventListener("dblclick",a=>K(this,"dblclick",a,H));window.addEventListener("wheel",a=>{this.oa||l(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Ia,pageX:a.pageX,pageY:a.pageY+this.Ia,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},H)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();
ib(a.target)&&document.activeElement&&!ib(document.activeElement)&&document.activeElement.blur();L(this,"pointerdown",a)});this.l.fa&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{L(this,"pointermove",a)}):window.addEventListener("pointermove",a=>L(this,"pointermove",a));window.addEventListener("pointerup",a=>L(this,"pointerup",a));window.addEventListener("pointercancel",a=>L(this,"pointercancel",a));const b=()=>this.Wc();window.addEventListener("pointerup",
b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.l.Re()&&!this.l.Hd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{fb(this,this.ka(),navigator.virtualKeyboard.boundingRect.height)}));this.l.tb()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}ua(){return this.l.ua()}ka(){return this.l.ka()}Wc(){var b=
[...this.fb];this.fb.clear();if(!this.Ea)for(const a of b)(b=a.play())&&b.catch(()=>{this.lc.has(a)||this.fb.add(a)})}Ma(b){if("function"!==typeof b.play)throw Error("missing play function");this.lc.delete(b);let a;try{a=b.play()}catch(c){this.fb.add(b);return}a&&a.catch(()=>{this.lc.has(b)||this.fb.add(b)})}Xa(b){this.fb.delete(b);this.lc.add(b)}Wb(b){this.Ea=!!b}Tc(b){alert(b.message)}});"use strict";
async function Aa(b){if(b.Vf)throw Error("already initialised");b.Vf=!0;var a=b.Ga.Qc(("playable-ad"===b.Ga.A?b.Ga.kb:"")+"dispatchworker.js");b.ad=await b.Ga.Bc(a,b.yb,{name:"DispatchWorker"});a=new MessageChannel;b.gd=a.port1;b.ad.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.qd=await Ga(b)}function Ba(b){return[b.gd,b.qd]}
async function Ga(b){const a=b.he.length;var c=b.Ga.Qc(("playable-ad"===b.Ga.A?b.Ga.kb:"")+"jobworker.js");c=await b.Ga.Bc(c,b.yb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.ad.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.he.push(c);return e.port1}
self.Ue=class{constructor(b){this.Ga=b;this.yb=b.ea;this.yb="preview"===b.A?this.yb+"workers/":this.yb+b.kb;this.Xf=Math.min(navigator.hardwareConcurrency||2,16);this.ad=null;this.he=[];this.qd=this.gd=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.ba({mg:!1,ng:"workermain.js",mb:["scripts/c3runtime.js"],wc:[],Ad:"",hg:"scripts/",xc:[],we:"html5"}));"use strict";
self.ba.sa(class extends self.Ca{constructor(b){super(b,"mouse");x(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.l.Gd().requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{l(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{l(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";const jb=180/Math.PI;
async function kb(b,a){a.usePlayMusicAsSoundWorkaround&&(b.pc=!0);b.wd=a.timeScaleMode;b.me=["equalpower","HRTF","soundfield"][a.panningModel];b.Yd=["linear","inverse","exponential"][a.distanceModel];b.ne=a.refDistance;b.le=a.maxDistance;b.pe=a.rolloffFactor;if(b.l.hd)b.pc=!0,b.h=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.l.ae)});else{var c={latencyHint:a.latencyHint};b.se||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.h=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.h=new webkitAudioContext(c);else throw Error("Web Audio API not supported");lb(b);b.h.onstatechange=()=>{"running"!==b.h.state&&lb(b);l(b,"audiocontext-state",{audioContextState:b.h.state})}}b.ab=b.h.createGain();b.ab.connect(b.h.destination);c=a.listenerPos;b.da[0]=c[0];b.da[1]=c[1];b.da[2]=c[2];b.h.listener.setPosition(c[0],c[1],c[2]);b.h.listener.setOrientation(...b.ga);self.C3_GetAudioContextCurrentTime=()=>b.h.currentTime;try{await Promise.all(a.preloadList.map(d=>
M(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.h.sampleRate,audioContextState:b.h.state,outputLatency:b.h.outputLatency||0}}
async function mb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,h=a.tags,k=a.isLooping,m=a.vol,n=a.pos,t=a.panning,v=a.stereoPan;let u=a.off;0<u&&!a.trueClock&&(b.h.getOutputTimestamp?(a=b.h.getOutputTimestamp(),u=u-a.performanceTime/1E3+a.contextTime):u=u-performance.now()/1E3+b.h.currentTime);b.ie=h.slice(0);nb(b,h);try{b.U=await pb(b,c,d,e,h,f);if(t){N(b.U,!0);var w=b.U,ha=t.x,J=t.y,Gb=t.z,Hb=t.angle,sa=t.innerAngle,ta=t.outerAngle,ua=t.outerGain;if(w.Fb){qb(w,ha,J,Gb,Hb);var E=self.ob.Ze;
w.ya[0]!==E(sa)&&(w.ya[0]=E(sa),w.H.coneInnerAngle=E(sa));w.ya[1]!==E(ta)&&(w.ya[1]=E(ta),w.H.coneOuterAngle=E(ta));w.ya[2]!==ua&&(w.ya[2]=ua,w.H.coneOuterGain=ua)}t.hasOwnProperty("uid")&&(b.U.wa=t.uid)}else"number"===typeof v&&0!==v?(O(b.U,!0),rb(b.U,v)):(N(b.U,!1),O(b.U,!1));b.U.Play(k,m,n,u)}catch(Ib){console.error("[Construct] Audio: error starting playback: ",Ib);return}finally{c=h.join(" ");d=b.Nb.get(c);if(!d)throw Error("expected pending tag");d.Bd--;0===d.Bd&&(d.resolve(),b.Nb.delete(c))}y(b)}
async function sb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await tb(b,c);for(const k of P(b,c))if(!k.Da){c=k.I.gain;c.cancelScheduledValues(0);var f=k.B.h.currentTime,h=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,h);k.Va=d;k.cb=h;k.re=a}Q(b)}async function ub(b,a){const c=a.tags;a=a.rate;await tb(b,c);for(const d of P(b,c))d.pa!==a&&(d.pa=a,d.Pa())}async function vb(b,a){const c=a.tags;a=a.pos;await tb(b,c);for(const d of P(b,c))d.Ic(a)}
async function wb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await pb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function xb(b,a){if(a=await M(b,"",a.url,a.type,a.isMusic,!0))a.m(),a=b.ma.indexOf(a),-1!==a&&b.ma.splice(a,1)}
async function yb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await M(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct] Audio: error loading convolution: ",m);return}for(const m of d){if("filter"===c)d=new self.De(b,...e);else if("delay"===c)d=new self.Be(b,...e);else if("convolution"===c){var h=d=new self.Ae(b,f.la,...e),k=a.bufferType;h.Wd=a.bufferOriginalUrl;h.Xd=k}else if("flanger"===c)d=
new self.Ee(b,...e);else if("phaser"===c)d=new self.Ge(b,...e);else if("gain"===c)d=new self.Fe(b,...e);else if("stereopan"===c)d=new self.Ie(b,...e);else if("tremolo"===c)d=new self.Je(b,...e);else if("ringmod"===c)d=new self.He(b,...e);else if("distortion"===c)d=new self.Ce(b,...e);else if("compressor"===c)d=new self.ze(b,...e);else if("analyser"===c)d=new self.ye(b,...e);else throw Error("invalid effect type");h=b;k=m;k=k.toLowerCase();let n=h.na.get(k);n||(n=[],h.na.set(k,n));d.fe=n.length;d.ud=
k;n.push(d);zb(h,k)}Ab(b)}
async function Bb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.J)e.Ja()&&1===c||!e.Ja()&&2===c?d.push(e):e.m();b.J=d}for(const f of b.na.values())for(const h of f)h.m();b.na.clear();b.uc=a.timeScale;b.cd=a.gameTime;d=a.listenerPos;b.da[0]=d[0];b.da[1]=d[1];b.da[2]=d[2];b.h.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ga[e]=d[e];b.h.listener.setOrientation(...b.ga)}b.Ea=a.isSilent;b.l.Wb(b.Ea);b.kc=a.masterVolume;b.ab.gain.value=
b.kc;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(h=>yb(b,h))));await Promise.all(d);await Promise.all(a.playing.map(f=>Cb(b,f,c)));Q(b)}
async function Db(b,a){try{const c=b.h.suspend(a.time);b.ee?b.h.resume():(b.h.startRendering().then(d=>{const e=[];for(let f=0,h=d.numberOfChannels;f<h;++f){const k=d.getChannelData(f);e.push(k.buffer)}b.l.vb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Eb(d)),b.ee=!0);await c}catch(c){Eb(c)}}
function lb(b){b.dc||(b.fd=!1,window.addEventListener("pointerup",b.Ha,!0),window.addEventListener("touchend",b.Ha,!0),window.addEventListener("click",b.Ha,!0),window.addEventListener("keydown",b.Ha,!0),b.dc=!0)}
async function M(b,a,c,d,e,f){for(var h of b.ma)if(h.rb()===c)return await Fb(h),h;if(f)return null;if(e&&(b.pc||b.de)){f=0;for(let k=0,m=b.ma.length;k<m;++k)h=b.ma[k],b.ma[f]=h,h.Ja()?h.m():++f;b.ma.length=f}f="audio/webm; codecs=opus"===d&&!b.se;e&&f&&(b.de=!0);c=!e||b.pc||f?new self.Me(b,a,c,d,e,f):new self.Ke(b,a,c,d,e);b.ma.push(c);await Fb(c);b.ke.has(a)||(l(b,"buffer-metadata",{originalUrl:a,duration:c.ja()}),b.ke.add(a));return c}
function Jb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Kb(b,a){return(a=b.na.get(a.toLowerCase()))?a[0].R():b.ia()}function zb(b,a){a=a.toLowerCase();let c=b.ia();var d=b.na.get(a);if(d&&d.length){c=d[0].R();for(let f=0,h=d.length;f<h;++f){var e=d[f];f+1===h?e.X(b.ia()):e.X(d[f+1].R())}}for(const f of Lb(b,a))e=f,d=c,e=e.ha||e.H||e.I,e.disconnect(),e.connect(d);b.Ta&&b.nd===a&&(b.Ta.disconnect(),b.Ta.connect(c))}
function*Lb(b,a){if(a)for(const c of b.J)Jb(0<c.ra.length?c.ra[0]:"",a)&&(yield c);else b.U&&!b.U.S()&&(yield b.U)}function Mb(b,a,c){return c?b.l.Tf(a).then(d=>{const e=b.h.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.h.decodeAudioData(a,d,e)})}function Nb(b,a){let c=0;for(let d=0,e=b.J.length;d<e;++d){const f=b.J[d];b.J[c]=f;f.T===a?f.m():++c}b.J.length=c}
function*P(b,a){if(0<a.length)for(const d of b.J){a:{b=d.ra;var c=a;for(const e of c){c=!1;for(const f of b)if(Jb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.U&&!b.U.S()&&(yield b.U)}async function pb(b,a,c,d,e,f){for(const h of b.J)if(h.rb()===c&&(h.zc()||f))return h.ra=e,h;a=await M(b,a,c,d,f);e="html5"===a.Zc?new self.Le(a.B,a,e):new self.Ne(a.B,a,e);b.J.push(e);return e}
function nb(b,a){a=a.join(" ");let c=b.Nb.get(a);if(!c){let d=null;c={Bd:0,promise:new Promise(e=>d=e),resolve:d};b.Nb.set(a,c)}c.Bd++}function tb(b,a){return(b=b.Nb.get((0===a.length?b.ie:a).join(" ")))?b.promise:Promise.resolve()}function Q(b){if(0<b.Za.size)y(b);else for(const a of b.J)if(!a.K&&!a.S()){y(b);break}}function Ob(b,a,c,d){l(b,"trigger",{type:a,tags:c,aiid:d})}function Ab(b){b.jd||(b.jd=!0,Promise.resolve().then(()=>Pb(b)))}
function Pb(b){const a={};for(const [c,d]of b.na)a[c]=d.map(e=>e.qb());l(b,"fxstate",{fxstate:a});b.jd=!1}
async function Cb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,h=a.isMusic,k=a.tags,m=a.isLooping,n=a.volume,t=a.playbackTime;if(!h||1!==c)if(h||2!==c){c=null;try{c=await pb(b,d,e,f,k,h)}catch(v){console.error("[Construct] Audio: error loading audio state: ",v);return}b=c;(d=a.pan)?(N(b,!0),e=b.H,f=d.pos,b.hb[0]=f[0],b.hb[1]=f[1],b.hb[2]=f[2],f=d.orient,b.gb[0]=f[0],b.gb[1]=f[1],b.gb[2]=f[2],e.setPosition(...b.hb),e.setOrientation(...b.gb),b.ya[0]=d.cia,b.ya[1]=d.coa,b.ya[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.wa=d.uid):N(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?O(b,!1):(O(b,!0),rb(b,d));c.Play(m,n,t,0);a.isPlaying||c.ub();c.Sc(a)}}}function Eb(b){console.error("[Audio] Offline rendering error: ",b)}
self.ob=class extends self.Ca{constructor(b){super(b,"audio");this.ab=this.h=null;this.dc=this.fd=!1;this.Ha=()=>{if(!this.fd){var a=this.h;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.dc&&(this.fd=!0,window.removeEventListener("pointerup",this.Ha,!0),window.removeEventListener("touchend",this.Ha,!0),window.removeEventListener("click",this.Ha,!0),window.removeEventListener("keydown",
this.Ha,!0),this.dc=!1)}};this.ma=[];this.J=[];this.U=null;this.ie=[];this.ke=new Set;this.je=-1;this.Nb=new Map;this.kc=1;this.Ea=!1;this.wd=0;this.uc=1;this.cd=0;this.me="HRTF";this.Yd="inverse";this.ne=600;this.le=1E4;this.pe=1;this.da=[0,0,0];this.ga=[0,0,-1,0,1,0];this.de=this.pc=!1;this.se=this.l.Se();this.na=new Map;this.Za=new Set;this.ee=this.jd=!1;this.nd="";this.Ta=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ta&&this.Ta.disconnect();this.nd=c.toLowerCase();this.Ta=this.h.createMediaStreamSource(a);
this.Ta.connect(Kb(this,this.nd))};this.cc=null;self.C3Audio_GetOutputStream=()=>{this.cc||(this.cc=this.h.createMediaStreamDestination(),this.ab.connect(this.cc));return this.cc.stream};self.C3Audio_DOMInterface=this;x(this,[["create-audio-context",a=>kb(this,a)],["play",a=>mb(this,a)],["stop",a=>{a=a.tags;for(const c of P(this,a))c.Ka()}],["stop-all",()=>{for(const a of this.J)a.Ka()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of P(this,c))a?d.ub():d.Vb();Q(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of P(this,c))R(d,a)}],["fade-volume",a=>sb(this,a)],["set-master-volume",a=>{this.kc=a.vol;this.ab.gain.value=this.kc}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of P(this,c))Qb(d,a)}],["set-silent",a=>{this.Ea=a.isSilent;this.l.Wb(this.Ea);for(const c of this.J)c.ac()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of P(this,c))d.Jc(a)}],["set-playback-rate",a=>ub(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of P(this,
c))O(d,!0),rb(d,a)}],["seek",a=>vb(this,a)],["preload",a=>wb(this,a)],["unload",a=>xb(this,a)],["unload-all",()=>{for(const a of this.ma)a.m();this.ma.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.h.resume&&this.h.resume();for(const c of this.J)c.Kc(a);a&&this.h.suspend&&this.h.suspend()}],["add-effect",a=>yb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,h=a.ramp;a=a.time;for(const k of c)c=this.na.get(k.toLowerCase()),!c||0>d||d>=c.length||c[d].ca(e,
f,h,a);Ab(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.na.get(a);if(!d||!d.length)break;for(const e of d)e.m();this.na.delete(a);zb(this,a)}}],["tick",a=>{this.uc=a.timeScale;this.cd=a.gameTime;this.je=a.tickCount;if(0!==this.wd)for(var c of this.J)c.Pa();!(c=a.listenerPos)||this.da[0]===c[0]&&this.da[1]===c[1]&&this.da[2]===c[2]||(this.da[0]=c[0],this.da[1]=c[1],this.da[2]=c[2],this.h.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ga[0]!==
c[0]||this.ga[1]!==c[1]||this.ga[2]!==c[2]||this.ga[3]!==c[3]||this.ga[4]!==c[4]||this.ga[5]!==c[5])){for(let d=0;6>d;++d)this.ga[d]=c[d];this.h.listener.setOrientation(...this.ga)}for(const d of a.instPans){a=d.uid;for(const e of this.J)e.wa===a&&qb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Bb(this,a)],["offline-render-audio",a=>Db(this,a)],["offline-render-finish",()=>{this.h.resume()}]])}Y(){return this.h}ia(){return this.ab}GetAudioContextExtern(){return this.Y()}GetDestinationNodeExtern(){return this.ia()}Ub(){return this.Ea}Ma(b){this.l.Ma(b)}Xa(b){this.l.Xa(b)}La(){for(var b of this.Za)b.La();
b=this.h.currentTime;for(var a of this.J)a.La(b);a=this.J.filter(c=>!c.K&&!c.S()).map(c=>c.qb());l(this,"state",{tickCount:this.je,outputLatency:this.h.outputLatency||0,audioInstances:a,analysers:[...this.Za].map(c=>({tag:c.ud,index:c.fe,peak:c.ib,rms:c.oe,binCount:c.o.frequencyBinCount,freqBins:c.ce}))});0===a.length&&0===this.Za.size&&this.ec&&(this.l.Rd(this.te),this.ec=!1)}static Ze(b){return b*jb}static Fd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Ve(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.ba.sa(self.ob);"use strict";function Fb(b){b.ic||(b.ic=b.Rc());return b.ic}self.Cd=class{constructor(b,a,c,d,e){this.B=b;this.$f=a;this.Ua=c;this.W=d;this.Wf=e;this.Zc="";this.ic=null}m(){this.ic=this.B=null}Rc(){}Y(){return this.B.Y()}Fc(){return this.$f}rb(){return this.Ua}Dc(){return this.W}Ja(){return this.Wf}ja(){}};"use strict";
self.Ke=class extends self.Cd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Zc="html5";this.O=new Audio;this.O.crossOrigin="anonymous";this.O.autoplay=!1;this.O.preload="auto";this.Ib=this.Jb=null;this.O.addEventListener("canplaythrough",()=>!0);this.Mb=this.Y().createGain();this.Lb=null;this.O.addEventListener("canplay",()=>{this.Jb&&(this.Jb(),this.Ib=this.Jb=null);!this.Lb&&this.O&&(this.Lb=this.Y().createMediaElementSource(this.O),this.Lb.connect(this.Mb))});this.onended=null;this.O.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.O.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ua}' error: `,f);this.Ib&&(this.Ib(f),this.Ib=this.Jb=null)})}m(){Nb(this.B,this);this.Mb.disconnect();this.Mb=null;this.Lb.disconnect();this.Lb=null;this.O&&!this.O.paused&&this.O.pause();this.O=this.onended=null;super.m()}Rc(){return new Promise((b,a)=>{this.Jb=b;this.Ib=a;this.O.src=this.Ua})}Z(){return this.O}ja(){return this.O.duration}};"use strict";
async function Rb(b){if(b.Qa)return b.Qa;var a=b.B.l;if("cordova"===a.A&&a.Id(b.Ua)&&a.fc)b.Qa=await a.Sb(b.Ua);else{a=await fetch(b.Ua);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Qa=await a.arrayBuffer()}}async function Sb(b){if(b.la)return b.la;b.la=await Mb(b.B,b.Qa,b.Yf);b.Qa=null}
self.Me=class extends self.Cd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Zc="webaudio";this.la=this.Qa=null;this.Yf=!!f}m(){Nb(this.B,this);this.la=this.Qa=null;super.m()}async Rc(){try{await Rb(this),await Sb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ua}': `,b)}}ja(){return this.la?this.la.duration:0}};"use strict";let Ub=0;
function N(b,a){a=!!a;b.Fb!==a&&(b.Fb=a,b.Fb?(O(b,!1),b.H||(b.H=b.Y().createPanner(),b.H.panningModel=b.B.me,b.H.distanceModel=b.B.Yd,b.H.refDistance=b.B.ne,b.H.maxDistance=b.B.le,b.H.rolloffFactor=b.B.pe),b.I.disconnect(),b.I.connect(b.H),b.H.connect(b.ia())):(b.H.disconnect(),b.I.disconnect(),b.I.connect(b.ia())))}
function O(b,a){a=!!a;b.hc!==a&&(b.hc=a,b.hc?(N(b,!1),b.ha=b.Y().createStereoPanner(),b.I.disconnect(),b.I.connect(b.ha),b.ha.connect(b.ia())):(b.ha.disconnect(),b.ha=null,b.I.disconnect(),b.I.connect(b.ia())))}function rb(b,a){b.hc&&b.td!==a&&(b.ha.pan.value=a,b.td=a)}function R(b,a){b.Va=a;b.I.gain.cancelScheduledValues(0);b.cb=-1;b.I.gain.value=b.Gc()}function Qb(b,a){a=!!a;b.Da!==a&&(b.Da=a,b.ac())}
function qb(b,a,c,d,e){if(b.Fb){var f=b.hb,h=b.gb,k=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.H.setPosition(...f);if(h[0]!==k||h[1]!==e||0!==h[2])h[0]=k,h[1]=e,h[2]=0,b.H.setOrientation(...h)}}function S(b){return b.kd?b.B.cd:performance.now()/1E3}
self.Dd=class{constructor(b,a,c){this.B=b;this.T=a;this.ra=c;this.bc=Ub++;this.I=this.Y().createGain();this.I.connect(this.ia());this.H=null;this.Fb=!1;this.hb=[0,0,0];this.gb=[0,0,0];this.ya=[0,0,0];this.ha=null;this.hc=!1;this.td=0;this.K=!0;this.aa=this.za=this.M=!1;this.Va=1;this.Da=!1;this.pa=1;b=this.B.wd;this.kd=1===b&&!this.Ja()||2===b;this.cb=this.wa=-1;this.re=!1}m(){this.T=this.B=null;this.H&&(this.H.disconnect(),this.H=null);this.ha&&(this.ha.disconnect(),this.ha=null);this.I.disconnect();
this.I=null}Y(){return this.B.Y()}ia(){return Kb(this.B,0<this.ra.length?this.ra[0]:"")}Fc(){return this.T.Fc()}rb(){return this.T.rb()}Dc(){return this.T.Dc()}Ja(){return this.T.Ja()}S(){}zc(){}IsPlaying(){return!this.K&&!this.M&&!this.S()}Wa(){}ja(){return this.T.ja()}Play(){}Ka(){}ub(){}Vb(){}La(b){-1!==this.cb&&b>=this.cb&&(this.cb=-1,this.re&&this.Ka(),Ob(this.B,"fade-ended",this.ra,this.bc))}Gc(){const b=this.Va;return isFinite(b)?b:0}Ub(){return this.B.Ub()}ac(){}Jc(){}Pa(){}Ic(){}Kc(){}Hc(){}qb(){var b=
this.bc,a=this.ra,c=this.ja(),d=-1===this.cb?this.Va:this.I.gain.value,e=this.IsPlaying();if(this.H){var f=this.H;f={pos:this.hb,orient:this.gb,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.wa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Wa(),playbackRate:this.pa,uid:this.wa,bufferOriginalUrl:this.Fc(),bufferUrl:"",bufferType:this.Dc(),isMusic:this.Ja(),isLooping:this.aa,isMuted:this.Da,resumePosition:this.Hc(),pan:f,stereoPan:this.ha?
this.td:null}}Sc(b){var a=b.playbackRate;this.pa!==a&&(this.pa=a,this.Pa());Qb(this,b.isMuted)}};"use strict";
self.Le=class extends self.Dd{constructor(b,a,c){super(b,a,c);this.T.Mb.connect(this.I);this.T.onended=()=>this.Uc()}m(){this.Ka();this.T.Mb.disconnect();super.m()}Z(){return this.T.Z()}Uc(){this.K=!0;this.wa=-1;Ob(this.B,"ended",this.ra,this.bc)}S(){return this.Z().ended}zc(){return this.K?!0:this.S()}Wa(){let b=this.Z().currentTime;this.aa||(b=Math.min(b,this.ja()));return b}Play(b,a,c){const d=this.Z();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);R(this,a);this.Da=!1;d.muted&&
(d.muted=!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.T.rb()}' to position '${c}': `,e)}this.B.Ma(d);this.M=this.K=!1;this.aa=b;this.pa=1}Ka(){const b=this.Z();b.paused||b.pause();this.B.Xa(b);this.K=!0;this.M=!1;this.wa=-1}ub(){if(!(this.M||this.K||this.S())){var b=this.Z();b.paused||b.pause();this.B.Xa(b);this.M=!0}}Vb(){!this.M||this.K||this.S()||(this.B.Ma(this.Z()),this.M=!1)}ac(){this.Z().muted=this.Da||this.Ub()}Jc(b){b=!!b;
this.aa!==b&&(this.aa=b,this.Z().loop=b)}Pa(){let b=this.pa;this.kd&&(b*=this.B.uc);try{this.Z().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}Ic(b){if(!this.K&&!this.S())try{this.Z().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}Hc(){return this.Wa()}Kc(b){b?this.IsPlaying()?(this.Z().pause(),this.za=!0):this.za=!1:this.za&&(this.B.Ma(this.Z()),this.za=!1)}};"use strict";
function T(b){b.v&&(b.v.onended=null,b.v.disconnect(),b.v.buffer=null);b.v=null;b.xb=null}
self.Ne=class extends self.Dd{constructor(b,a,c){super(b,a,c);this.v=null;this.mc=d=>this.Uc(d);this.ed=!0;this.xb=null;this.V=this.oc=this.qc=0;this.pd=1}m(){this.Ka();T(this);this.mc=null;super.m()}Uc(b){this.M||this.za||b.target!==this.xb||(this.K=this.ed=!0,this.wa=-1,T(this),Ob(this.B,"ended",this.ra,this.bc))}S(){return!this.K&&this.v&&this.v.loop||this.M?!1:this.ed}zc(){return!this.v||this.K?!0:this.S()}Wa(){let b;b=this.M?this.V:this.oc+(S(this)-this.qc)*this.pa;this.aa||(b=Math.min(b,this.ja()));
return b}Play(b,a,c,d){this.Da=!1;this.pd=1;R(this,a);T(this);this.v=this.Y().createBufferSource();this.v.buffer=this.T.la;this.v.connect(this.I);this.xb=this.v;this.v.onended=this.mc;this.v.loop=b;this.v.start(d,c);this.M=this.K=this.ed=!1;this.aa=b;this.pa=1;this.qc=S(this);this.oc=c}Ka(){if(this.v)try{this.v.stop(0)}catch(b){}this.K=!0;this.M=!1;this.wa=-1}ub(){this.M||this.K||this.S()||(this.V=this.Wa(),this.aa&&(this.V%=this.ja()),this.M=!0,this.v.stop(0))}Vb(){!this.M||this.K||this.S()||(T(this),
this.v=this.Y().createBufferSource(),this.v.buffer=this.T.la,this.v.connect(this.I),this.xb=this.v,this.v.onended=this.mc,this.v.loop=this.aa,R(this,this.Va),this.Pa(),this.v.start(0,this.V),this.qc=S(this),this.oc=this.V,this.M=!1)}Gc(){return super.Gc()*this.pd}ac(){this.pd=this.Da||this.Ub()?0:1;R(this,this.Va)}Jc(b){b=!!b;this.aa!==b&&(this.aa=b,this.v&&(this.v.loop=b))}Pa(){let b=this.pa;this.kd&&(b*=this.B.uc);this.v&&(this.v.playbackRate.value=b)}Ic(b){this.K||this.S()||(this.M?this.V=b:(this.ub(),
this.V=b,this.Vb()))}Hc(){return this.V}Kc(b){b?this.IsPlaying()?(this.za=!0,this.V=this.Wa(),this.aa&&(this.V%=this.ja()),this.v.stop(0)):this.za=!1:this.za&&(T(this),this.v=this.Y().createBufferSource(),this.v.buffer=this.T.la,this.v.connect(this.I),this.xb=this.v,this.v.onended=this.mc,this.v.loop=this.aa,R(this,this.Va),this.Pa(),this.v.start(0,this.V),this.qc=S(this),this.oc=this.V,this.za=!1)}Sc(b){super.Sc(b);this.V=b.resumePosition}};"use strict";function U(b){return b.h.createGain()}
function V(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.h.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class W{constructor(b){this.B=b;this.h=b.Y();this.fe=-1;this.W=this.ud="";this.u=null}m(){this.h=null}R(){}X(){}qb(){return{type:this.W,tag:this.ud,params:this.u}}}
self.De=class extends W{constructor(b,a,c,d,e,f,h){super(b);this.W="filter";this.u=[a,c,d,e,f,h];this.C=U(this);this.j=U(this);this.j.gain.value=h;this.i=U(this);this.i.gain.value=1-h;this.G=this.h.createBiquadFilter();this.G.type=a;this.G.frequency.value=c;this.G.detune.value=d;this.G.Q.value=e;this.G.gain.vlaue=f;this.C.connect(this.G);this.C.connect(this.i);this.G.connect(this.j)}m(){this.C.disconnect();this.G.disconnect();this.j.disconnect();this.i.disconnect();super.m()}X(b){this.j.disconnect();
this.j.connect(b);this.i.disconnect();this.i.connect(b)}R(){return this.C}ca(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.u[5]=a;V(this,this.j.gain,a,c,d);V(this,this.i.gain,1-a,c,d);break;case 1:this.u[1]=a;V(this,this.G.frequency,a,c,d);break;case 2:this.u[2]=a;V(this,this.G.detune,a,c,d);break;case 3:this.u[3]=a;V(this,this.G.Q,a,c,d);break;case 4:this.u[4]=a,V(this,this.G.gain,a,c,d)}}};
self.Be=class extends W{constructor(b,a,c,d){super(b);this.W="delay";this.u=[a,c,d];this.C=U(this);this.j=U(this);this.j.gain.value=d;this.i=U(this);this.i.gain.value=1-d;this.Kb=U(this);this.$=this.h.createDelay(a);this.$.delayTime.value=a;this.Bb=U(this);this.Bb.gain.value=c;this.C.connect(this.Kb);this.C.connect(this.i);this.Kb.connect(this.j);this.Kb.connect(this.$);this.$.connect(this.Bb);this.Bb.connect(this.Kb)}m(){this.C.disconnect();this.j.disconnect();this.i.disconnect();this.Kb.disconnect();
this.$.disconnect();this.Bb.disconnect();super.m()}X(b){this.j.disconnect();this.j.connect(b);this.i.disconnect();this.i.connect(b)}R(){return this.C}ca(b,a,c,d){const e=self.ob.Fd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.u[2]=a;V(this,this.j.gain,a,c,d);V(this,this.i.gain,1-a,c,d);break;case 4:this.u[1]=e(a);V(this,this.Bb.gain,e(a),c,d);break;case 5:this.u[0]=a,V(this,this.$.delayTime,a,c,d)}}};
self.Ae=class extends W{constructor(b,a,c,d){super(b);this.W="convolution";this.u=[c,d];this.Xd=this.Wd="";this.C=U(this);this.j=U(this);this.j.gain.value=d;this.i=U(this);this.i.gain.value=1-d;this.Ab=this.h.createConvolver();this.Ab.normalize=c;this.Ab.buffer=a;this.C.connect(this.Ab);this.C.connect(this.i);this.Ab.connect(this.j)}m(){this.C.disconnect();this.Ab.disconnect();this.j.disconnect();this.i.disconnect();super.m()}X(b){this.j.disconnect();this.j.connect(b);this.i.disconnect();this.i.connect(b)}R(){return this.C}ca(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.u[1]=a,V(this,this.j.gain,a,c,d),V(this,this.i.gain,1-a,c,d)}}qb(){const b=super.qb();b.bufferOriginalUrl=this.Wd;b.bufferUrl="";b.bufferType=this.Xd;return b}};
self.Ee=class extends W{constructor(b,a,c,d,e,f){super(b);this.W="flanger";this.u=[a,c,d,e,f];this.C=U(this);this.i=U(this);this.i.gain.value=1-f/2;this.j=U(this);this.j.gain.value=f/2;this.Db=U(this);this.Db.gain.value=e;this.$=this.h.createDelay(a+c);this.$.delayTime.value=a;this.F=this.h.createOscillator();this.F.frequency.value=d;this.N=U(this);this.N.gain.value=c;this.C.connect(this.$);this.C.connect(this.i);this.$.connect(this.j);this.$.connect(this.Db);this.Db.connect(this.$);this.F.connect(this.N);
this.N.connect(this.$.delayTime);this.F.start(0)}m(){this.F.stop(0);this.C.disconnect();this.$.disconnect();this.F.disconnect();this.N.disconnect();this.i.disconnect();this.j.disconnect();this.Db.disconnect();super.m()}X(b){this.j.disconnect();this.j.connect(b);this.i.disconnect();this.i.connect(b)}R(){return this.C}ca(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.u[4]=a;V(this,this.j.gain,a/2,c,d);V(this,this.i.gain,1-a/2,c,d);break;case 6:this.u[1]=a/1E3;V(this,this.N.gain,a/1E3,
c,d);break;case 7:this.u[2]=a;V(this,this.F.frequency,a,c,d);break;case 8:this.u[3]=a/100,V(this,this.Db.gain,a/100,c,d)}}};
self.Ge=class extends W{constructor(b,a,c,d,e,f,h){super(b);this.W="phaser";this.u=[a,c,d,e,f,h];this.C=U(this);this.i=U(this);this.i.gain.value=1-h/2;this.j=U(this);this.j.gain.value=h/2;this.G=this.h.createBiquadFilter();this.G.type="allpass";this.G.frequency.value=a;this.G.detune.value=c;this.G.Q.value=d;this.F=this.h.createOscillator();this.F.frequency.value=f;this.N=U(this);this.N.gain.value=e;this.C.connect(this.G);this.C.connect(this.i);this.G.connect(this.j);this.F.connect(this.N);this.N.connect(this.G.frequency);
this.F.start(0)}m(){this.F.stop(0);this.C.disconnect();this.G.disconnect();this.F.disconnect();this.N.disconnect();this.i.disconnect();this.j.disconnect();super.m()}X(b){this.j.disconnect();this.j.connect(b);this.i.disconnect();this.i.connect(b)}R(){return this.C}ca(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.u[5]=a;V(this,this.j.gain,a/2,c,d);V(this,this.i.gain,1-a/2,c,d);break;case 1:this.u[0]=a;V(this,this.G.frequency,a,c,d);break;case 2:this.u[1]=a;V(this,this.G.detune,a,c,
d);break;case 3:this.u[2]=a;V(this,this.G.Q,a,c,d);break;case 6:this.u[3]=a;V(this,this.N.gain,a,c,d);break;case 7:this.u[4]=a,V(this,this.F.frequency,a,c,d)}}};self.Fe=class extends W{constructor(b,a){super(b);this.W="gain";this.u=[a];this.o=U(this);this.o.gain.value=a}m(){this.o.disconnect();super.m()}X(b){this.o.disconnect();this.o.connect(b)}R(){return this.o}ca(b,a,c,d){const e=self.ob.Fd;switch(b){case 4:this.u[0]=e(a),V(this,this.o.gain,e(a),c,d)}}};
self.Ie=class extends W{constructor(b,a){super(b);this.W="stereopan";this.u=[a];this.o=this.h.createStereoPanner();this.o.pan.value=a}m(){this.o.disconnect();super.m()}X(b){this.o.disconnect();this.o.connect(b)}R(){return this.o}ca(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.u[0]=a,V(this,this.o.pan,a,c,d)}}};
self.Je=class extends W{constructor(b,a,c){super(b);this.W="tremolo";this.u=[a,c];this.o=U(this);this.o.gain.value=1-c/2;this.F=this.h.createOscillator();this.F.frequency.value=a;this.N=U(this);this.N.gain.value=c/2;this.F.connect(this.N);this.N.connect(this.o.gain);this.F.start(0)}m(){this.F.stop(0);this.F.disconnect();this.N.disconnect();this.o.disconnect();super.m()}X(b){this.o.disconnect();this.o.connect(b)}R(){return this.o}ca(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.u[1]=
a;V(this,this.o.gain,1-a/2,c,d);V(this,this.N.gain,a/2,c,d);break;case 7:this.u[0]=a,V(this,this.F.frequency,a,c,d)}}};
self.He=class extends W{constructor(b,a,c){super(b);this.W="ringmod";this.u=[a,c];this.C=U(this);this.j=U(this);this.j.gain.value=c;this.i=U(this);this.i.gain.value=1-c;this.Pb=U(this);this.Pb.gain.value=0;this.F=this.h.createOscillator();this.F.frequency.value=a;this.F.connect(this.Pb.gain);this.F.start(0);this.C.connect(this.Pb);this.C.connect(this.i);this.Pb.connect(this.j)}m(){this.F.stop(0);this.F.disconnect();this.Pb.disconnect();this.C.disconnect();this.j.disconnect();this.i.disconnect();super.m()}X(b){this.j.disconnect();
this.j.connect(b);this.i.disconnect();this.i.connect(b)}R(){return this.C}ca(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.u[1]=a;V(this,this.j.gain,a,c,d);V(this,this.i.gain,1-a,c,d);break;case 7:this.u[0]=a,V(this,this.F.frequency,a,c,d)}}};
self.Ce=class extends W{constructor(b,a,c,d,e,f){super(b);this.W="distortion";this.u=[a,c,d,e,f];this.C=U(this);this.sc=U(this);this.rc=U(this);b=d;.01>b&&(b=.01);this.sc.gain.value=b;this.rc.gain.value=Math.pow(1/b,.6)*e;this.j=U(this);this.j.gain.value=f;this.i=U(this);this.i.gain.value=1-f;this.vc=this.h.createWaveShaper();this.$c=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.$c[32768+e]=f,this.$c[32768-
e-1]=-f;this.vc.curve=this.$c;this.C.connect(this.sc);this.C.connect(this.i);this.sc.connect(this.vc);this.vc.connect(this.rc);this.rc.connect(this.j)}m(){this.C.disconnect();this.sc.disconnect();this.vc.disconnect();this.rc.disconnect();this.j.disconnect();this.i.disconnect();super.m()}X(b){this.j.disconnect();this.j.connect(b);this.i.disconnect();this.i.connect(b)}R(){return this.C}ca(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.u[4]=a,V(this,this.j.gain,a,c,d),V(this,this.i.gain,
1-a,c,d)}}};self.ze=class extends W{constructor(b,a,c,d,e,f){super(b);this.W="compressor";this.u=[a,c,d,e,f];this.o=this.h.createDynamicsCompressor();this.o.threshold.value=a;this.o.knee.value=c;this.o.ratio.value=d;this.o.attack.value=e;this.o.release.value=f}m(){this.o.disconnect();super.m()}X(b){this.o.disconnect();this.o.connect(b)}R(){return this.o}ca(){}};
self.ye=class extends W{constructor(b,a,c){super(b);this.W="analyser";this.u=[a,c];this.o=this.h.createAnalyser();this.o.fftSize=a;this.o.smoothingTimeConstant=c;this.ce=new Float32Array(this.o.frequencyBinCount);this.qe=new Uint8Array(a);this.oe=this.ib=0;b=this.B;b.Za.add(this);Q(b)}m(){this.B.Za.delete(this);this.o.disconnect();super.m()}La(){this.o.getFloatFrequencyData(this.ce);this.o.getByteTimeDomainData(this.qe);const b=this.o.fftSize;let a=this.ib=0;for(var c=0;c<b;++c){let d=(this.qe[c]-
128)/128;0>d&&(d=-d);this.ib<d&&(this.ib=d);a+=d*d}c=self.ob.Ve;this.ib=c(this.ib);this.oe=c(Math.sqrt(a/b))}X(b){this.o.disconnect();this.o.connect(b)}R(){return this.o}ca(){}};"use strict";function X(b){b.stopPropagation()}
self.ba.sa(class extends self.Tb{constructor(b){super(b,"progress-bar")}Ac(b,a){const c=document.createElement("progress");c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",X);c.addEventListener("pointermove",X);c.addEventListener("pointerrawupdate",X);c.addEventListener("pointerup",X);c.addEventListener("mousedown",X);c.addEventListener("mouseup",X);c.addEventListener("click",()=>ea(this,b));a.id&&(c.id=a.id);a.className&&(c.className=
a.className);this.wb(c,a);return c}wb(b,a){b.title=a.title;const c=a.value;a=a.max;0<a&&0<=c?(b.max=a,b.value=c):(b.removeAttribute("value"),b.removeAttribute("max"))}});"use strict";async function Vb(b,a){a=a.type;let c=!0;0===a?c=await Wb():1===a&&(c=await Xb());l(b,"permission-result",{type:a,result:c})}
async function Wb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Xb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.ba.sa(class extends self.Ca{constructor(b){super(b,"touch");r(this,"request-permission",a=>Vb(this,a))}});"use strict";
async function Yb(){try{return{isOk:!0,isPersistent:await navigator.storage.persist()}}catch(b){return console.error("[Construct] Error requesting persistent storage: ",b),{isOk:!1}}}self.ba.sa(class extends self.Ca{constructor(b){super(b,"localstorage");x(this,[["init",()=>this.Xb()],["request-persistent",()=>Yb()]])}async Xb(){let b=!1;try{b=await navigator.storage.persisted()}catch(a){b=!1,console.warn("[Construct] Error checking storage persisted state: ",a)}return{isPersistent:b}}});"use strict";
function Y(b){b.stopPropagation()}
self.ba.sa(class extends self.Tb{constructor(b){super(b,"sliderbar")}Ac(b,a){const c=document.createElement("input");c.type="range";c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",Y);c.addEventListener("pointermove",Y);c.addEventListener("pointerrawupdate",Y);c.addEventListener("pointerup",Y);c.addEventListener("mousedown",Y);c.addEventListener("mouseup",Y);c.addEventListener("keydown",Y);c.addEventListener("keyup",Y);c.addEventListener("contextmenu",
d=>d.preventDefault());c.addEventListener("click",()=>ea(this,b));c.addEventListener("change",()=>z(this,"change",b,{value:parseFloat(c.value)}));c.addEventListener("input",()=>z(this,"input",b,{value:parseFloat(c.value)}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.wb(c,a);return c}wb(b,a){b.max=a.max;b.min=a.min;b.step=a.step;b.value=a.value;b.disabled=!a.isEnabled;b.title=a.title}});"use strict";let Z=null,Zb=null;
window.addEventListener("beforeinstallprompt",b=>{b.preventDefault();Z=b;Zb&&l(Zb,"install-available");return!1});function $b(){}function ac(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>l(b,"sw-message",a.data))}
function bc(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}async function cc(){if(!Z)return{result:"unavailable"};try{return Z.prompt(),{result:(await Z.userChoice).outcome}}catch(b){return console.error("[Construct] Requesting install failed: ",b),{result:"failed"}}}
self.ba.sa(class extends self.Ca{constructor(b){super(b,"browser");this.A="";x(this,[["get-initial-state",a=>{this.A=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
ac(this)],["alert",a=>this.Tc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Vc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>bc(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||this.l.ta()?window.open(c,"_blank"):this.xg||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.l.ta()||"macos-wkwebview"===this.A)self.ba.$b(!0),this.l.Oa({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===
a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch($b)}}],["exit-fullscreen",()=>{if(this.l.ta()||"macos-wkwebview"===this.A)self.ba.$b(!1),this.l.Oa({type:"set-fullscreen",
fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch($b)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var h=
document.querySelector(e);f=h?[h]:[]}else f=[document.documentElement];e=f;for(const k of e)c.startsWith("--")?k.style.setProperty(c,d):k.style[c]=d}catch(k){console.warn("[Browser] Failed to set style: ",k)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}],["set-window-size",a=>{window.resizeTo(a.windowWidth,
a.windowHeight)}],["set-window-position",a=>{window.moveTo(a.windowX,a.windowY)}],["request-install",()=>cc()],["set-warn-on-close",a=>{a.enabled?window.addEventListener("beforeunload",this.Vd):window.removeEventListener("beforeunload",this.Vd)}]]);window.addEventListener("online",()=>{l(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{l(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{l(this,"hashchange",{location:location.toString()})});this.Vd=
a=>a.preventDefault();document.addEventListener("backbutton",()=>{l(this,"backbutton")})}yc(){Z?l(this,"install-available"):Zb=this;window.addEventListener("appinstalled",()=>{l(this,"app-installed")})}Tc(b){alert(b.message)}Vc(b){b=b.isFocus;if("nwjs"===this.A){const a="nwjs"===this.A?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";
async function dc(){return new Promise(b=>{const a=document.getElementsByTagName("head")[0],c=document.createElement("script");c.src="/sdk.js";c.async=!0;c.onload=async()=>b();a.appendChild(c)})}async function ec(b){b.g&&(b.g.onEvent(b.g.EVENTS.HISTORY_BACK,()=>{l(b.s,"ysdk-handle-event",{type:"HISTORY_BACK"})}),await b.Mc(),await fc(b))}async function fc(b){if(b.g){var a=await b.g.feedback.canReview();await p(b.s,"ysdk-update-can-review",{value:a.value})}}
class gc{constructor(b){this.s=b;this.g=void 0;window.ysdk=void 0;r(this.s,"ysdk-initialize",this.Pe.bind(this));r(this.s,"ysdk-loading-api-ready",this.kf.bind(this));r(this.s,"ysdk-gameplay-api-start",this.Na.bind(this));r(this.s,"ysdk-gameplay-api-stop",this.Lc.bind(this));r(this.s,"ysdk-show-fullscreen-ad",this.tf.bind(this));r(this.s,"ysdk-show-rewarded-ad",this.uf.bind(this));r(this.s,"ysdk-show-sticky-banner",this.vf.bind(this));r(this.s,"ysdk-hide-sticky-banner",this.hf.bind(this));r(this.s,
"ysdk-get-leaderboard-entries",this.cf.bind(this));r(this.s,"ysdk-set-leaderboard-score",this.pf.bind(this));r(this.s,"ysdk-purchase",this.lf.bind(this));r(this.s,"ysdk-consume-purchase",this.$e.bind(this));r(this.s,"ysdk-get-purchases",this.gf.bind(this));r(this.s,"ysdk-get-catalog",this.bf.bind(this));r(this.s,"ysdk-get-player",this.df.bind(this));r(this.s,"ysdk-get-player-data",this.ef.bind(this));r(this.s,"ysdk-get-player-stats",this.ff.bind(this));r(this.s,"ysdk-set-player-data",this.qf.bind(this));
r(this.s,"ysdk-set-player-stats",this.rf.bind(this));r(this.s,"ysdk-increment-player-stats",this.jf.bind(this));r(this.s,"ysdk-dispatch-event",this.af.bind(this));r(this.s,"ysdk-shortcuts-show-prompt",this.sf.bind(this));r(this.s,"ysdk-remote-config-fetch",this.mf.bind(this));r(this.s,"ysdk-request-review",this.nf.bind(this));r(this.s,"ysdk-update-can-show-shortcut-prompt",this.Mc.bind(this))}async Pe(){await dc();if(window.YaGames)return this.g=await window.YaGames.init(),window.ysdk=this.g,window.g=
this.g,await ec(this),this.g.features.PluginEngineDataReporterAPI?.report({engineName:"Construct",engineVersion:"3",pluginName:"yagames_sdk by LisGames",pluginVersion:"2.11.0"}),console.log("%c YandexGamesSDK for Construct 3 v2.11.0 ","background: #14151f; color: #fb923c"),{environment:{app:{id:this.g.environment.app.id},browser:{lang:this.g.environment.browser.lang},i18n:{lang:this.g.environment.i18n.lang,tld:this.g.environment.i18n.tld},payload:this.g.environment.payload},deviceType:this.g.deviceInfo.type}}kf(){this.g&&
this.g.features.LoadingAPI?.ready()}Na(){this.g&&this.g.features.GameplayAPI?.start()}Lc(){this.g&&this.g.features.GameplayAPI?.stop()}tf(){this.g&&this.g.adv.showFullscreenAdv({callbacks:{onClose:b=>{this.Lc();l(this.s,"ysdk-fullscreen-ad-callback",{type:"onClose",wasShown:b})},onOpen:()=>{this.Na();l(this.s,"ysdk-fullscreen-ad-callback",{type:"onOpen"})},onError:b=>{this.Na();l(this.s,"ysdk-fullscreen-ad-callback",{type:"onError",error:JSON.stringify(b)})},onOffline:()=>{this.Na();l(this.s,"ysdk-fullscreen-ad-callback",
{type:"onOffline"})}}})}uf(b){this.g&&this.g.adv.showRewardedVideo({callbacks:{onOpen:()=>{this.Lc();l(this.s,"ysdk-rewarded-ad-callback",{id:b.id,type:"onOpen"})},onRewarded:()=>{this.Na();l(this.s,"ysdk-rewarded-ad-callback",{id:b.id,type:"onRewarded"})},onClose:()=>{this.Na();l(this.s,"ysdk-rewarded-ad-callback",{id:b.id,type:"onClose"})},onError:a=>{this.Na();l(this.s,"ysdk-rewarded-ad-callback",{id:b.id,type:"onError",error:JSON.stringify(a)})}}})}vf(){this.g&&this.g.adv.showBannerAdv()}hf(){this.g&&
this.g.adv.hideBannerAdv()}async cf(b){if(this.g)return b=await (await this.g.getLeaderboards()).getLeaderboardEntries(b.leaderboardName,b.options),{leaderboard:b.leaderboard,ranges:b.ranges,userRank:b.userRank,entries:b.entries.map(a=>({score:a.score,extraData:a.extraData,rank:a.rank,player:{avatarSrc:{small:a.player.getAvatarSrc("small"),medium:a.player.getAvatarSrc("medium"),large:a.player.getAvatarSrc("large")},avatarSrcSet:{small:a.player.getAvatarSrcSet("small"),medium:a.player.getAvatarSrcSet("medium"),
large:a.player.getAvatarSrcSet("large")},lang:a.player.lang,publicName:a.player.publicName,scopePermissions:a.player.scopePermissions,uniqueID:a.player.uniqueID},formattedScore:a.formattedScore}))}}async pf(b){this.g&&await (await this.g.getLeaderboards()).setLeaderboardScore(b.leaderboardName,b.score,b.extraData||void 0)}async lf(b){if(this.g)try{const a=await (await this.g.getPayments({signed:!0})).purchase({id:b.productID,developerPayload:b.developerPayload});l(this.s,"ysdk-purchase-callback",
{success:!0,productID:a.productID,purchaseToken:a.purchaseToken,developerPayload:a.developerPayload,signature:a.signature})}catch(a){console.error(a),l(this.s,"ysdk-purchase-callback",{error:JSON.stringify(a)})}}async $e(b){this.g&&await (await this.g.getPayments({signed:!0})).consumePurchase(b.purchaseToken)}async gf(){if(this.g){var b=await (await this.g.getPayments({signed:!0})).getPurchases(),a=[];for(let c=0;c<b.length;c++){const d=b[c];a[c]={productID:d.productID,purchaseToken:d.purchaseToken,
developerPayload:d.developerPayload}}a.signature=b.signature;return a}}async bf(){if(this.g){var b=await (await this.g.getPayments({signed:!0})).getCatalog(),a=[];for(let c=0;c<b.length;c++){const d=b[c];a[c]={id:d.id,title:d.title,description:d.description,imageURI:d.imageURI,price:d.price,priceValue:d.priceValue,priceCurrencyCode:d.priceCurrencyCode,priceCurrencyImage:{small:d.getPriceCurrencyImage("small"),medium:d.getPriceCurrencyImage("medium"),svg:d.getPriceCurrencyImage("svg")}}}return a}}async ef(b){if(this.g)return await (await this.g.getPlayer()).getData(b)}async ff(b){if(this.g)return await (await this.g.getPlayer()).getStats(b)}async qf(b){this.g&&
await (await this.g.getPlayer()).setData(b.data,b.flush)}async rf(b){this.g&&await (await this.g.getPlayer()).setStats(b)}async jf(b){this.g&&await (await this.g.getPlayer()).incrementStats(b)}async df(b){if(this.g)return b.requestPersonalInfo&&this.g.openAuthDialog?(b=await this.g.getPlayer({signed:!0,scopes:!0}),"lite"===b.getMode()&&(await this.g.openAuthDialog(),await this.g.getPlayer({signed:!0,scopes:!0})),b=await this.g.getPlayer({signed:!0,scopes:!0})):b=await this.g.getPlayer({scopes:!1}),
await fc(this),{isAuthorized:"lite"!==b.getMode(),isAccessGranted:""!==b.getName(),uniqueID:b.getUniqueID(),publicName:b.getName(),avatars:{small:b.getPhoto("small"),medium:b.getPhoto("medium"),large:b.getPhoto("large")},signature:b.signature,payingStatus:b.getPayingStatus()}}af(b){this.g&&this.g.dispatchEvent(this.g.EVENTS[b.name])}async Mc(){if(this.g){var b=await this.g.shortcut.canShowPrompt();await p(this.s,"ysdk-update-can-show-shortcut-prompt",{canShow:b.canShow})}}async sf(){if(this.g){var b=
await this.g.shortcut.showPrompt();await this.Mc();l(this.s,"ysdk-shortcut-show-prompt-result",{accepted:"accepted"===b.outcome})}}async mf(b){return this.g?await this.g.getFlags(b):b.yg}async nf(){if(this.g){if((await this.g.feedback.canReview()).value){const b=await this.g.feedback.requestReview();await fc(this);return{feedbackSent:b.feedbackSent}}return{feedbackSent:!1}}}}
function hc(b){b.L=document.createElement("iframe");b.L.id="tv-emulator";b.L.src="";b.L.style.position="absolute";b.L.style.display="none";b.L.style.width="288px";b.L.style.height="640px";b.L.style.border="none";b.L.style.zIndex="999";b.L.style.transformOrigin="right bottom";document.body.appendChild(b.L);b.Ld(b.L);fetch("tv_emulator.html").then(a=>a.text()).then(a=>{b.L.contentWindow.document.write(a);window.addEventListener("resize",b.Ld.bind(b));window.addEventListener("message",b.Xe.bind(b));
window.addEventListener("keydown",b.We.bind(b))});b.Ba={id:"TV Remote Emulator",index:0,axes:[0,0,0,0],connected:!1,buttons:Array(16).fill(0).map(()=>({pressed:!1,kg:!1,value:0})),timestamp:Math.floor(Date.now()/1E3)}}function ic(b){b.enabled=!0;b.L.style.display="block";const a=new Event("gamepadconnected");b.Ba.connected=!0;a.gamepad=b.Ba;b.Ba.timestamp=Math.floor(Date.now()/1E3);window.dispatchEvent(a);b.Zf=navigator.getGamepads;navigator.getGamepads=()=>[b.Ba]}
class jc{constructor(b){this.s=b;this.enabled=!1;this.xe={tg:12,qg:13,rg:14,sg:15}}We(b){"F6"===b.key&&("none"===this.L.style.display?ic(this):(this.enabled=!1,this.L.style.display="none",b=new Event("gamepaddisconnected"),this.Ba.connected=!1,b.gamepad=this.Ba,this.Ba.timestamp=Math.floor(Date.now()/1E3),window.dispatchEvent(b),navigator.getGamepads=this.Zf))}Xe(b){if("tv-emulator-event"===b.data.event)switch(b.data.name){case "Enter":window.dispatchEvent(new KeyboardEvent(b.data.pressed?"keydown":
"keyup",{key:"Enter",code:"Enter",keyCode:13}));break;case "Back":b.data.pressed||l(this.s,"ysdk-handle-event",{type:"HISTORY_BACK"});break;default:const a=this.Ba.buttons[this.xe[b.data.name]];a.pressed=b.data.pressed;a.value=b.data.pressed?1:0;a.kg=b.data.pressed;this.Ba.timestamp=Math.floor(Date.now()/1E3)}}Ld(){this.L.style.transform=`scale(${Math.min(window.innerWidth/288,window.innerHeight/640)})`;this.L.style.left=`${window.innerWidth-288}px`;this.L.style.top=`${window.innerHeight-640}px`}}
function kc(b){const a=navigator.getGamepads().filter(c=>c);if(a.length){for(const c of a)c&&(b.data.upPressed=b.data.upPressed||c.buttons[12].pressed,b.data.downPressed=b.data.downPressed||c.buttons[13].pressed,b.data.leftPressed=b.data.leftPressed||c.buttons[14].pressed,b.data.rightPressed=b.data.rightPressed||c.buttons[15].pressed);l(b,"gamepads-update",b.data)}}
self.ba.sa(class extends self.Ca{constructor(b){super(b,"yagames_sdk");this.pg=new gc(this);this.lg=new jc(this);r(this,"start-tv-remote-emulator",()=>{hc(this.lg)});r(this,"start-tv-remote-tracking",()=>{this.Uf=!0;window.addEventListener("keydown",a=>{"Enter"===a.key&&l(this,"tv-remote-ok-click",!0)});window.addEventListener("keyup",a=>{"Enter"===a.key&&l(this,"tv-remote-ok-click",!1)})});this.data={Fg:!1,zg:!1,Bg:!1,Dg:!1};y(this)}La(){this.Uf&&kc(this);var b=this.pg;b.g&&l(b.s,"ysdk-server-time-update",
b.g.Eg())}});
