const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.Bullet,
		C3.Behaviors.LOS,
		C3.Behaviors.Pin,
		C3.Behaviors.Physics,
		C3.Plugins.Mouse,
		C3.Behaviors.Fade,
		C3.Plugins.Keyboard,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Behaviors.Anchor,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Behaviors.MoveTo,
		C3.Plugins.Text,
		C3.Plugins.progressbar,
		C3.Plugins.Touch,
		C3.Behaviors.Turret,
		C3.Behaviors.solid,
		C3.Behaviors.DragnDrop,
		C3.Plugins.TiledBg,
		C3.Plugins.LocalStorage,
		C3.Plugins.Dictionary,
		C3.Plugins.sliderbar,
		C3.Behaviors.Orbit,
		C3.Plugins.Browser,
		C3.Plugins.yagames_sdk,
		C3.Plugins.Button,
		C3.Plugins.CORDOVAIAP,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Dictionary.Cnds.IsEmpty,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.MoveToLayer,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetSolidCollisionFilter,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Pin.Cnds.IsPinned,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.Particles.Acts.MoveToTop,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Behaviors.Turret.Acts.SetRateOfFire,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Behaviors.EightDir.Acts.SetDeceleration,
		C3.Behaviors.EightDir.Acts.SetAcceleration,
		C3.Behaviors.EightDir.Acts.SetAllowSliding,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Physics.Acts.SetLinearDamping,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.EightDir.Cnds.IsEnabled,
		C3.Behaviors.solid.Acts.SetTags,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Behaviors.Physics.Cnds.IsEnabled,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Behaviors.Orbit.Acts.Pin,
		C3.Behaviors.Orbit.Acts.SetRadius,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.Particles.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Text.Acts.SetAngle,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Behaviors.Turret.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Turret.Cnds.HasTarget,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Behaviors.Turret.Acts.ClearTargets,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Plugins.Particles.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.yagames_sdk.Cnds.OnRewardedADRewarded,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.yagames_sdk.Cnds.OnRewardedADClose,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Physics.Acts.SetPreventRotate,
		C3.Behaviors.MoveTo.Acts.SetDeceleration,
		C3.Behaviors.MoveTo.Acts.SetAcceleration,
		C3.Behaviors.LOS.Acts.SetRange,
		C3.Behaviors.MoveTo.Acts.SetStopOnSolids,
		C3.Behaviors.LOS.Acts.ClearObstacles,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Behaviors.Sin.Acts.SetMovement,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Orbit.Acts.SetSpeed,
		C3.Behaviors.Orbit.Acts.SetAcceleration,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.Text.Cnds.IsRunningTypewriterText,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Cnds.CompareSpeed,
		C3.Plugins.Text.Acts.SetHAlign,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.yagames_sdk.Cnds.IsDesktop,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.yagames_sdk.Cnds.IsMobile
	];
};
self.C3_JsPropNameTable = [
	{fiz: 0},
	{fire: 0},
	{ice: 0},
	{acid: 0},
	{efir: 0},
	{"8Направлений": 0},
	{СледитьЗа: 0},
	{Пуля: 0},
	{ПолеЗрения: 0},
	{Прикрепить: 0},
	{ПолеЗрения2: 0},
	{Физика: 0},
	{Player: 0},
	{Мышь: 0},
	{Угасание: 0},
	{Bullet: 0},
	{Клавиатура: 0},
	{Krov: 0},
	{head: 0},
	{Аудио: 0},
	{Якорь: 0},
	{Твинанимация: 0},
	{Slot_pistols: 0},
	{slot_PP: 0},
	{Синусоид: 0},
	{Ramka: 0},
	{legs: 0},
	{Light_fire: 0},
	{Light_fire_ground: 0},
	{Частицы2: 0},
	{Поворот: 0},
	{Синусоид2: 0},
	{Gilzy: 0},
	{fon: 0},
	{slot_e: 0},
	{ДвижениеК: 0},
	{Rounds: 0},
	{ammo_pis_text: 0},
	{ammo_rifle_text: 0},
	{ammo_ark_text: 0},
	{Damage_text: 0},
	{Индикатор: 0},
	{text: 0},
	{text2: 0},
	{luchi: 0},
	{blood_spot: 0},
	{Частицы4: 0},
	{dust: 0},
	{fon_interface: 0},
	{R_1: 0},
	{r_2: 0},
	{R_3: 0},
	{R_4: 0},
	{R_5: 0},
	{tykva_loot: 0},
	{interface_button2: 0},
	{t_gold_text: 0},
	{part_skill: 0},
	{fon_okno: 0},
	{Skill_text: 0},
	{Yees: 0},
	{Noo: 0},
	{Тач: 0},
	{Pumpkinade_bottle: 0},
	{P_1: 0},
	{P_2: 0},
	{P_9: 0},
	{P_8: 0},
	{P_7: 0},
	{PP_1: 0},
	{PP_2: 0},
	{PP_3: 0},
	{PP_4: 0},
	{PP_5: 0},
	{rt: 0},
	{Damage_figure: 0},
	{Granata: 0},
	{e_1: 0},
	{e_2: 0},
	{e_3: 0},
	{e_4: 0},
	{e_5: 0},
	{s_1: 0},
	{s_2: 0},
	{s_3: 0},
	{s_4: 0},
	{s_5: 0},
	{Турель: 0},
	{Left_hand: 0},
	{Right_hand: 0},
	{ammo_rifle_zapas_text: 0},
	{ammo_ark_zapas_text: 0},
	{ammo_pis_zapas_text: 0},
	{Hp_bar_player: 0},
	{hp_line_player: 0},
	{HP_text: 0},
	{batman: 0},
	{Granata2: 0},
	{ring_granade: 0},
	{Dym_sprite: 0},
	{Частицы6: 0},
	{dym_vzryva: 0},
	{light_exp: 0},
	{granat_text: 0},
	{Granat_loot: 0},
	{Voronka: 0},
	{Твердый: 0},
	{Blocks: 0},
	{obryv: 0},
	{maket_point: 0},
	{Перетаскивание: 0},
	{joy: 0},
	{Center: 0},
	{dsgdgfs: 0},
	{dsfg: 0},
	{a: 0},
	{d: 0},
	{TArea: 0},
	{TPin: 0},
	{R: 0},
	{L: 0},
	{T: 0},
	{D: 0},
	{"45rt": 0},
	{"45rd": 0},
	{"45ld": 0},
	{"45lt": 0},
	{Z_head: 0},
	{isKry: 0},
	{Short_text: 0},
	{stamina_bar: 0},
	{piatno: 0},
	{zub: 0},
	{zuby_text: 0},
	{Bankomat: 0},
	{Tovary: 0},
	{fon_magaz: 0},
	{oto: 0},
	{fon_okno_magaz: 0},
	{Noo_mag: 0},
	{Yees_mag: 0},
	{Skill_text_mag: 0},
	{Krest_magaz: 0},
	{Duki: 0},
	{Спрайт24: 0},
	{Pochva: 0},
	{green_water_tail: 0},
	{Metka: 0},
	{Vsplesk: 0},
	{Plity: 0},
	{fon_part: 0},
	{nik_part: 0},
	{Spawner: 0},
	{Спрайт29: 0},
	{save1: 0},
	{Slovar: 0},
	{podplita1: 0},
	{Aim_left: 0},
	{HP: 0},
	{speed: 0},
	{Синусоида: 0},
	{Синусоида2: 0},
	{Z: 0},
	{z_text: 0},
	{z_line: 0},
	{flash_bar: 0},
	{pp_fire: 0},
	{props_graves: 0},
	{props_graves_2: 0},
	{Спрайт33: 0},
	{Pochva2: 0},
	{Спрайт34: 0},
	{tree2: 0},
	{tree3: 0},
	{Listya: 0},
	{listva: 0},
	{Gates: 0},
	{Weapon_loot: 0},
	{fon_change: 0},
	{Krest_change1: 0},
	{icon_change: 0},
	{icon_change2: 0},
	{Weapon_text: 0},
	{Weapon_text2: 0},
	{Krest_change2: 0},
	{flame: 0},
	{Damage_figure_fire: 0},
	{svechenie: 0},
	{Dym_part: 0},
	{Acid_part: 0},
	{Acid_cube: 0},
	{Damage_figure_acid: 0},
	{Ice_cube: 0},
	{Ice_part: 0},
	{Damage_figure_ice: 0},
	{Damage_figure_efir: 0},
	{z_burn: 0},
	{Ice_cube222: 0},
	{Ползунок: 0},
	{Kuski_lda: 0},
	{Kusok_lda: 0},
	{snejinki_vystrel: 0},
	{info_okno: 0},
	{info_text: 0},
	{acid_spray_part: 0},
	{fire_cube: 0},
	{Kolco_lda: 0},
	{snejinki_kolco: 0},
	{oskolki_lda: 0},
	{Угасание2: 0},
	{sosulka: 0},
	{Popadaniya: 0},
	{Krov_potok: 0},
	{Light_fire2: 0},
	{Спрайт42: 0},
	{ded: 0},
	{Спрайт41: 0},
	{Спрайт38: 0},
	{d_ded: 0},
	{dialog_window: 0},
	{krest_Dialog: 0},
	{d1: 0},
	{d2: 0},
	{d3: 0},
	{d_migalka: 0},
	{life_time: 0},
	{Орбита: 0},
	{pila: 0},
	{pila_ten: 0},
	{Krov_potok_big: 0},
	{tykva: 0},
	{mech: 0},
	{Sharik1: 0},
	{luch_ruletka: 0},
	{Sharik2: 0},
	{Sharik3: 0},
	{Sharik4: 0},
	{Sharik5: 0},
	{Sharik6: 0},
	{Sharik7: 0},
	{Sharik8: 0},
	{Sharik9: 0},
	{Sharik10: 0},
	{povodyr: 0},
	{fon_ruletka: 0},
	{pult_legendary: 0},
	{krest_ruletka: 0},
	{da_ruletka: 0},
	{pult_blue: 0},
	{pult_epic: 0},
	{Спрайт43: 0},
	{пыльНовая: 0},
	{kuski_tykvy: 0},
	{tykva_pyl: 0},
	{tykva_pyl2: 0},
	{loot_banner: 0},
	{reward_baner: 0},
	{kills: 0},
	{GC: 0},
	{reward_monster_icon: 0},
	{reward_kills_text: 0},
	{reward_icon: 0},
	{reward_text: 0},
	{reward_count_kills_text: 0},
	{Blood_brizgi: 0},
	{blood_pyl: 0},
	{kuski_ice: 0},
	{white_cube: 0},
	{stamina_line: 0},
	{P_3: 0},
	{P_4: 0},
	{P_5: 0},
	{P_6: 0},
	{s_6: 0},
	{s_7: 0},
	{s_8: 0},
	{s_9: 0},
	{t_green_text: 0},
	{t_blue_text: 0},
	{t_glass_text: 0},
	{t_demon_text: 0},
	{Light_skill: 0},
	{zuby_text2: 0},
	{icon_dubler: 0},
	{udar_button: 0},
	{ryvok_button: 0},
	{udar_fire: 0},
	{sparks: 0},
	{sparks2: 0},
	{ice_siluet: 0},
	{udar_bullet: 0},
	{acid_2: 0},
	{acid_ring: 0},
	{ring_exp_acid: 0},
	{acid_light: 0},
	{kusok_ice_z1: 0},
	{laser_luch_R: 0},
	{iskry_tech: 0},
	{efir_Light: 0},
	{spawner_cube_l: 0},
	{weapon_flash: 0},
	{Dym_laser: 0},
	{Спрайт: 0},
	{Спрайт3: 0},
	{oval_ataki: 0},
	{chraracters_portraits: 0},
	{dialog_button_fon: 0},
	{dialog_button: 0},
	{Tovary2: 0},
	{loot_text: 0},
	{Glaz: 0},
	{blik_glaza: 0},
	{stamina_text: 0},
	{blesk: 0},
	{Спрайт40: 0},
	{Blocks3: 0},
	{rain_drops: 0},
	{rain_drops2: 0},
	{spawner_cube_r: 0},
	{spawner_cube_t: 0},
	{spawner_cube_b: 0},
	{spawner_area: 0},
	{temnota: 0},
	{Спрайт5: 0},
	{quest_info: 0},
	{strelka: 0},
	{strelka_weapon: 0},
	{sofa: 0},
	{Pyl: 0},
	{Block_special: 0},
	{Спрайт9: 0},
	{Спрайт10: 0},
	{hand_sofa_l: 0},
	{hand_sofa_l2: 0},
	{Rychag: 0},
	{portal_base: 0},
	{portal: 0},
	{kick_icon: 0},
	{Частицы10: 0},
	{Спрайт11: 0},
	{Спрайт12: 0},
	{spawn_circle: 0},
	{ruki_hlopayut: 0},
	{Спрайт13: 0},
	{Спрайт14: 0},
	{Частицы12: 0},
	{Спрайт15: 0},
	{robo: 0},
	{robo_text: 0},
	{robo_line: 0},
	{tech_bar: 0},
	{robo_head: 0},
	{tech_death_part: 0},
	{iskry_potok: 0},
	{kusok_ice_robo: 0},
	{Bullet_e: 0},
	{Ice_part_vystrel: 0},
	{Acid_cloud: 0},
	{ice_cloud: 0},
	{sneg_cloud: 0},
	{fire_shot: 0},
	{fire_shot_yellow: 0},
	{acid_shot: 0},
	{acid_shot_yellow: 0},
	{pila_fire: 0},
	{fire_sparks: 0},
	{acid_light_shot: 0},
	{laser_part: 0},
	{svechenie_laser_R: 0},
	{svechenie_laser_L: 0},
	{laser_luch_L: 0},
	{laser_parts_pop_R: 0},
	{laser_parts_pop_L: 0},
	{blue_light_shoot: 0},
	{sosulka_s_neba: 0},
	{oskolki_tenb: 0},
	{Kolco_lda_mini: 0},
	{Kolco_ognia: 0},
	{meteor_s_neba: 0},
	{oskolki_kamnia: 0},
	{Частицы: 0},
	{Tail_4: 0},
	{Trees4: 0},
	{fire_stones: 0},
	{ogonek: 0},
	{Trees6: 0},
	{Спрайт7: 0},
	{ice_stones: 0},
	{kusok_ice_zvuk: 0},
	{snejinki_death: 0},
	{kusok_ice_z2: 0},
	{kusok_ice_robo2: 0},
	{rain_sparks: 0},
	{Light_ground_lantern: 0},
	{Спрайт8: 0},
	{Спрайт19: 0},
	{Спрайт20: 0},
	{Спрайт21: 0},
	{s1: 0},
	{s2: 0},
	{s3: 0},
	{heal_sparks: 0},
	{flesh_popadanie: 0},
	{tech_popadanie: 0},
	{fire_shoot: 0},
	{efir_light_shoot: 0},
	{puzyr: 0},
	{vsplesk_puz: 0},
	{Z_fire: 0},
	{Z_fire_head: 0},
	{z_fire_line: 0},
	{z_fire_text: 0},
	{fire_bar: 0},
	{kusok_ice_z_fire: 0},
	{kusok_ice_z_fire2: 0},
	{Спрайт16: 0},
	{barrels: 0},
	{Ring_fire_barrel: 0},
	{Спрайт17: 0},
	{vzryvatel: 0},
	{Ring_ice_barrel: 0},
	{Ring_ice_barrel2: 0},
	{Ring_ice_barrel3: 0},
	{vsplesk_acid: 0},
	{vsplesk_efir: 0},
	{efir_smoke: 0},
	{light_exp2: 0},
	{udar_pulia: 0},
	{Спрайт22: 0},
	{effect_udara: 0},
	{z1_kusok: 0},
	{z_fire_kusok: 0},
	{robo_kusok: 0},
	{kills_og: 0},
	{kills_kis: 0},
	{kills_hol: 0},
	{ice_ghoul: 0},
	{Z_acid: 0},
	{Z_ice_head: 0},
	{z_ice_text: 0},
	{z_ice_line: 0},
	{ice_bar: 0},
	{kusok_ice_z_ice: 0},
	{kusok_ice_z_ice2: 0},
	{z_ice_kusok: 0},
	{Z_acid_head: 0},
	{z_acid_text: 0},
	{z_acid_line: 0},
	{acid_bar: 0},
	{kusok_acid: 0},
	{kusok_acid2: 0},
	{z_acid_kusok: 0},
	{shoot: 0},
	{Z_efir: 0},
	{z_efir_text: 0},
	{z_efir_line: 0},
	{efir_bar: 0},
	{Z_efir_head: 0},
	{kusok_efir: 0},
	{kusok_efir2: 0},
	{z_efir_kusok: 0},
	{D_player: 0},
	{D_player_fire: 0},
	{D_player_acid: 0},
	{D_player_ice: 0},
	{D_player_efir: 0},
	{tykva_sparks: 0},
	{snow_sparks: 0},
	{Dym_part_for_fire: 0},
	{Dym_red_for_fire: 0},
	{lantern: 0},
	{vorona: 0},
	{vorona_spawner: 0},
	{perya: 0},
	{vorona_krov: 0},
	{acid_props: 0},
	{ТайловыйФон: 0},
	{Частицы7: 0},
	{motor: 0},
	{porshen: 0},
	{acid_spray_little: 0},
	{pero: 0},
	{strelki: 0},
	{ТайловыйФон2: 0},
	{Pochva3: 0},
	{gorod_props: 0},
	{oskolki_lda2: 0},
	{lift: 0},
	{Спрайт23: 0},
	{lift_mark: 0},
	{lift_point: 0},
	{lift_sparks: 0},
	{Plity2: 0},
	{efir_sparks: 0},
	{ef_part: 0},
	{Z_2: 0},
	{Z_head2: 0},
	{z_2_text: 0},
	{z_2_line: 0},
	{kusok_ice_z22: 0},
	{kusok2_ice_z_22: 0},
	{z2_kusok: 0},
	{hand_throw: 0},
	{Частицы8: 0},
	{Частицы9: 0},
	{lesnik: 0},
	{jug1_head: 0},
	{jug1_text: 0},
	{jug1_line: 0},
	{"1_kusok_ice_Jug1": 0},
	{"1_kusok_ice_Jug2": 0},
	{jug1_kusok: 0},
	{vzmah_topora: 0},
	{snejok: 0},
	{ice2_head: 0},
	{ice2_text: 0},
	{ice2_line: 0},
	{kusok_ice2_1: 0},
	{ice2_kusok: 0},
	{kusok_ice2_2: 0},
	{snowball: 0},
	{Buran: 0},
	{buran_head: 0},
	{buran_text: 0},
	{buran_line: 0},
	{kusok_buran_1: 0},
	{buran_kusok: 0},
	{kusok_buran_2: 0},
	{ice_spear: 0},
	{Ice_cube_player22: 0},
	{Ice_cube_player: 0},
	{snejinki_kolco2: 0},
	{cyber: 0},
	{cyber_head: 0},
	{cyber_text: 0},
	{cyber_line: 0},
	{kusok_cyber1: 0},
	{cyber_kusok: 0},
	{kusok_cyber2: 0},
	{laser_bullet: 0},
	{circ: 0},
	{circ_saw: 0},
	{pila_ten222: 0},
	{circ_part: 0},
	{circ_head: 0},
	{circ_text: 0},
	{circ_line: 0},
	{kusok_ice_circ1: 0},
	{circ_kusok: 0},
	{kusok_ice_circ2: 0},
	{Gnil: 0},
	{Gnil_text: 0},
	{Gnil_line: 0},
	{kusok_Gnil1: 0},
	{Gnil_kusok: 0},
	{kusok_Gnil2: 0},
	{Gnil_head: 0},
	{pump_throw: 0},
	{pump_throw222: 0},
	{Спрайт18: 0},
	{pump_circl: 0},
	{tykva_pyl_effect: 0},
	{zajigalka: 0},
	{zaj_text: 0},
	{zaj_line: 0},
	{kusok_ice_zaj1: 0},
	{zaj_kusok: 0},
	{kusok_ice_zaj2: 0},
	{zaj_head: 0},
	{zaj_throw: 0},
	{fire_ring: 0},
	{ognevik: 0},
	{og_head: 0},
	{og_text: 0},
	{og_line: 0},
	{kusok_ice_og1: 0},
	{og_kusok: 0},
	{kusok_ice_og2: 0},
	{og_throw: 0},
	{sparks3: 0},
	{Dem: 0},
	{Dem_mini: 0},
	{dem_head: 0},
	{dem_text: 0},
	{kusok_ice_dem1: 0},
	{dem_kusok: 0},
	{kusok_ice_dem2: 0},
	{dem_line: 0},
	{dem_luch: 0},
	{svechenie_dem: 0},
	{dem_mini_circl: 0},
	{Storoj: 0},
	{stor_head: 0},
	{stor_text: 0},
	{stor_line: 0},
	{kusok_ice_stor1: 0},
	{stor_kusok: 0},
	{kusok_ice_stor2: 0},
	{oil_brizgi: 0},
	{birn1: 0},
	{birn2: 0},
	{oval_ataki_2: 0},
	{Lich: 0},
	{lich_head: 0},
	{lich_text: 0},
	{lich_line: 0},
	{lich_spear: 0},
	{kusok_lich1: 0},
	{lich_kusok: 0},
	{kusok_lich2: 0},
	{rad: 0},
	{ice_head: 0},
	{plevun: 0},
	{ple_text: 0},
	{ple_line: 0},
	{kusok_ple1: 0},
	{ple_kusok: 0},
	{kusok_ple2: 0},
	{ple_head: 0},
	{plevok: 0},
	{kislyi: 0},
	{kis_head: 0},
	{kis_text: 0},
	{kis_line: 0},
	{kusok_kis1: 0},
	{kis_kusok: 0},
	{kusok_kis2: 0},
	{kis_spear: 0},
	{poison_circl: 0},
	{Acid_cloud2: 0},
	{acid_cube_player: 0},
	{Saya: 0},
	{saya_head: 0},
	{kusok_saya1: 0},
	{saya_kusok: 0},
	{kusok_saya2: 0},
	{ef_spear: 0},
	{Efirness: 0},
	{efi_head: 0},
	{efi_text: 0},
	{efi_line: 0},
	{kusok_efi1: 0},
	{efi_kusok: 0},
	{kusok_efi2: 0},
	{efi_spear: 0},
	{efir_spray_shoot: 0},
	{sa_text: 0},
	{sa_line: 0},
	{nevesta: 0},
	{nev_head: 0},
	{nev_text: 0},
	{nev_line: 0},
	{nev_spear: 0},
	{kusok_nev1: 0},
	{nev_kusok: 0},
	{kusok_nev2: 0},
	{nev_circl: 0},
	{nev_fly_head: 0},
	{Krov_potok2: 0},
	{nev_kiss: 0},
	{efir_popadanie: 0},
	{Ryglo: 0},
	{ryg_text: 0},
	{ryg_line: 0},
	{ryg_head: 0},
	{kusok_ryg1: 0},
	{ryg_kusok: 0},
	{kusok_ryg2: 0},
	{acid_brizgi: 0},
	{birn3: 0},
	{acid_spray_part2: 0},
	{ryg_circl: 0},
	{acid_popadanie: 0},
	{iskry_znak: 0},
	{spawn_spawn: 0},
	{fire_popadanie: 0},
	{Словарь: 0},
	{Браузер: 0},
	{death_text: 0},
	{button_reward: 0},
	{butt_2: 0},
	{button_text: 0},
	{Resurrect_base: 0},
	{ott_circl: 0},
	{spawn_player: 0},
	{pyl_nogi: 0},
	{quests_point: 0},
	{tykva_ruletka: 0},
	{pult_circle: 0},
	{Plita_ruletka1: 0},
	{Plita_ruletka2: 0},
	{Plita_ruletka3: 0},
	{podplita2: 0},
	{podplita3: 0},
	{kick_icon222: 0},
	{YandexGamesSDK: 0},
	{train_props: 0},
	{comment_trig: 0},
	{train_images: 0},
	{Текст: 0},
	{train_text: 0},
	{quest_text: 0},
	{train_znak: 0},
	{podlojka: 0},
	{train_part: 0},
	{zas: 0},
	{Спрайт6: 0},
	{p: 0},
	{knopka: 0},
	{f1: 0},
	{f2: 0},
	{zvezda: 0},
	{p2: 0},
	{centr: 0},
	{zas2: 0},
	{zas3: 0},
	{zvezda2: 0},
	{zvezda3: 0},
	{p3: 0},
	{zas4: 0},
	{bel: 0},
	{bel2: 0},
	{Спрайт25: 0},
	{shit: 0},
	{sh: 0},
	{Спрайт2: 0},
	{portal_boss: 0},
	{portal_boss2: 0},
	{Спрайт26: 0},
	{o: 0},
	{Plity3: 0},
	{Спрайт27: 0},
	{logo: 0},
	{Listya2: 0},
	{butt_3: 0},
	{ПокупкиВПриложенияхIAP: 0},
	{kurs: 0},
	{blood_navylet: 0},
	{icon3: 0},
	{shit_infa: 0},
	{shit_strelki: 0},
	{kills_boss: 0},
	{boss_point: 0},
	{che: 0},
	{Спрайт28: 0},
	{shans: 0},
	{s_10: 0},
	{Listya3: 0},
	{stih: 0},
	{Gates2: 0},
	{ammo_ark_text2: 0},
	{runs: 0},
	{info_reklama_okno: 0},
	{info_text_reklama: 0},
	{"8Направлений2": 0},
	{Enemies: 0},
	{Icons: 0},
	{Player_parts: 0},
	{loot: 0},
	{Interface: 0},
	{text_family: 0},
	{parts_1: 0},
	{Shariki: 0},
	{Cubes_stihii: 0},
	{skill_icons: 0},
	{strelki_joy: 0},
	{magaz_objects: 0},
	{props: 0},
	{Bloks: 0},
	{cubes_spawn: 0},
	{Tech_enemy: 0},
	{Flesh_enemy: 0},
	{lasers: 0},
	{laser_parts: 0},
	{Cifry_urona: 0},
	{Rains: 0},
	{acid_enemy: 0},
	{fire_enemy: 0},
	{ice_enemy: 0},
	{efir_enemy: 0},
	{Физика2: 0},
	{heads: 0},
	{lines: 0},
	{Delete: 0},
	{Delete2: 0},
	{Delete3: 0},
	{Delete4: 0},
	{interface_2: 0},
	{rev_ammo: 0},
	{Rev_ammo_zapas: 0},
	{rev_speed_base: 0},
	{rev_speed: 0},
	{rev_base_damage: 0},
	{rev_damage: 0},
	{rev_razbros_base: 0},
	{rev_razbros: 0},
	{rev_1: 0},
	{r_save: 0},
	{pp_ammo: 0},
	{pp_ammo_zapas: 0},
	{pp_base_speed: 0},
	{pp_speed: 0},
	{pp_base_damage: 0},
	{pp_damage: 0},
	{pp_razbros_base: 0},
	{pp_razbros: 0},
	{pp_1: 0},
	{pp_save: 0},
	{e_ammo: 0},
	{e_ammo_zapas: 0},
	{e_speed: 0},
	{e_base_speed: 0},
	{e_damage: 0},
	{e_base_damage: 0},
	{e_save: 0},
	{Granat_damage: 0},
	{granat_current: 0},
	{Granat_max: 0},
	{Granat_acid_damage: 0},
	{fire_damage: 0},
	{ice_damage: 0},
	{Acid_damage: 0},
	{efir_damage: 0},
	{fire_long: 0},
	{ice_long: 0},
	{acid_long: 0},
	{PP_number: 0},
	{SG_number: 0},
	{e_number: 0},
	{loot_chans: 0},
	{Shans_vozgoraniya: 0},
	{Shans_effekta: 0},
	{hp_player_current: 0},
	{hp_player_max: 0},
	{player_speed: 0},
	{vidimost_igroka: 0},
	{death: 0},
	{stamina_current: 0},
	{stamina_max: 0},
	{stamina_regen: 0},
	{stamina_udar: 0},
	{stamina_ryvok: 0},
	{otbros_power: 0},
	{udar_damage: 0},
	{udar_impuls: 0},
	{udar_fire_damage: 0},
	{ryvok_speed: 0},
	{ryvok_ice_damage: 0},
	{acid_damage_player: 0},
	{acid_long_player: 0},
	{ice_long_player: 0},
	{zuby: 0},
	{t_gold: 0},
	{t_green: 0},
	{t_blue: 0},
	{t_glass: 0},
	{t_demon: 0},
	{quests: 0},
	{maket: 0},
	{RusEng: 0},
	{ruletka_blue: 0},
	{ruletka_epic: 0},
	{ruletka_legend: 0},
	{ruletka_shar: 0},
	{tip_puli: 0},
	{Lut_z: 0},
	{Lut_b: 0},
	{cost: 0},
	{train: 0},
	{start: 0},
	{uron_efiru: 0},
	{ramka_weapon: 0},
	{z1_kills: 0},
	{robo_kills: 0},
	{z_fire_kills: 0},
	{z_ice_kills: 0},
	{z_acid_kills: 0},
	{z_efir_kills: 0},
	{z_2_kills: 0},
	{ice2_kills: 0},
	{cyber_kills: 0},
	{zaj_kills: 0},
	{saya_kills: 0},
	{ple_kills: 0},
	{jug1_kills: 0},
	{buran_kills: 0},
	{Gnil_kills: 0},
	{og_kills: 0},
	{efi_kills: 0},
	{kis_kills: 0},
	{dem_kills: 0},
	{dem_achiev: 0},
	{stor_kills: 0},
	{stor_achiev: 0},
	{lich_kills: 0},
	{lich_achiev: 0},
	{saw_timer: 0},
	{circ_achiev: 0},
	{circ_kills: 0},
	{nev_kills: 0},
	{nev_achiev: 0},
	{ryg_achiev: 0},
	{ryg_kills: 0},
	{spawn_meele: 0},
	{spawn_range: 0},
	{spawn_juger: 0},
	{meele_hp: 0},
	{meele_damage: 0},
	{meele_speed: 0},
	{range_hp: 0},
	{range_damage: 0},
	{range_speed: 0},
	{boss_hp: 0},
	{jug_hp: 0},
	{boss_kills: 0},
	{fire_kills: 0},
	{acid_kills: 0},
	{ice_kills: 0},
	{p1: 0},
	{p4: 0},
	{p5: 0},
	{p6: 0},
	{p7: 0},
	{p8: 0},
	{p9: 0},
	{r1: 0},
	{r2: 0},
	{r3: 0},
	{r4: 0},
	{r5: 0},
	{pp1: 0},
	{pp2: 0},
	{pp3: 0},
	{pp4: 0},
	{pp5: 0},
	{e1: 0},
	{e2: 0},
	{e3: 0},
	{e4: 0},
	{e5: 0},
	{s4: 0},
	{s5: 0},
	{s6: 0},
	{s7: 0},
	{s8: 0},
	{s9: 0},
	{s10: 0},
	{s11: 0},
	{shar_b4: 0},
	{shar_b5: 0},
	{shar_b6: 0},
	{shar_b7: 0},
	{shar_b8: 0},
	{shar_e3: 0},
	{shar_e4: 0},
	{shar_e5: 0},
	{shar_e6: 0},
	{shar_e7: 0},
	{shar_e8: 0},
	{shar_e9: 0},
	{shar_l1: 0},
	{shar_l2: 0},
	{shar_l3: 0},
	{shar_l4: 0},
	{shar_l5: 0},
	{shar_l6: 0},
	{shar_l7: 0},
	{shar_l8: 0},
	{shar_l9: 0},
	{shar_l10: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Клавиатура: class extends self.IInstance {},
	Krov: class extends self.IParticlesInstance {},
	head: class extends self.ISpriteInstance {},
	Аудио: class extends self.IInstance {},
	Slot_pistols: class extends self.ISpriteInstance {},
	slot_PP: class extends self.ISpriteInstance {},
	Ramka: class extends self.ISpriteInstance {},
	legs: class extends self.ISpriteInstance {},
	Light_fire: class extends self.ISpriteInstance {},
	Light_fire_ground: class extends self.ISpriteInstance {},
	Частицы2: class extends self.IParticlesInstance {},
	Gilzy: class extends self.ISpriteInstance {},
	fon: class extends self.ISpriteInstance {},
	slot_e: class extends self.ISpriteInstance {},
	Rounds: class extends self.ISpriteInstance {},
	ammo_pis_text: class extends self.ITextInstance {},
	ammo_rifle_text: class extends self.ITextInstance {},
	ammo_ark_text: class extends self.ITextInstance {},
	Damage_text: class extends self.ITextInstance {},
	Индикатор: class extends self.IProgressBarInstance {},
	text: class extends self.ITextInstance {},
	text2: class extends self.ITextInstance {},
	luchi: class extends self.ISpriteInstance {},
	blood_spot: class extends self.ISpriteInstance {},
	Частицы4: class extends self.IParticlesInstance {},
	dust: class extends self.IParticlesInstance {},
	fon_interface: class extends self.ISpriteInstance {},
	R_1: class extends self.ISpriteInstance {},
	r_2: class extends self.ISpriteInstance {},
	R_3: class extends self.ISpriteInstance {},
	R_4: class extends self.ISpriteInstance {},
	R_5: class extends self.ISpriteInstance {},
	tykva_loot: class extends self.ISpriteInstance {},
	interface_button2: class extends self.ISpriteInstance {},
	t_gold_text: class extends self.ITextInstance {},
	part_skill: class extends self.IParticlesInstance {},
	fon_okno: class extends self.ISpriteInstance {},
	Skill_text: class extends self.ITextInstance {},
	Yees: class extends self.ISpriteInstance {},
	Noo: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	Pumpkinade_bottle: class extends self.ISpriteInstance {},
	P_1: class extends self.ISpriteInstance {},
	P_2: class extends self.ISpriteInstance {},
	P_9: class extends self.ISpriteInstance {},
	P_8: class extends self.ISpriteInstance {},
	P_7: class extends self.ISpriteInstance {},
	PP_1: class extends self.ISpriteInstance {},
	PP_2: class extends self.ISpriteInstance {},
	PP_3: class extends self.ISpriteInstance {},
	PP_4: class extends self.ISpriteInstance {},
	PP_5: class extends self.ISpriteInstance {},
	rt: class extends self.ISpriteInstance {},
	Damage_figure: class extends self.ITextInstance {},
	Granata: class extends self.ISpriteInstance {},
	e_1: class extends self.ISpriteInstance {},
	e_2: class extends self.ISpriteInstance {},
	e_3: class extends self.ISpriteInstance {},
	e_4: class extends self.ISpriteInstance {},
	e_5: class extends self.ISpriteInstance {},
	s_1: class extends self.ISpriteInstance {},
	s_2: class extends self.ISpriteInstance {},
	s_3: class extends self.ISpriteInstance {},
	s_4: class extends self.ISpriteInstance {},
	s_5: class extends self.ISpriteInstance {},
	Left_hand: class extends self.ISpriteInstance {},
	Right_hand: class extends self.ISpriteInstance {},
	ammo_rifle_zapas_text: class extends self.ITextInstance {},
	ammo_ark_zapas_text: class extends self.ITextInstance {},
	ammo_pis_zapas_text: class extends self.ITextInstance {},
	Hp_bar_player: class extends self.ISpriteInstance {},
	hp_line_player: class extends self.ISpriteInstance {},
	HP_text: class extends self.ITextInstance {},
	batman: class extends self.ISpriteInstance {},
	Granata2: class extends self.ISpriteInstance {},
	ring_granade: class extends self.ISpriteInstance {},
	Dym_sprite: class extends self.ISpriteInstance {},
	Частицы6: class extends self.IParticlesInstance {},
	dym_vzryva: class extends self.IParticlesInstance {},
	light_exp: class extends self.ISpriteInstance {},
	granat_text: class extends self.ITextInstance {},
	Granat_loot: class extends self.ISpriteInstance {},
	Voronka: class extends self.ISpriteInstance {},
	Blocks: class extends self.ISpriteInstance {},
	obryv: class extends self.ISpriteInstance {},
	maket_point: class extends self.ISpriteInstance {},
	joy: class extends self.ISpriteInstance {},
	Center: class extends self.ISpriteInstance {},
	dsgdgfs: class extends self.ISpriteInstance {},
	dsfg: class extends self.ISpriteInstance {},
	TArea: class extends self.ISpriteInstance {},
	TPin: class extends self.ISpriteInstance {},
	R: class extends self.ISpriteInstance {},
	L: class extends self.ISpriteInstance {},
	T: class extends self.ISpriteInstance {},
	D: class extends self.ISpriteInstance {},
	_45rt: class extends self.ISpriteInstance {},
	_45rd: class extends self.ISpriteInstance {},
	_45ld: class extends self.ISpriteInstance {},
	_45lt: class extends self.ISpriteInstance {},
	Z_head: class extends self.ISpriteInstance {},
	isKry: class extends self.IParticlesInstance {},
	Short_text: class extends self.ITextInstance {},
	stamina_bar: class extends self.ISpriteInstance {},
	piatno: class extends self.ISpriteInstance {},
	zub: class extends self.ISpriteInstance {},
	zuby_text: class extends self.ITextInstance {},
	Bankomat: class extends self.ISpriteInstance {},
	Tovary: class extends self.ISpriteInstance {},
	fon_magaz: class extends self.ISpriteInstance {},
	fon_okno_magaz: class extends self.ISpriteInstance {},
	Noo_mag: class extends self.ISpriteInstance {},
	Yees_mag: class extends self.ISpriteInstance {},
	Skill_text_mag: class extends self.ITextInstance {},
	Krest_magaz: class extends self.ISpriteInstance {},
	Duki: class extends self.ISpriteInstance {},
	Спрайт24: class extends self.ISpriteInstance {},
	Pochva: class extends self.ISpriteInstance {},
	green_water_tail: class extends self.ITiledBackgroundInstance {},
	Metka: class extends self.ISpriteInstance {},
	Vsplesk: class extends self.ISpriteInstance {},
	Plity: class extends self.ISpriteInstance {},
	fon_part: class extends self.IParticlesInstance {},
	nik_part: class extends self.IParticlesInstance {},
	Spawner: class extends self.ISpriteInstance {},
	Спрайт29: class extends self.ISpriteInstance {},
	save1: class extends self.IInstance {},
	Slovar: class extends self.IDictionaryInstance {},
	podplita1: class extends self.ISpriteInstance {},
	Aim_left: class extends self.ISpriteInstance {},
	Z: class extends self.ISpriteInstance {},
	z_text: class extends self.ITextInstance {},
	z_line: class extends self.ISpriteInstance {},
	flash_bar: class extends self.ISpriteInstance {},
	pp_fire: class extends self.ISpriteInstance {},
	props_graves: class extends self.ISpriteInstance {},
	props_graves_2: class extends self.ISpriteInstance {},
	Спрайт33: class extends self.ISpriteInstance {},
	Pochva2: class extends self.ISpriteInstance {},
	Спрайт34: class extends self.ISpriteInstance {},
	tree2: class extends self.ISpriteInstance {},
	tree3: class extends self.ISpriteInstance {},
	Listya: class extends self.ISpriteInstance {},
	listva: class extends self.ISpriteInstance {},
	Gates: class extends self.ISpriteInstance {},
	Weapon_loot: class extends self.ISpriteInstance {},
	fon_change: class extends self.ISpriteInstance {},
	Krest_change1: class extends self.ISpriteInstance {},
	icon_change: class extends self.ISpriteInstance {},
	icon_change2: class extends self.ISpriteInstance {},
	Weapon_text: class extends self.ITextInstance {},
	Weapon_text2: class extends self.ITextInstance {},
	Krest_change2: class extends self.ISpriteInstance {},
	flame: class extends self.ISpriteInstance {},
	Damage_figure_fire: class extends self.ITextInstance {},
	svechenie: class extends self.ISpriteInstance {},
	Dym_part: class extends self.IParticlesInstance {},
	Acid_part: class extends self.IParticlesInstance {},
	Acid_cube: class extends self.ISpriteInstance {},
	Damage_figure_acid: class extends self.ITextInstance {},
	Ice_cube: class extends self.ISpriteInstance {},
	Ice_part: class extends self.IParticlesInstance {},
	Damage_figure_ice: class extends self.ITextInstance {},
	Damage_figure_efir: class extends self.ITextInstance {},
	z_burn: class extends self.ISpriteInstance {},
	Ice_cube222: class extends self.ISpriteInstance {},
	Ползунок: class extends self.ISliderBarInstance {},
	Kuski_lda: class extends self.IParticlesInstance {},
	Kusok_lda: class extends self.ISpriteInstance {},
	snejinki_vystrel: class extends self.IParticlesInstance {},
	info_okno: class extends self.ISpriteInstance {},
	info_text: class extends self.ITextInstance {},
	acid_spray_part: class extends self.IParticlesInstance {},
	fire_cube: class extends self.ISpriteInstance {},
	Kolco_lda: class extends self.ISpriteInstance {},
	snejinki_kolco: class extends self.IParticlesInstance {},
	oskolki_lda: class extends self.IParticlesInstance {},
	sosulka: class extends self.ISpriteInstance {},
	Popadaniya: class extends self.ISpriteInstance {},
	Krov_potok: class extends self.IParticlesInstance {},
	Light_fire2: class extends self.ISpriteInstance {},
	Спрайт42: class extends self.ISpriteInstance {},
	ded: class extends self.ISpriteInstance {},
	Спрайт41: class extends self.ISpriteInstance {},
	Спрайт38: class extends self.ISpriteInstance {},
	d_ded: class extends self.ITextInstance {},
	dialog_window: class extends self.ISpriteInstance {},
	krest_Dialog: class extends self.ISpriteInstance {},
	d1: class extends self.ITextInstance {},
	d2: class extends self.ITextInstance {},
	d3: class extends self.ITextInstance {},
	d_migalka: class extends self.ISpriteInstance {},
	pila: class extends self.ISpriteInstance {},
	pila_ten: class extends self.ISpriteInstance {},
	Krov_potok_big: class extends self.IParticlesInstance {},
	tykva: class extends self.ISpriteInstance {},
	mech: class extends self.ISpriteInstance {},
	Sharik1: class extends self.ISpriteInstance {},
	luch_ruletka: class extends self.ISpriteInstance {},
	Sharik2: class extends self.ISpriteInstance {},
	Sharik3: class extends self.ISpriteInstance {},
	Sharik4: class extends self.ISpriteInstance {},
	Sharik5: class extends self.ISpriteInstance {},
	Sharik6: class extends self.ISpriteInstance {},
	Sharik7: class extends self.ISpriteInstance {},
	Sharik8: class extends self.ISpriteInstance {},
	Sharik9: class extends self.ISpriteInstance {},
	Sharik10: class extends self.ISpriteInstance {},
	povodyr: class extends self.ISpriteInstance {},
	fon_ruletka: class extends self.ISpriteInstance {},
	pult_legendary: class extends self.ISpriteInstance {},
	krest_ruletka: class extends self.ISpriteInstance {},
	da_ruletka: class extends self.ISpriteInstance {},
	pult_blue: class extends self.ISpriteInstance {},
	pult_epic: class extends self.ISpriteInstance {},
	Спрайт43: class extends self.ISpriteInstance {},
	пыльНовая: class extends self.IParticlesInstance {},
	kuski_tykvy: class extends self.ISpriteInstance {},
	tykva_pyl: class extends self.IParticlesInstance {},
	tykva_pyl2: class extends self.IParticlesInstance {},
	loot_banner: class extends self.ISpriteInstance {},
	reward_baner: class extends self.ISpriteInstance {},
	kills: class extends self.ITextInstance {},
	GC: class extends self.ISpriteInstance {},
	reward_monster_icon: class extends self.ISpriteInstance {},
	reward_kills_text: class extends self.ITextInstance {},
	reward_icon: class extends self.ISpriteInstance {},
	reward_text: class extends self.ITextInstance {},
	reward_count_kills_text: class extends self.ITextInstance {},
	Blood_brizgi: class extends self.ISpriteInstance {},
	blood_pyl: class extends self.IParticlesInstance {},
	kuski_ice: class extends self.ISpriteInstance {},
	white_cube: class extends self.ISpriteInstance {},
	stamina_line: class extends self.ISpriteInstance {},
	P_3: class extends self.ISpriteInstance {},
	P_4: class extends self.ISpriteInstance {},
	P_5: class extends self.ISpriteInstance {},
	P_6: class extends self.ISpriteInstance {},
	s_6: class extends self.ISpriteInstance {},
	s_7: class extends self.ISpriteInstance {},
	s_8: class extends self.ISpriteInstance {},
	s_9: class extends self.ISpriteInstance {},
	t_green_text: class extends self.ITextInstance {},
	t_blue_text: class extends self.ITextInstance {},
	t_glass_text: class extends self.ITextInstance {},
	t_demon_text: class extends self.ITextInstance {},
	Light_skill: class extends self.ISpriteInstance {},
	zuby_text2: class extends self.ITextInstance {},
	icon_dubler: class extends self.ISpriteInstance {},
	udar_button: class extends self.ISpriteInstance {},
	ryvok_button: class extends self.ISpriteInstance {},
	udar_fire: class extends self.ISpriteInstance {},
	sparks: class extends self.IParticlesInstance {},
	sparks2: class extends self.IParticlesInstance {},
	ice_siluet: class extends self.ISpriteInstance {},
	udar_bullet: class extends self.ISpriteInstance {},
	acid_2: class extends self.IParticlesInstance {},
	acid_ring: class extends self.IParticlesInstance {},
	ring_exp_acid: class extends self.ISpriteInstance {},
	acid_light: class extends self.ISpriteInstance {},
	kusok_ice_z1: class extends self.ISpriteInstance {},
	laser_luch_R: class extends self.ISpriteInstance {},
	iskry_tech: class extends self.IParticlesInstance {},
	efir_Light: class extends self.ISpriteInstance {},
	spawner_cube_l: class extends self.ISpriteInstance {},
	weapon_flash: class extends self.ISpriteInstance {},
	Dym_laser: class extends self.IParticlesInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	oval_ataki: class extends self.ISpriteInstance {},
	chraracters_portraits: class extends self.ISpriteInstance {},
	dialog_button_fon: class extends self.ISpriteInstance {},
	dialog_button: class extends self.ISpriteInstance {},
	Tovary2: class extends self.ISpriteInstance {},
	loot_text: class extends self.ITextInstance {},
	Glaz: class extends self.ISpriteInstance {},
	blik_glaza: class extends self.ISpriteInstance {},
	stamina_text: class extends self.ITextInstance {},
	blesk: class extends self.ISpriteInstance {},
	Спрайт40: class extends self.ISpriteInstance {},
	Blocks3: class extends self.ISpriteInstance {},
	rain_drops: class extends self.IParticlesInstance {},
	rain_drops2: class extends self.IParticlesInstance {},
	spawner_cube_r: class extends self.ISpriteInstance {},
	spawner_cube_t: class extends self.ISpriteInstance {},
	spawner_cube_b: class extends self.ISpriteInstance {},
	spawner_area: class extends self.ISpriteInstance {},
	temnota: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	quest_info: class extends self.ITextInstance {},
	strelka: class extends self.ISpriteInstance {},
	strelka_weapon: class extends self.ISpriteInstance {},
	sofa: class extends self.ISpriteInstance {},
	Pyl: class extends self.IParticlesInstance {},
	Block_special: class extends self.ISpriteInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	hand_sofa_l: class extends self.ISpriteInstance {},
	hand_sofa_l2: class extends self.ISpriteInstance {},
	Rychag: class extends self.ISpriteInstance {},
	portal_base: class extends self.ISpriteInstance {},
	portal: class extends self.ISpriteInstance {},
	kick_icon: class extends self.ISpriteInstance {},
	Частицы10: class extends self.IParticlesInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	Спрайт12: class extends self.ISpriteInstance {},
	spawn_circle: class extends self.ISpriteInstance {},
	ruki_hlopayut: class extends self.ISpriteInstance {},
	Спрайт13: class extends self.ISpriteInstance {},
	Спрайт14: class extends self.ISpriteInstance {},
	Частицы12: class extends self.IParticlesInstance {},
	Спрайт15: class extends self.ISpriteInstance {},
	robo: class extends self.ISpriteInstance {},
	robo_text: class extends self.ITextInstance {},
	robo_line: class extends self.ISpriteInstance {},
	tech_bar: class extends self.ISpriteInstance {},
	robo_head: class extends self.ISpriteInstance {},
	tech_death_part: class extends self.IParticlesInstance {},
	iskry_potok: class extends self.IParticlesInstance {},
	kusok_ice_robo: class extends self.ISpriteInstance {},
	Bullet_e: class extends self.ISpriteInstance {},
	Ice_part_vystrel: class extends self.IParticlesInstance {},
	Acid_cloud: class extends self.IParticlesInstance {},
	ice_cloud: class extends self.IParticlesInstance {},
	sneg_cloud: class extends self.IParticlesInstance {},
	fire_shot: class extends self.IParticlesInstance {},
	fire_shot_yellow: class extends self.IParticlesInstance {},
	acid_shot: class extends self.IParticlesInstance {},
	acid_shot_yellow: class extends self.IParticlesInstance {},
	pila_fire: class extends self.ISpriteInstance {},
	fire_sparks: class extends self.IParticlesInstance {},
	acid_light_shot: class extends self.ISpriteInstance {},
	laser_part: class extends self.IParticlesInstance {},
	svechenie_laser_R: class extends self.ISpriteInstance {},
	svechenie_laser_L: class extends self.ISpriteInstance {},
	laser_luch_L: class extends self.ISpriteInstance {},
	laser_parts_pop_R: class extends self.IParticlesInstance {},
	laser_parts_pop_L: class extends self.IParticlesInstance {},
	blue_light_shoot: class extends self.ISpriteInstance {},
	sosulka_s_neba: class extends self.ISpriteInstance {},
	oskolki_tenb: class extends self.IParticlesInstance {},
	Kolco_lda_mini: class extends self.ISpriteInstance {},
	Kolco_ognia: class extends self.ISpriteInstance {},
	meteor_s_neba: class extends self.ISpriteInstance {},
	oskolki_kamnia: class extends self.IParticlesInstance {},
	Частицы: class extends self.IParticlesInstance {},
	Tail_4: class extends self.ITiledBackgroundInstance {},
	Trees4: class extends self.ISpriteInstance {},
	fire_stones: class extends self.ISpriteInstance {},
	ogonek: class extends self.ISpriteInstance {},
	Trees6: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	ice_stones: class extends self.ISpriteInstance {},
	kusok_ice_zvuk: class extends self.ISpriteInstance {},
	snejinki_death: class extends self.IParticlesInstance {},
	kusok_ice_z2: class extends self.ISpriteInstance {},
	kusok_ice_robo2: class extends self.ISpriteInstance {},
	rain_sparks: class extends self.IParticlesInstance {},
	Light_ground_lantern: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Спрайт19: class extends self.ISpriteInstance {},
	Спрайт20: class extends self.ISpriteInstance {},
	Спрайт21: class extends self.ISpriteInstance {},
	s1: class extends self.ISpriteInstance {},
	s2: class extends self.ISpriteInstance {},
	s3: class extends self.ISpriteInstance {},
	heal_sparks: class extends self.IParticlesInstance {},
	flesh_popadanie: class extends self.IParticlesInstance {},
	tech_popadanie: class extends self.IParticlesInstance {},
	fire_shoot: class extends self.ISpriteInstance {},
	efir_light_shoot: class extends self.ISpriteInstance {},
	puzyr: class extends self.ISpriteInstance {},
	vsplesk_puz: class extends self.IParticlesInstance {},
	Z_fire: class extends self.ISpriteInstance {},
	Z_fire_head: class extends self.ISpriteInstance {},
	z_fire_line: class extends self.ISpriteInstance {},
	z_fire_text: class extends self.ITextInstance {},
	fire_bar: class extends self.ISpriteInstance {},
	kusok_ice_z_fire: class extends self.ISpriteInstance {},
	kusok_ice_z_fire2: class extends self.ISpriteInstance {},
	Спрайт16: class extends self.ISpriteInstance {},
	barrels: class extends self.ISpriteInstance {},
	Ring_fire_barrel: class extends self.ISpriteInstance {},
	Спрайт17: class extends self.ISpriteInstance {},
	vzryvatel: class extends self.ISpriteInstance {},
	Ring_ice_barrel: class extends self.ISpriteInstance {},
	Ring_ice_barrel2: class extends self.ISpriteInstance {},
	Ring_ice_barrel3: class extends self.ISpriteInstance {},
	vsplesk_acid: class extends self.IParticlesInstance {},
	vsplesk_efir: class extends self.IParticlesInstance {},
	efir_smoke: class extends self.IParticlesInstance {},
	light_exp2: class extends self.ISpriteInstance {},
	udar_pulia: class extends self.ISpriteInstance {},
	Спрайт22: class extends self.ISpriteInstance {},
	effect_udara: class extends self.ISpriteInstance {},
	z1_kusok: class extends self.ISpriteInstance {},
	z_fire_kusok: class extends self.ISpriteInstance {},
	robo_kusok: class extends self.ISpriteInstance {},
	kills_og: class extends self.ITextInstance {},
	kills_kis: class extends self.ITextInstance {},
	kills_hol: class extends self.ITextInstance {},
	ice_ghoul: class extends self.ISpriteInstance {},
	Z_acid: class extends self.ISpriteInstance {},
	Z_ice_head: class extends self.ISpriteInstance {},
	z_ice_text: class extends self.ITextInstance {},
	z_ice_line: class extends self.ISpriteInstance {},
	ice_bar: class extends self.ISpriteInstance {},
	kusok_ice_z_ice: class extends self.ISpriteInstance {},
	kusok_ice_z_ice2: class extends self.ISpriteInstance {},
	z_ice_kusok: class extends self.ISpriteInstance {},
	Z_acid_head: class extends self.ISpriteInstance {},
	z_acid_text: class extends self.ITextInstance {},
	z_acid_line: class extends self.ISpriteInstance {},
	acid_bar: class extends self.ISpriteInstance {},
	kusok_acid: class extends self.ISpriteInstance {},
	kusok_acid2: class extends self.ISpriteInstance {},
	z_acid_kusok: class extends self.ISpriteInstance {},
	Z_efir: class extends self.ISpriteInstance {},
	z_efir_text: class extends self.ITextInstance {},
	z_efir_line: class extends self.ISpriteInstance {},
	efir_bar: class extends self.ISpriteInstance {},
	Z_efir_head: class extends self.ISpriteInstance {},
	kusok_efir: class extends self.ISpriteInstance {},
	kusok_efir2: class extends self.ISpriteInstance {},
	z_efir_kusok: class extends self.ISpriteInstance {},
	D_player: class extends self.ITextInstance {},
	D_player_fire: class extends self.ITextInstance {},
	D_player_acid: class extends self.ITextInstance {},
	D_player_ice: class extends self.ITextInstance {},
	D_player_efir: class extends self.ITextInstance {},
	tykva_sparks: class extends self.IParticlesInstance {},
	snow_sparks: class extends self.IParticlesInstance {},
	Dym_part_for_fire: class extends self.IParticlesInstance {},
	Dym_red_for_fire: class extends self.IParticlesInstance {},
	lantern: class extends self.ISpriteInstance {},
	vorona: class extends self.ISpriteInstance {},
	vorona_spawner: class extends self.ISpriteInstance {},
	perya: class extends self.IParticlesInstance {},
	vorona_krov: class extends self.IParticlesInstance {},
	acid_props: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	Частицы7: class extends self.IParticlesInstance {},
	motor: class extends self.ISpriteInstance {},
	porshen: class extends self.ISpriteInstance {},
	acid_spray_little: class extends self.IParticlesInstance {},
	pero: class extends self.ISpriteInstance {},
	strelki: class extends self.ISpriteInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	Pochva3: class extends self.ISpriteInstance {},
	gorod_props: class extends self.ISpriteInstance {},
	oskolki_lda2: class extends self.IParticlesInstance {},
	lift: class extends self.ISpriteInstance {},
	Спрайт23: class extends self.ISpriteInstance {},
	lift_mark: class extends self.ISpriteInstance {},
	lift_point: class extends self.ISpriteInstance {},
	lift_sparks: class extends self.IParticlesInstance {},
	Plity2: class extends self.ISpriteInstance {},
	efir_sparks: class extends self.IParticlesInstance {},
	ef_part: class extends self.IParticlesInstance {},
	Z_2: class extends self.ISpriteInstance {},
	Z_head2: class extends self.ISpriteInstance {},
	z_2_text: class extends self.ITextInstance {},
	z_2_line: class extends self.ISpriteInstance {},
	kusok_ice_z22: class extends self.ISpriteInstance {},
	kusok2_ice_z_22: class extends self.ISpriteInstance {},
	z2_kusok: class extends self.ISpriteInstance {},
	hand_throw: class extends self.ISpriteInstance {},
	Частицы8: class extends self.IParticlesInstance {},
	Частицы9: class extends self.IParticlesInstance {},
	lesnik: class extends self.ISpriteInstance {},
	jug1_head: class extends self.ISpriteInstance {},
	jug1_text: class extends self.ITextInstance {},
	jug1_line: class extends self.ISpriteInstance {},
	_1_kusok_ice_Jug1: class extends self.ISpriteInstance {},
	_1_kusok_ice_Jug2: class extends self.ISpriteInstance {},
	jug1_kusok: class extends self.ISpriteInstance {},
	vzmah_topora: class extends self.ISpriteInstance {},
	snejok: class extends self.ISpriteInstance {},
	ice2_head: class extends self.ISpriteInstance {},
	ice2_text: class extends self.ITextInstance {},
	ice2_line: class extends self.ISpriteInstance {},
	kusok_ice2_1: class extends self.ISpriteInstance {},
	ice2_kusok: class extends self.ISpriteInstance {},
	kusok_ice2_2: class extends self.ISpriteInstance {},
	snowball: class extends self.ISpriteInstance {},
	Buran: class extends self.ISpriteInstance {},
	buran_head: class extends self.ISpriteInstance {},
	buran_text: class extends self.ITextInstance {},
	buran_line: class extends self.ISpriteInstance {},
	kusok_buran_1: class extends self.ISpriteInstance {},
	buran_kusok: class extends self.ISpriteInstance {},
	kusok_buran_2: class extends self.ISpriteInstance {},
	ice_spear: class extends self.ISpriteInstance {},
	Ice_cube_player22: class extends self.ISpriteInstance {},
	Ice_cube_player: class extends self.ISpriteInstance {},
	snejinki_kolco2: class extends self.IParticlesInstance {},
	cyber: class extends self.ISpriteInstance {},
	cyber_head: class extends self.ISpriteInstance {},
	cyber_text: class extends self.ITextInstance {},
	cyber_line: class extends self.ISpriteInstance {},
	kusok_cyber1: class extends self.ISpriteInstance {},
	cyber_kusok: class extends self.ISpriteInstance {},
	kusok_cyber2: class extends self.ISpriteInstance {},
	laser_bullet: class extends self.ISpriteInstance {},
	circ: class extends self.ISpriteInstance {},
	circ_saw: class extends self.ISpriteInstance {},
	pila_ten222: class extends self.ISpriteInstance {},
	circ_part: class extends self.IParticlesInstance {},
	circ_head: class extends self.ISpriteInstance {},
	circ_text: class extends self.ITextInstance {},
	circ_line: class extends self.ISpriteInstance {},
	kusok_ice_circ1: class extends self.ISpriteInstance {},
	circ_kusok: class extends self.ISpriteInstance {},
	kusok_ice_circ2: class extends self.ISpriteInstance {},
	Gnil: class extends self.ISpriteInstance {},
	Gnil_text: class extends self.ITextInstance {},
	Gnil_line: class extends self.ISpriteInstance {},
	kusok_Gnil1: class extends self.ISpriteInstance {},
	Gnil_kusok: class extends self.ISpriteInstance {},
	kusok_Gnil2: class extends self.ISpriteInstance {},
	Gnil_head: class extends self.ISpriteInstance {},
	pump_throw: class extends self.ISpriteInstance {},
	pump_throw222: class extends self.ISpriteInstance {},
	Спрайт18: class extends self.ISpriteInstance {},
	pump_circl: class extends self.ISpriteInstance {},
	tykva_pyl_effect: class extends self.IParticlesInstance {},
	zajigalka: class extends self.ISpriteInstance {},
	zaj_text: class extends self.ITextInstance {},
	zaj_line: class extends self.ISpriteInstance {},
	kusok_ice_zaj1: class extends self.ISpriteInstance {},
	zaj_kusok: class extends self.ISpriteInstance {},
	kusok_ice_zaj2: class extends self.ISpriteInstance {},
	zaj_head: class extends self.ISpriteInstance {},
	zaj_throw: class extends self.ISpriteInstance {},
	fire_ring: class extends self.IParticlesInstance {},
	ognevik: class extends self.ISpriteInstance {},
	og_head: class extends self.ISpriteInstance {},
	og_text: class extends self.ITextInstance {},
	og_line: class extends self.ISpriteInstance {},
	kusok_ice_og1: class extends self.ISpriteInstance {},
	og_kusok: class extends self.ISpriteInstance {},
	kusok_ice_og2: class extends self.ISpriteInstance {},
	og_throw: class extends self.ISpriteInstance {},
	sparks3: class extends self.IParticlesInstance {},
	Dem: class extends self.ISpriteInstance {},
	Dem_mini: class extends self.ISpriteInstance {},
	dem_head: class extends self.ISpriteInstance {},
	dem_text: class extends self.ITextInstance {},
	kusok_ice_dem1: class extends self.ISpriteInstance {},
	dem_kusok: class extends self.ISpriteInstance {},
	kusok_ice_dem2: class extends self.ISpriteInstance {},
	dem_line: class extends self.ISpriteInstance {},
	dem_luch: class extends self.ISpriteInstance {},
	svechenie_dem: class extends self.ISpriteInstance {},
	dem_mini_circl: class extends self.ISpriteInstance {},
	Storoj: class extends self.ISpriteInstance {},
	stor_head: class extends self.ISpriteInstance {},
	stor_text: class extends self.ITextInstance {},
	stor_line: class extends self.ISpriteInstance {},
	kusok_ice_stor1: class extends self.ISpriteInstance {},
	stor_kusok: class extends self.ISpriteInstance {},
	kusok_ice_stor2: class extends self.ISpriteInstance {},
	oil_brizgi: class extends self.ISpriteInstance {},
	birn1: class extends self.IParticlesInstance {},
	birn2: class extends self.IParticlesInstance {},
	oval_ataki_2: class extends self.ISpriteInstance {},
	Lich: class extends self.ISpriteInstance {},
	lich_head: class extends self.ISpriteInstance {},
	lich_text: class extends self.ITextInstance {},
	lich_line: class extends self.ISpriteInstance {},
	lich_spear: class extends self.ISpriteInstance {},
	kusok_lich1: class extends self.ISpriteInstance {},
	lich_kusok: class extends self.ISpriteInstance {},
	kusok_lich2: class extends self.ISpriteInstance {},
	ice_head: class extends self.ISpriteInstance {},
	plevun: class extends self.ISpriteInstance {},
	ple_text: class extends self.ITextInstance {},
	ple_line: class extends self.ISpriteInstance {},
	kusok_ple1: class extends self.ISpriteInstance {},
	ple_kusok: class extends self.ISpriteInstance {},
	kusok_ple2: class extends self.ISpriteInstance {},
	ple_head: class extends self.ISpriteInstance {},
	plevok: class extends self.ISpriteInstance {},
	kislyi: class extends self.ISpriteInstance {},
	kis_head: class extends self.ISpriteInstance {},
	kis_text: class extends self.ITextInstance {},
	kis_line: class extends self.ISpriteInstance {},
	kusok_kis1: class extends self.ISpriteInstance {},
	kis_kusok: class extends self.ISpriteInstance {},
	kusok_kis2: class extends self.ISpriteInstance {},
	kis_spear: class extends self.ISpriteInstance {},
	poison_circl: class extends self.ISpriteInstance {},
	Acid_cloud2: class extends self.IParticlesInstance {},
	acid_cube_player: class extends self.ISpriteInstance {},
	Saya: class extends self.ISpriteInstance {},
	saya_head: class extends self.ISpriteInstance {},
	kusok_saya1: class extends self.ISpriteInstance {},
	saya_kusok: class extends self.ISpriteInstance {},
	kusok_saya2: class extends self.ISpriteInstance {},
	ef_spear: class extends self.ISpriteInstance {},
	Efirness: class extends self.ISpriteInstance {},
	efi_head: class extends self.ISpriteInstance {},
	efi_text: class extends self.ITextInstance {},
	efi_line: class extends self.ISpriteInstance {},
	kusok_efi1: class extends self.ISpriteInstance {},
	efi_kusok: class extends self.ISpriteInstance {},
	kusok_efi2: class extends self.ISpriteInstance {},
	efi_spear: class extends self.ISpriteInstance {},
	efir_spray_shoot: class extends self.IParticlesInstance {},
	sa_text: class extends self.ITextInstance {},
	sa_line: class extends self.ISpriteInstance {},
	nevesta: class extends self.ISpriteInstance {},
	nev_head: class extends self.ISpriteInstance {},
	nev_text: class extends self.ITextInstance {},
	nev_line: class extends self.ISpriteInstance {},
	nev_spear: class extends self.ISpriteInstance {},
	kusok_nev1: class extends self.ISpriteInstance {},
	nev_kusok: class extends self.ISpriteInstance {},
	kusok_nev2: class extends self.ISpriteInstance {},
	nev_circl: class extends self.ISpriteInstance {},
	nev_fly_head: class extends self.ISpriteInstance {},
	Krov_potok2: class extends self.IParticlesInstance {},
	nev_kiss: class extends self.ISpriteInstance {},
	efir_popadanie: class extends self.IParticlesInstance {},
	Ryglo: class extends self.ISpriteInstance {},
	ryg_text: class extends self.ITextInstance {},
	ryg_line: class extends self.ISpriteInstance {},
	ryg_head: class extends self.ISpriteInstance {},
	kusok_ryg1: class extends self.ISpriteInstance {},
	ryg_kusok: class extends self.ISpriteInstance {},
	kusok_ryg2: class extends self.ISpriteInstance {},
	acid_brizgi: class extends self.ISpriteInstance {},
	birn3: class extends self.IParticlesInstance {},
	acid_spray_part2: class extends self.IParticlesInstance {},
	ryg_circl: class extends self.ISpriteInstance {},
	acid_popadanie: class extends self.IParticlesInstance {},
	iskry_znak: class extends self.IParticlesInstance {},
	spawn_spawn: class extends self.ISpriteInstance {},
	fire_popadanie: class extends self.IParticlesInstance {},
	Словарь: class extends self.IDictionaryInstance {},
	Браузер: class extends self.IInstance {},
	death_text: class extends self.ITextInstance {},
	button_reward: class extends self.ISpriteInstance {},
	butt_2: class extends self.ISpriteInstance {},
	button_text: class extends self.ITextInstance {},
	Resurrect_base: class extends self.ITextInstance {},
	ott_circl: class extends self.ISpriteInstance {},
	spawn_player: class extends self.ISpriteInstance {},
	pyl_nogi: class extends self.IParticlesInstance {},
	quests_point: class extends self.ISpriteInstance {},
	tykva_ruletka: class extends self.ISpriteInstance {},
	pult_circle: class extends self.ISpriteInstance {},
	Plita_ruletka1: class extends self.ISpriteInstance {},
	Plita_ruletka2: class extends self.ISpriteInstance {},
	Plita_ruletka3: class extends self.ISpriteInstance {},
	podplita2: class extends self.ISpriteInstance {},
	podplita3: class extends self.ISpriteInstance {},
	kick_icon222: class extends self.ISpriteInstance {},
	YandexGamesSDK: class extends self.IInstance {},
	train_props: class extends self.ISpriteInstance {},
	comment_trig: class extends self.ISpriteInstance {},
	train_images: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	train_text: class extends self.ITextInstance {},
	quest_text: class extends self.ITextInstance {},
	train_znak: class extends self.ISpriteInstance {},
	podlojka: class extends self.ISpriteInstance {},
	train_part: class extends self.IParticlesInstance {},
	zas: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	p: class extends self.ISpriteInstance {},
	knopka: class extends self.IButtonInstance {},
	f1: class extends self.ISpriteInstance {},
	f2: class extends self.ISpriteInstance {},
	zvezda: class extends self.ISpriteInstance {},
	p2: class extends self.ISpriteInstance {},
	centr: class extends self.ISpriteInstance {},
	zas2: class extends self.ISpriteInstance {},
	zas3: class extends self.ISpriteInstance {},
	zvezda2: class extends self.ISpriteInstance {},
	zvezda3: class extends self.ISpriteInstance {},
	p3: class extends self.ISpriteInstance {},
	zas4: class extends self.ISpriteInstance {},
	bel: class extends self.ISpriteInstance {},
	bel2: class extends self.ISpriteInstance {},
	Спрайт25: class extends self.ISpriteInstance {},
	shit: class extends self.ISpriteInstance {},
	sh: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	portal_boss: class extends self.ISpriteInstance {},
	portal_boss2: class extends self.ISpriteInstance {},
	Спрайт26: class extends self.ISpriteInstance {},
	o: class extends self.ISpriteInstance {},
	Plity3: class extends self.ISpriteInstance {},
	Спрайт27: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	Listya2: class extends self.ISpriteInstance {},
	butt_3: class extends self.ISpriteInstance {},
	ПокупкиВПриложенияхIAP: class extends self.IInstance {},
	kurs: class extends self.ISpriteInstance {},
	blood_navylet: class extends self.IParticlesInstance {},
	icon3: class extends self.ISpriteInstance {},
	shit_infa: class extends self.ISpriteInstance {},
	shit_strelki: class extends self.ISpriteInstance {},
	kills_boss: class extends self.ITextInstance {},
	boss_point: class extends self.ISpriteInstance {},
	che: class extends self.ISpriteInstance {},
	Спрайт28: class extends self.ISpriteInstance {},
	shans: class extends self.ISpriteInstance {},
	s_10: class extends self.ISpriteInstance {},
	Listya3: class extends self.ISpriteInstance {},
	stih: class extends self.ISpriteInstance {},
	Gates2: class extends self.ISpriteInstance {},
	ammo_ark_text2: class extends self.ITextInstance {},
	runs: class extends self.ISpriteInstance {},
	info_reklama_okno: class extends self.ISpriteInstance {},
	info_text_reklama: class extends self.ITextInstance {},
	Enemies: class extends self.ISpriteInstance {},
	Icons: class extends self.ISpriteInstance {},
	Player_parts: class extends self.ISpriteInstance {},
	loot: class extends self.ISpriteInstance {},
	Interface: class extends self.ISpriteInstance {},
	text_family: class extends self.ITextInstance {},
	parts_1: class extends self.ISpriteInstance {},
	Shariki: class extends self.ISpriteInstance {},
	Cubes_stihii: class extends self.ISpriteInstance {},
	skill_icons: class extends self.ISpriteInstance {},
	strelki_joy: class extends self.ISpriteInstance {},
	magaz_objects: class extends self.ISpriteInstance {},
	props: class extends self.ISpriteInstance {},
	Bloks: class extends self.ISpriteInstance {},
	cubes_spawn: class extends self.ISpriteInstance {},
	Tech_enemy: class extends self.ISpriteInstance {},
	Flesh_enemy: class extends self.ISpriteInstance {},
	lasers: class extends self.ISpriteInstance {},
	laser_parts: class extends self.IParticlesInstance {},
	Cifry_urona: class extends self.ITextInstance {},
	Rains: class extends self.IParticlesInstance {},
	acid_enemy: class extends self.ISpriteInstance {},
	fire_enemy: class extends self.ISpriteInstance {},
	ice_enemy: class extends self.ISpriteInstance {},
	efir_enemy: class extends self.ISpriteInstance {},
	heads: class extends self.ISpriteInstance {},
	lines: class extends self.ISpriteInstance {},
	Delete: class extends self.ISpriteInstance {},
	Delete2: class extends self.IParticlesInstance {},
	Delete3: class extends self.IParticlesInstance {},
	Delete4: class extends self.IParticlesInstance {},
	interface_2: class extends self.ITextInstance {}
}